#Pandas Foundation

##A. What is Pandas and When to use it?
Pandas is a Python library for **data manipulation and analysis**.

It provides high-performance, easy-to-use data structures **(Series, DataFrame)** and functions to work with **structured data**.

It is widely used in:

**Data cleaning**

**Data exploration / analysis**

**Aggregation & summarization**

**Preparing datasets for machine learning**

In [1]:
import pandas as pd

In [2]:
print(pd.__version__)

2.2.2

#B. Pandas Series
A Series is a **1-dimensional labeled array** capable of holding any data type **(integers, floats, strings, etc.).**

**Each element has an index, which is like a row label.**

**Think of Series as a single column of a DataFrame.**

**Vectorized operations work on Series.**

##Creating Series 1. From a list

In [3]:
data = [10,20,30,40]
s = pd.Series(data)
print(s)

0    10
1    20
2    30
3    40
dtype: int64

##2. From a list with custom index

In [8]:
s1 = pd.Series(data, index = ['a','b','c','d'])
print(s1)

a    10
b    20
c    30
d    40
dtype: int64

##3. From a Dictionary

In [129]:
data_dict = {'Math':90,'Science': 85, 'English': 95}
s2 = pd.Series(data_dict)
print(s2)

Math       90
Science    85
English    95
dtype: int64

##4. Check values, index, dtype

In [15]:
print("Values of s2 and s1 are: \n")
print(s2.values)
print(s1.values, "\n")

print("Index of s2 and s1 are: \n")
print(s2.index)
print(s1.index, "\n")

print("dtype of s2 and s1 are: \n")
print(s2.dtype)
print(s1.dtype)

Values of s2 and s1 are:

[90 85 95]
[10 20 30 40]

Index of s2 and s1 are:

Index(['Math', 'Science', 'English'], dtype='object')
Index(['a', 'b', 'c', 'd'], dtype='object')

dtype of s2 and s1 are:

int64
int64

#Series Operations are Vectorized

In [16]:
print(s)

0    10
1    20
2    30
3    40
dtype: int64

##Multiply whole column with 5, Vectorized

In [17]:
print(s*5)

0     50
1    100
2    150
3    200
dtype: int64

In [18]:
print(s2*5)

Math       450
Science    425
English    475
dtype: int64

#Can select elements by index or position:

##Select Element by Position

In [25]:
print(s[1])

20

##Select element by Label

In [27]:
print(s2['Math'])

90

##Missing values are represented as Nan

In [31]:
missing = [10, None, 50, None, 70, 80, None]
s3 = pd.Series(missing, index = ['a','b','c','d','e','f','g'])
print(s3)

a    10.0
b     NaN
c    50.0
d     NaN
e    70.0
f    80.0
g     NaN
dtype: float64

#C. Pandas DataFrame
A DataFrame is a **2-dimensional labeled** data structure, like an Excel spreadsheet or SQL table.

**Consists of rows and columns**.

**Each column is a Series, but columns can have different data types.**

**Index identifies rows; column names identify columns.**

**All pandas operations (filtering, cleaning, grouping) work on DataFrames**

##Key properties:

df.shape → rows x columns

df.columns → column names

df.index → row labels

df.dtypes → column data types

##Creating DataFrames
###1. From Dictionary

In [32]:
data = {
    'Name': ['Ali', 'Sana', 'Omar'],
    'Math': [90, 80, 75],
    'Science': [85, 95, 65]
}
df = pd.DataFrame(data)
print(df)

   Name  Math  Science
0   Ali    90       85
1  Sana    80       95
2  Omar    75       65

###If you add index to dictionaries columns names changed to 0,1,2...

In [42]:
df3 = pd.DataFrame(data, index = ['a','b','c'])
print(df3)

      0   1   2
a   Ali  90  85
b  Sana  80  95
c  Omar  75  65

In [43]:
df3 = pd.DataFrame(data, index = ['a','b','c'], columns = ['Math', "Science", "Name"])
print(df3)

   Math  Science  Name
a   Ali       90    85
b  Sana       80    95
c  Omar       75    65

##2. From list of lists with column names

In [33]:
data = [
    ['Ali', 90, 85],
    ['Sana', 80, 95],
    ['Omar', 75, 65]
]
df1 = pd.DataFrame(data)
print(df1)

      0   1   2
0   Ali  90  85
1  Sana  80  95
2  Omar  75  65

###Setting Column Names

In [34]:
df2_names = pd.DataFrame(data, columns= ["Names", "Math", "English"])
print(df2_names)

  Names  Math  English
0   Ali    90       85
1  Sana    80       95
2  Omar    75       65

###Setting Indexes

In [38]:
df2_index = pd.DataFrame(data,index = ['a','b','c'])
print(df2_index)

      0   1   2
a   Ali  90  85
b  Sana  80  95
c  Omar  75  65

###Setting Both Columns and Indexes

In [45]:
df4 = pd.DataFrame(data, index= ['a','b','c'], columns= ['Name', 'Math', 'Science'])
print(df4)

   Name  Math  Science
a   Ali    90       85
b  Sana    80       95
c  Omar    75       65

##3. Inspecting data

In [54]:
inspect = {
          "Name": ["Abdullah", "Ali", "Maaz", "Asif", "Saad", "Faad", "Majid", "Azaan", "Sijjad", "Masab", "Hanzallah","Zafar"],
          "Maths": [90,89,None,89,90,None,89,88,90,87,85,None],
          "Science": [None,45,78,90,None,89,88,76,87,84,92,78]
}

In [55]:
s4 = pd.Series(inspect)
print(s4)

Name       [Abdullah, Ali, Maaz, Asif, Saad, Faad, Majid,...
Maths      [90, 89, None, 89, 90, None, 89, 88, 90, 87, 8...
Science    [None, 45, 78, 90, None, 89, 88, 76, 87, 84, 9...
dtype: object

In [56]:
df5 = pd.DataFrame(inspect)
print(df5)

         Name  Maths  Science
0    Abdullah   90.0      NaN
1         Ali   89.0     45.0
2        Maaz    NaN     78.0
3        Asif   89.0     90.0
4        Saad   90.0      NaN
5        Faad    NaN     89.0
6       Majid   89.0     88.0
7       Azaan   88.0     76.0
8      Sijjad   90.0     87.0
9       Masab   87.0     84.0
10  Hanzallah   85.0     92.0
11      Zafar    NaN     78.0

df.head()      # first 5 rows

df.tail()      # last 5 rows

df.info()      # summary

df.describe()  # statistics for numeric columns

df.shape       # dimensions

df.columns     # column names

df.dtypes      # data types

##df.head()

In [57]:
print(df5.head())

       Name  Maths  Science
0  Abdullah   90.0      NaN
1       Ali   89.0     45.0
2      Maaz    NaN     78.0
3      Asif   89.0     90.0
4      Saad   90.0      NaN

##df.tail()

In [58]:
print(df5.tail())

         Name  Maths  Science
7       Azaan   88.0     76.0
8      Sijjad   90.0     87.0
9       Masab   87.0     84.0
10  Hanzallah   85.0     92.0
11      Zafar    NaN     78.0

##df.info()

In [59]:
print(df5.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     12 non-null     object
 1   Maths    9 non-null      float64
 2   Science  10 non-null     float64
dtypes: float64(2), object(1)
memory usage: 420.0+ bytes
None

##df.describe()

In [60]:
print(df5.describe())

           Maths    Science
count   9.000000  10.000000
mean   88.555556  80.700000
std     1.666667  13.736003
min    85.000000  45.000000
25%    88.000000  78.000000
50%    89.000000  85.500000
75%    90.000000  88.750000
max    90.000000  92.000000

##df.shape

In [61]:
print(df5.shape)

(12, 3)

##df.columns

In [62]:
print(df5.columns)

Index(['Name', 'Maths', 'Science'], dtype='object')

##df.dtypes

In [63]:
print(df5.dtypes)

Name        object
Maths      float64
Science    float64
dtype: object

#1. Column Access

##Access in Series

In [64]:
print(s4)

Name       [Abdullah, Ali, Maaz, Asif, Saad, Faad, Majid,...
Maths      [90, 89, None, 89, 90, None, 89, 88, 90, 87, 8...
Science    [None, 45, 78, 90, None, 89, 88, 76, 87, 84, 9...
dtype: object

In [141]:
print("Access Column:")
print(s4[0],"\n")
#Or
print(s4["Name"])

print("Access Element in Column:")
print(s4[0][4],"\n")
#Or
print(s4["Name"][4])

Access Column:
['Abdullah', 'Ali', 'Maaz', 'Asif', 'Saad', 'Faad', 'Majid', 'Azaan', 'Sijjad', 'Masab', 'Hanzallah', 'Zafar']

['Abdullah', 'Ali', 'Maaz', 'Asif', 'Saad', 'Faad', 'Majid', 'Azaan', 'Sijjad', 'Masab', 'Hanzallah', 'Zafar']
Access Element in Column:
Saad

Saad

/tmp/ipykernel_579/1487282324.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s4[0],"\n")
/tmp/ipykernel_579/1487282324.py:7: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s4[0][4],"\n")

##Access in DataFrame

In [74]:
print(df5)

         Name  Maths  Science
0    Abdullah   90.0      NaN
1         Ali   89.0     45.0
2        Maaz    NaN     78.0
3        Asif   89.0     90.0
4        Saad   90.0      NaN
5        Faad    NaN     89.0
6       Majid   89.0     88.0
7       Azaan   88.0     76.0
8      Sijjad   90.0     87.0
9       Masab   87.0     84.0
10  Hanzallah   85.0     92.0
11      Zafar    NaN     78.0

In [84]:
print(df5[["Name"]].head(),"\n")
print(df5[["Name","Maths"]].head())

       Name
0  Abdullah
1       Ali
2      Maaz
3      Asif
4      Saad

       Name  Maths
0  Abdullah   90.0
1       Ali   89.0
2      Maaz    NaN
3      Asif   89.0
4      Saad   90.0

#2. Row Access

##DataFrames

In [90]:
print(df5)

         Name  Maths  Science
0    Abdullah   90.0      NaN
1         Ali   89.0     45.0
2        Maaz    NaN     78.0
3        Asif   89.0     90.0
4        Saad   90.0      NaN
5        Faad    NaN     89.0
6       Majid   89.0     88.0
7       Azaan   88.0     76.0
8      Sijjad   90.0     87.0
9       Masab   87.0     84.0
10  Hanzallah   85.0     92.0
11      Zafar    NaN     78.0

##Loc By Label/Index

In [95]:
print(df5.loc[3],"\n") #3 is label or index in DataFrame
print(df5.loc[3][2])

Name       Asif
Maths      89.0
Science    90.0
Name: 3, dtype: object

90.0

/tmp/ipykernel_579/2984010126.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(df5.loc[3][2])

##iloc By Integer Position

In [112]:
print(df5.iloc[3])
print(df5.iloc[3][1])

Name        Asif
Maths       89.0
Science     90.0
Total      179.0
Name: 3, dtype: object
89.0

/tmp/ipykernel_579/1226975949.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(df5.iloc[3][1])

#3. Adding New Columns

In [106]:
df5['Total'] = df5['Maths'] + df5['Science']
print(df5)

         Name  Maths  Science  Total
0    Abdullah   90.0      NaN    NaN
1         Ali   89.0     45.0  134.0
2        Maaz    NaN     78.0    NaN
3        Asif   89.0     90.0  179.0
4        Saad   90.0      NaN    NaN
5        Faad    NaN     89.0    NaN
6       Majid   89.0     88.0  177.0
7       Azaan   88.0     76.0  164.0
8      Sijjad   90.0     87.0  177.0
9       Masab   87.0     84.0  171.0
10  Hanzallah   85.0     92.0  177.0
11      Zafar    NaN     78.0    NaN

Make a new column here using dictionaries.

Then convert it into DataFrame.

And assign it DataFrame in which I wanted to add it.

In [119]:
Test_column = {"Testing": [4,5,6,7,1,2,3,8,9,10,11,12]}
df6 = pd.DataFrame(Test_column)
print(df6, "\n")
df5['New'] = df6['Testing']
print(df5)

    Testing
0         4
1         5
2         6
3         7
4         1
5         2
6         3
7         8
8         9
9        10
10       11
11       12

         Name  Maths  Science  Total  New
0    Abdullah   90.0      NaN    NaN    4
1         Ali   89.0     45.0  134.0    5
2        Maaz    NaN     78.0    NaN    6
3        Asif   89.0     90.0  179.0    7
4        Saad   90.0      NaN    NaN    1
5        Faad    NaN     89.0    NaN    2
6       Majid   89.0     88.0  177.0    3
7       Azaan   88.0     76.0  164.0    8
8      Sijjad   90.0     87.0  177.0    9
9       Masab   87.0     84.0  171.0   10
10  Hanzallah   85.0     92.0  177.0   11
11      Zafar    NaN     78.0    NaN   12

#4. Renaming Columns

In [121]:
df5.rename(columns={"New": "New_Addtion"},inplace=True)
print(df5)

         Name  Maths  Science  Total  New_Addtion
0    Abdullah   90.0      NaN    NaN            4
1         Ali   89.0     45.0  134.0            5
2        Maaz    NaN     78.0    NaN            6
3        Asif   89.0     90.0  179.0            7
4        Saad   90.0      NaN    NaN            1
5        Faad    NaN     89.0    NaN            2
6       Majid   89.0     88.0  177.0            3
7       Azaan   88.0     76.0  164.0            8
8      Sijjad   90.0     87.0  177.0            9
9       Masab   87.0     84.0  171.0           10
10  Hanzallah   85.0     92.0  177.0           11
11      Zafar    NaN     78.0    NaN           12

###Renaming Multiple Columns

In [123]:
df5.rename(columns={"New": "New_Addtion", "Total": "Sub_Total"},inplace=True)
print(df5)

         Name  Maths  Science  Sub_Total  New_Addtion
0    Abdullah   90.0      NaN        NaN            4
1         Ali   89.0     45.0      134.0            5
2        Maaz    NaN     78.0        NaN            6
3        Asif   89.0     90.0      179.0            7
4        Saad   90.0      NaN        NaN            1
5        Faad    NaN     89.0        NaN            2
6       Majid   89.0     88.0      177.0            3
7       Azaan   88.0     76.0      164.0            8
8      Sijjad   90.0     87.0      177.0            9
9       Masab   87.0     84.0      171.0           10
10  Hanzallah   85.0     92.0      177.0           11
11      Zafar    NaN     78.0        NaN           12

#5. Indexing

In [130]:
df5.index = ['a','b','c','d','e','f','g','h','i','j','k','l']

In [131]:
print(df5)

        Name  Maths  Science  Sub_Total  New_Addtion
a   Abdullah   90.0      NaN        NaN            4
b        Ali   89.0     45.0      134.0            5
c       Maaz    NaN     78.0        NaN            6
d       Asif   89.0     90.0      179.0            7
e       Saad   90.0      NaN        NaN            1
f       Faad    NaN     89.0        NaN            2
g      Majid   89.0     88.0      177.0            3
h      Azaan   88.0     76.0      164.0            8
i     Sijjad   90.0     87.0      177.0            9
j      Masab   87.0     84.0      171.0           10
k  Hanzallah   85.0     92.0      177.0           11
l      Zafar    NaN     78.0        NaN           12

###If you want to change the names of all the columns

In [135]:
df5.columns = ["Naame", "Mas","sd", "sdd","df"]
print(df5)

       Naame   Mas    sd    sdd  df
a   Abdullah  90.0   NaN    NaN   4
b        Ali  89.0  45.0  134.0   5
c       Maaz   NaN  78.0    NaN   6
d       Asif  89.0  90.0  179.0   7
e       Saad  90.0   NaN    NaN   1
f       Faad   NaN  89.0    NaN   2
g      Majid  89.0  88.0  177.0   3
h      Azaan  88.0  76.0  164.0   8
i     Sijjad  90.0  87.0  177.0   9
j      Masab  87.0  84.0  171.0  10
k  Hanzallah  85.0  92.0  177.0  11
l      Zafar   NaN  78.0    NaN  12

###Neve Forget Inplace = True when Renaming Column

In [139]:
df5.rename(columns={"Naame": "Name", "Mas":"Maths", "sd":"Science","sdd":"New_Total", "df":"Test_Column"},inplace=True)
print(df5)

        Name  Maths  Science  New_Total  Test_Column
a   Abdullah   90.0      NaN        NaN            4
b        Ali   89.0     45.0      134.0            5
c       Maaz    NaN     78.0        NaN            6
d       Asif   89.0     90.0      179.0            7
e       Saad   90.0      NaN        NaN            1
f       Faad    NaN     89.0        NaN            2
g      Majid   89.0     88.0      177.0            3
h      Azaan   88.0     76.0      164.0            8
i     Sijjad   90.0     87.0      177.0            9
j      Masab   87.0     84.0      171.0           10
k  Hanzallah   85.0     92.0      177.0           11
l      Zafar    NaN     78.0        NaN           12

#D. Understanding Data Types

Pandas uses NumPy data types: int64, float64, object (string), bool, datetime64.

Knowing data types is critical for:

**Vectorized operations**

**Aggregation**

**Conversions for ML models**

In [142]:
print(df5)

        Name  Maths  Science  New_Total  Test_Column
a   Abdullah   90.0      NaN        NaN            4
b        Ali   89.0     45.0      134.0            5
c       Maaz    NaN     78.0        NaN            6
d       Asif   89.0     90.0      179.0            7
e       Saad   90.0      NaN        NaN            1
f       Faad    NaN     89.0        NaN            2
g      Majid   89.0     88.0      177.0            3
h      Azaan   88.0     76.0      164.0            8
i     Sijjad   90.0     87.0      177.0            9
j      Masab   87.0     84.0      171.0           10
k  Hanzallah   85.0     92.0      177.0           11
l      Zafar    NaN     78.0        NaN           12

In [144]:
print(df5.dtypes)

Name            object
Maths          float64
Science        float64
New_Total      float64
Test_Column      int64
dtype: object

##Convert Column Type

In [145]:
df5['Test_Column'] = df5["Test_Column"].astype(float)
print(df5.dtypes)

Name            object
Maths          float64
Science        float64
New_Total      float64
Test_Column    float64
dtype: object

#E. Viewing Data in DataFrames

In [150]:
df5.head(7)

       Name  Maths  Science  New_Total  Test_Column
a  Abdullah   90.0      NaN        NaN          4.0
b       Ali   89.0     45.0      134.0          5.0
c      Maaz    NaN     78.0        NaN          6.0
d      Asif   89.0     90.0      179.0          7.0
e      Saad   90.0      NaN        NaN          1.0
f      Faad    NaN     89.0        NaN          2.0
g     Majid   89.0     88.0      177.0          3.0

In [152]:
df5.tail(3)

        Name  Maths  Science  New_Total  Test_Column
j      Masab   87.0     84.0      171.0         10.0
k  Hanzallah   85.0     92.0      177.0         11.0
l      Zafar    NaN     78.0        NaN         12.0

##Always start analysis of a new dataset with:

**df.head()**

**df.info()**

**df.describe()**

**df.shape**

**df.dtypes**

This gives a complete understanding of the dataset in seconds.