#2. Pandas Data Selection and Indexing
In this notebook, we explore data selection and indexing in Pandas, which are essential skills for extracting and filtering specific information from a dataset.

The following key concepts are covered:

**Selecting Columns** – Accessing one or multiple columns from a DataFrame using bracket notation.

**Selecting Rows** – Retrieving rows using index labels or positions.

**loc Indexer** – Label-based selection used to access rows and columns by their names or labels.

**iloc Indexer** – Position-based selection used to access rows and columns by integer index.

**Slicing Data** – Selecting ranges of rows or columns using slicing syntax.

**Boolean Filtering** – Filtering rows based on logical conditions (e.g., salary greater than a certain value).

**Conditional Filtering** – Combining multiple conditions using logical operators such as & (AND) and | (OR).

**Querying Data** – Using the query() method to filter data using readable conditional expressions.

In [1]:
import pandas as pd

#Practice Questions
###1. Select only Name and Salary columns

In [2]:
data = {
    "Name": ["Ali", "Amir", "Sara", "Hina", "Fahad"],
    "Age": [23, 25, 22, 24, 26],
    "Department": ["IT", "Finance", "IT", "HR", "Finance"],
    "Salary": [70000, 80000, 65000, 60000, 90000]
}
df = pd.DataFrame(data)
df

    Name  Age Department  Salary
0    Ali   23         IT   70000
1   Amir   25    Finance   80000
2   Sara   22         IT   65000
3   Hina   24         HR   60000
4  Fahad   26    Finance   90000

In [3]:
df[['Name','Salary']]

    Name  Salary
0    Ali   70000
1   Amir   80000
2   Sara   65000
3   Hina   60000
4  Fahad   90000

###2. Select rows 1 to 3 using loc

In [4]:
df.loc[1:3]

   Name  Age Department  Salary
1  Amir   25    Finance   80000
2  Sara   22         IT   65000
3  Hina   24         HR   60000

###3. Select rows 1 to 3 using iloc

In [5]:
df.iloc[1:4]

   Name  Age Department  Salary
1  Amir   25    Finance   80000
2  Sara   22         IT   65000
3  Hina   24         HR   60000

###4. Find employees with:
###Salary > 70000

In [6]:
df[df['Salary']>70000]

    Name  Age Department  Salary
1   Amir   25    Finance   80000
4  Fahad   26    Finance   90000

###5. Find employees who work in:
###IT department

In [7]:
df.query("Department == 'IT'")

   Name  Age Department  Salary
0   Ali   23         IT   70000
2  Sara   22         IT   65000

###6. Find employees with:
###Age > 23 AND Salary > 65000

In [8]:
df[(df["Age"]>23) & (df['Salary']> 65000)]

    Name  Age Department  Salary
1   Amir   25    Finance   80000
4  Fahad   26    Finance   90000

###7. Find employees with:
###Age > 23 AND Salary > 65000 using Query

In [9]:
df.query("Age > 23 and Salary > 65000")

    Name  Age Department  Salary
1   Amir   25    Finance   80000
4  Fahad   26    Finance   90000

###8. Select Name and Salary of employees where:

###Salary > 70000

In [10]:
df.loc[df['Salary']> 70000, ['Name', 'Salary']]

    Name  Salary
1   Amir   80000
4  Fahad   90000

#Questions related to Loc and iloc

In [11]:
data = {
    "Name": ["Ali", "Amir", "Sara", "Hina", "Fahad"],
    "Age": [23, 25, 22, 24, 26],
    "Department": ["IT", "Finance", "IT", "HR", "Finance"],
    "Salary": [70000, 80000, 65000, 60000, 90000]
}

df = pd.DataFrame(data)
df

    Name  Age Department  Salary
0    Ali   23         IT   70000
1   Amir   25    Finance   80000
2   Sara   22         IT   65000
3   Hina   24         HR   60000
4  Fahad   26    Finance   90000

###1. Write a single line of code using loc to return:

Name	Salary

Amir	80000

Hina	60000

In [12]:
rows = [1,3]
columns = ['Name', 'Salary']
df.loc[rows, columns]

   Name  Salary
1  Amir   80000
3  Hina   60000

###2. Use iloc to select:

Age	Department

23	IT

25	Finance

22	IT

In [13]:
df.iloc[0:3,1:3]

   Age Department
0   23         IT
1   25    Finance
2   22         IT

###3. Select Name and Salary of employees whose:

Department = Finance

but you must use loc.

In [14]:
df.loc[df['Department']== 'Finance', ['Name','Salary']]

    Name  Salary
1   Amir   80000
4  Fahad   90000

###4. Use iloc to select only the last row of the dataset.

Expected output:

Name	Age	Department	Salary

Fahad	26	Finance	90000

In [15]:
df.iloc[-1]

Name            Fahad
Age                26
Department    Finance
Salary          90000
Name: 4, dtype: object

###5. Write one line that returns:

Name	Department

Ali	IT

Sara	IT

Use loc.

In [16]:
df.loc[df['Department'] == 'IT', ['Name', 'Department']]

   Name Department
0   Ali         IT
2  Sara         IT

###6. Select rows 1 and 4 and columns Name and Salary using iloc only.

Expected output:

Name	Salary

Amir	80000

Fahad	90000

In [17]:
df.iloc[[1,4],[0,3]]

    Name  Salary
1   Amir   80000
4  Fahad   90000

###7. Write a line of code that returns all employees except the first one using iloc.

Expected output:

Name	Age	Department	Salary

Amir	25	Finance	80000

Sara	22	IT	65000

Hina	24	HR	60000

Fahad	26	Finance	90000

In [18]:
df.iloc[1:]

    Name  Age Department  Salary
1   Amir   25    Finance   80000
2   Sara   22         IT   65000
3   Hina   24         HR   60000
4  Fahad   26    Finance   90000

###8. Using loc, change the Salary of employees in the IT department to 75000.

In [19]:
df.loc[df['Department']=='IT', 'Salary'] = 75000

In [20]:
df

    Name  Age Department  Salary
0    Ali   23         IT   75000
1   Amir   25    Finance   80000
2   Sara   22         IT   75000
3   Hina   24         HR   60000
4  Fahad   26    Finance   90000

###Here I changed the salaries back to original

In [21]:
df.loc[df['Name']=='Ali', 'Salary'] = 70000
df.loc[df['Name']=='Sara', 'Salary'] = 65000

###9. Select the Department column for rows 2–4 using iloc.

Expected output:

IT

HR

Finance

In [22]:
df.iloc[2:5, 2]

2         IT
3         HR
4    Finance
Name: Department, dtype: object

###10. Using one line, select:

rows where Salary > 70000

only columns Name and Department

using loc

Expected result:

Name	Department

Amir	Finance

Fahad	Finance

In [23]:
df.loc[df['Salary'] > 70000, ['Name', 'Department']]

    Name Department
1   Amir    Finance
4  Fahad    Finance