#2. Pandas Data Selection and Indexing
In this notebook, we explore data selection and indexing in Pandas, which are essential skills for extracting and filtering specific information from a dataset.

The following key concepts are covered:

**Selecting Columns** – Accessing one or multiple columns from a DataFrame using bracket notation.

**Selecting Rows** – Retrieving rows using index labels or positions.

**loc Indexer** – Label-based selection used to access rows and columns by their names or labels.

**iloc Indexer** – Position-based selection used to access rows and columns by integer index.

**Slicing Data** – Selecting ranges of rows or columns using slicing syntax.

**Boolean Filtering** – Filtering rows based on logical conditions (e.g., salary greater than a certain value).

**Conditional Filtering** – Combining multiple conditions using logical operators such as & (AND) and | (OR).

**Querying Data** – Using the query() method to filter data using readable conditional expressions.

In [98]:
import pandas as pd

In [99]:
data = {
    "Name": ["Ali", "Amir", "Sara", "Hina", "Fahad"],
    "Age": [23, 25, 22, 24, 26],
    "Department": ["IT", "Finance", "IT", "HR", "Finance"],
    "Salary": [70000, 80000, 65000, 60000, 90000]
}
df = pd.DataFrame(data)
df

    Name  Age Department  Salary
0    Ali   23         IT   70000
1   Amir   25    Finance   80000
2   Sara   22         IT   65000
3   Hina   24         HR   60000
4  Fahad   26    Finance   90000

#A. Selecting Columns

Columns are usually selected first during analysis.
###Single bracket → Series
###Double brackets → DataFrame

###Selecting One Column
This return a Series

In [100]:
df['Department']

0         IT
1    Finance
2         IT
3         HR
4    Finance
Name: Department, dtype: object

###Selecting Multiple Columns
This returns a DataFrame

In [101]:
df[['Department', 'Name']]

  Department   Name
0         IT    Ali
1    Finance   Amir
2         IT   Sara
3         HR   Hina
4    Finance  Fahad

#B. Selecting Rows
Rows can be selected using index numbers.

Example:

0

1

2

3

4

#C. loc vs iloc
###loc → label based

###iloc → position based

#Using Loc
loc selects using row labels and column names.

In [102]:
df

    Name  Age Department  Salary
0    Ali   23         IT   70000
1   Amir   25    Finance   80000
2   Sara   22         IT   65000
3   Hina   24         HR   60000
4  Fahad   26    Finance   90000

In [103]:
test_data = {
    "Name": ["Ali", "Amir", "Sara", "Hina", "Fahad"],
    "Age": [23, 25, 22, 24, 26],
    "Department": ["IT", "Finance", "IT", "HR", "Finance"],
    "Salary": [70000, 80000, 65000, 60000, 90000]
}
df1 = pd.DataFrame(data, index = ['a','b','c','d','e'])
df1.loc['a', 'Name']

'Ali'

###This selects row with label 1

In [104]:
df.loc[1]

Name             Amir
Age                25
Department    Finance
Salary          80000
Name: 1, dtype: object

###Selecting Row and Specific Column

In [105]:
df.loc[2, "Name"]
#Or
print(df.loc[2]["Name"])

Sara

###Selecting Multiple Columns with Loc

In [106]:
df.loc[2, ['Name', 'Department']]

Name          Sara
Department      IT
Name: 2, dtype: object

###Selecting Multiple Rows with loc

In [107]:
df.loc[1:3]

   Name  Age Department  Salary
1  Amir   25    Finance   80000
2  Sara   22         IT   65000
3  Hina   24         HR   60000

###Selecting Multiple Rows and Multiple Columns using Loc

In [108]:
df.loc[1:3, ['Name', 'Salary']]

   Name  Salary
1  Amir   80000
2  Sara   65000
3  Hina   60000

#Using iloc
###iloc selects using numerical positions.

In [109]:
df.iloc[2]

Name           Sara
Age              22
Department       IT
Salary        65000
Name: 2, dtype: object

###Selecting Row and Column with iloc

In [110]:
df.iloc[2,0]

'Sara'

###Selecting Multiple Columns with iloc
###iloc slicing is NOT inclusive
###0:2 excludes 2

In [111]:
df.iloc[0:2,0:3]

   Name  Age Department
0   Ali   23         IT
1  Amir   25    Finance

##loc → labels
##iloc → numbers

###df1.loc['c',"Name"]
###df1.iloc[2,0]
Both return Sara

In [112]:
df1

    Name  Age Department  Salary
a    Ali   23         IT   70000
b   Amir   25    Finance   80000
c   Sara   22         IT   65000
d   Hina   24         HR   60000
e  Fahad   26    Finance   90000

In [113]:
df1.loc['c', 'Name']

'Sara'

In [114]:
df1.iloc[2,0]

'Sara'

In [115]:
df1.loc['a':'c', ['Name', 'Department']]

   Name Department
a   Ali         IT
b  Amir    Finance
c  Sara         IT

In [116]:
df1.iloc[0:3,0:2]

   Name  Age
a   Ali   23
b  Amir   25
c  Sara   22

#D. Boolean Filtering
It selects rows based on conditions.

In [117]:
df['Salary']>70000

0    False
1     True
2    False
3    False
4     True
Name: Salary, dtype: bool

##Filtering Data

In [118]:
df[df['Salary']>70000]

    Name  Age Department  Salary
1   Amir   25    Finance   80000
4  Fahad   26    Finance   90000

##Multiple Conditions

In [119]:
df[(df['Salary']>65000) & (df['Salary']<=80000)]

   Name  Age Department  Salary
0   Ali   23         IT   70000
1  Amir   25    Finance   80000

##And Condition

In [120]:
df[(df['Salary']>70000) & (df['Department'] == 'Finance')]

    Name  Age Department  Salary
1   Amir   25    Finance   80000
4  Fahad   26    Finance   90000

##OR Condition

In [121]:
df[(df['Salary']<70000) | (df['Department'] == 'IT')]

   Name  Age Department  Salary
0   Ali   23         IT   70000
2  Sara   22         IT   65000
3  Hina   24         HR   60000

#E. Conditional Filtering
###We can combine conditions.

In [122]:
df

    Name  Age Department  Salary
0    Ali   23         IT   70000
1   Amir   25    Finance   80000
2   Sara   22         IT   65000
3   Hina   24         HR   60000
4  Fahad   26    Finance   90000

In [123]:
df[(df['Age']>24) & (df['Salary']>70000)]

    Name  Age Department  Salary
1   Amir   25    Finance   80000
4  Fahad   26    Finance   90000

#Querying Data with Query
###Another powerful filtering method.

In [124]:
df.query("Salary>70000")

    Name  Age Department  Salary
1   Amir   25    Finance   80000
4  Fahad   26    Finance   90000

##Multiple conditions with query

In [125]:
df.query("Age > 24 and Salary > 70000")

    Name  Age Department  Salary
1   Amir   25    Finance   80000
4  Fahad   26    Finance   90000

In [126]:
df[(df["Age"]>24)&(df["Salary"]>70000)]

    Name  Age Department  Salary
1   Amir   25    Finance   80000
4  Fahad   26    Finance   90000

###Both Boolean and Query Does the same job, as we can see in above two queries
###Query is best for readability

#Problem
###Find IT employees with salary > 65000.

###Boolean Method

In [127]:
df[(df["Department"]=="IT") & (df["Salary"]>65000)]

  Name  Age Department  Salary
0  Ali   23         IT   70000

###Query Method

In [128]:
df.query("Department == 'IT' and Salary > 65000")

  Name  Age Department  Salary
0  Ali   23         IT   70000

#Some Professional Tricks
##Trick 1 — Selecting Rows & Columns Dynamically (Using lists with loc)

In [129]:
df

    Name  Age Department  Salary
0    Ali   23         IT   70000
1   Amir   25    Finance   80000
2   Sara   22         IT   65000
3   Hina   24         HR   60000
4  Fahad   26    Finance   90000

###Suppose you want to select only specific rows

In [130]:
rows = [0,3,4]
columns = ['Name', 'Department']
df.loc[rows,columns]

    Name Department
0    Ali         IT
3   Hina         HR
4  Fahad    Finance

##Trick 2 — Conditional Row & Column Selection with loc

###You can combine Boolean filtering and column selection in one step, saving multiple lines of code.

###Example:

Get Name and Salary for employees with Salary > 70000:

Instead of writing two steps (filter + select columns), you do it in one line.

In [131]:
df.loc[df["Salary"]>70000, ["Name", "Salary"]]

    Name  Salary
1   Amir   80000
4  Fahad   90000

##Trick 3 — Selecting Rows & Columns by Position + Slicing

In [132]:
df.iloc[[0,2],[0,3]]

   Name  Salary
0   Ali   70000
2  Sara   65000

###Selecting all rows but only last two columns

In [133]:
df.iloc[:,-2:]

  Department  Salary
0         IT   70000
1    Finance   80000
2         IT   65000
3         HR   60000
4    Finance   90000

###You can combine lists, slices, and Boolean masks in both

In [92]:
df.loc[df["Salary"]>7000, 'Department'] = 'Management'

In [93]:
df

    Name  Age  Department  Salary
0    Ali   23  Management   70000
1   Amir   25  Management   80000
2   Sara   22  Management   65000
3   Hina   24  Management   60000
4  Fahad   26  Management   90000

#Practice Questions
###1. Select only Name and Salary columns

In [134]:
df[['Name','Salary']]

    Name  Salary
0    Ali   70000
1   Amir   80000
2   Sara   65000
3   Hina   60000
4  Fahad   90000

###2. Select rows 1 to 3 using loc

In [135]:
df.loc[1:3]

   Name  Age Department  Salary
1  Amir   25    Finance   80000
2  Sara   22         IT   65000
3  Hina   24         HR   60000

###3. Select rows 1 to 3 using iloc

In [136]:
df.iloc[1:4]

   Name  Age Department  Salary
1  Amir   25    Finance   80000
2  Sara   22         IT   65000
3  Hina   24         HR   60000

###4. Find employees with:
###Salary > 70000

In [137]:
df[df['Salary']>70000]

    Name  Age Department  Salary
1   Amir   25    Finance   80000
4  Fahad   26    Finance   90000

###5. Find employees who work in:
###IT department

In [138]:
df.query("Department == 'IT'")

   Name  Age Department  Salary
0   Ali   23         IT   70000
2  Sara   22         IT   65000

###6. Find employees with:
###Age > 23 AND Salary > 65000

In [139]:
df[(df["Age"]>23) & (df['Salary']> 65000)]

    Name  Age Department  Salary
1   Amir   25    Finance   80000
4  Fahad   26    Finance   90000

###7. Find employees with:
###Age > 23 AND Salary > 65000 using Query

In [140]:
df.query("Age > 23 and Salary > 65000")

    Name  Age Department  Salary
1   Amir   25    Finance   80000
4  Fahad   26    Finance   90000

###8. Select Name and Salary of employees where:

###Salary > 70000

In [141]:
df.loc[df['Salary']> 70000, ['Name', 'Salary']]

    Name  Salary
1   Amir   80000
4  Fahad   90000

#Questions related to Loc and iloc

In [142]:
data = {
    "Name": ["Ali", "Amir", "Sara", "Hina", "Fahad"],
    "Age": [23, 25, 22, 24, 26],
    "Department": ["IT", "Finance", "IT", "HR", "Finance"],
    "Salary": [70000, 80000, 65000, 60000, 90000]
}

df = pd.DataFrame(data)
df

    Name  Age Department  Salary
0    Ali   23         IT   70000
1   Amir   25    Finance   80000
2   Sara   22         IT   65000
3   Hina   24         HR   60000
4  Fahad   26    Finance   90000

###1. Write a single line of code using loc to return:

Name	Salary

Amir	80000

Hina	60000

In [190]:
rows = [1,3]
columns = ['Name', 'Salary']
df.loc[rows, columns]

   Name  Salary
1  Amir   80000
3  Hina   60000

###2. Use iloc to select:

Age	Department

23	IT

25	Finance

22	IT

In [148]:
df.iloc[0:3,1:3]

   Age Department
0   23         IT
1   25    Finance
2   22         IT

###3. Select Name and Salary of employees whose:

Department = Finance

but you must use loc.

In [149]:
df.loc[df['Department']== 'Finance', ['Name','Salary']]

    Name  Salary
1   Amir   80000
4  Fahad   90000

###4. Use iloc to select only the last row of the dataset.

Expected output:

Name	Age	Department	Salary

Fahad	26	Finance	90000

In [151]:
df.iloc[-1]

Name            Fahad
Age                26
Department    Finance
Salary          90000
Name: 4, dtype: object

###5. Write one line that returns:

Name	Department

Ali	IT

Sara	IT

Use loc.

In [158]:
df.loc[df['Department'] == 'IT', ['Name', 'Department']]

   Name Department
0   Ali         IT
2  Sara         IT

###6. Select rows 1 and 4 and columns Name and Salary using iloc only.

Expected output:

Name	Salary

Amir	80000

Fahad	90000

In [198]:
df.iloc[[1,4],[0,3]]

    Name  Salary
1   Amir   80000
4  Fahad   90000

###7. Write a line of code that returns all employees except the first one using iloc.

Expected output:

Name	Age	Department	Salary

Amir	25	Finance	80000

Sara	22	IT	65000

Hina	24	HR	60000

Fahad	26	Finance	90000

In [179]:
df.iloc[1:]

    Name  Age Department  Salary
1   Amir   25    Finance   80000
2   Sara   22         IT   65000
3   Hina   24         HR   60000
4  Fahad   26    Finance   90000

###8. Using loc, change the Salary of employees in the IT department to 75000.

In [181]:
df.loc[df['Department']=='IT', 'Salary'] = 75000

In [186]:
df

    Name  Age Department  Salary
0    Ali   23         IT   75000
1   Amir   25    Finance   80000
2   Sara   22         IT   75000
3   Hina   24         HR   60000
4  Fahad   26    Finance   90000

###Here I changed the salaries back to original

In [187]:
df.loc[df['Name']=='Ali', 'Salary'] = 70000
df.loc[df['Name']=='Sara', 'Salary'] = 65000

###9. Select the Department column for rows 2–4 using iloc.

Expected output:

IT

HR

Finance

In [188]:
df.iloc[2:5, 2]

2         IT
3         HR
4    Finance
Name: Department, dtype: object

###10. Using one line, select:

rows where Salary > 70000

only columns Name and Department

using loc

Expected result:

Name	Department

Amir	Finance

Fahad	Finance

In [189]:
df.loc[df['Salary'] > 70000, ['Name', 'Department']]

    Name Department
1   Amir    Finance
4  Fahad    Finance