#3. Pandas Data Cleaning 1 Practice

In [54]:
import pandas as pd
import numpy as np

In [55]:
data = {
    "Name": ["Ali", "Sara", "Ali", "Hina", "Omar", "Sara"],
    "Age": [23, np.nan, 23, 25, np.nan, 28],
    "Salary": [50000, 60000, 50000, np.nan, 70000, 60000],
    "Department": ["IT", "HR", "IT", "Finance", "IT", "HR"]
}
df = pd.DataFrame(data)
df

   Name   Age   Salary Department
0   Ali  23.0  50000.0         IT
1  Sara   NaN  60000.0         HR
2   Ali  23.0  50000.0         IT
3  Hina  25.0      NaN    Finance
4  Omar   NaN  70000.0         IT
5  Sara  28.0  60000.0         HR

##PART 1 — Missing Data
###Question 1 (Concept Test)

###Write a command that shows which cells in the dataset contain missing values.

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        6 non-null      object
 1   Age         4 non-null      float64
 2   Salary      5 non-null      float64
 3   Department  6 non-null      object
dtypes: float64(2), object(2)
memory usage: 324.0+ bytes

In [57]:
df.isna()

    Name    Age  Salary  Department
0  False  False   False       False
1  False   True   False       False
2  False  False   False       False
3  False  False    True       False
4  False   True   False       False
5  False  False   False       False

##Question 2 (Counting Missing Data)

###Find how many missing values exist in each column.

###Expected type of result:

**Age       ?**

**Salary    ?**

In [58]:
df[['Age','Salary']].isna().sum()

Age       2
Salary    1
dtype: int64

##Question 3

###Write a command that removes rows where Age is missing, but keeps rows where Salary is missing.

In [59]:
df.dropna(subset=['Age'])

   Name   Age   Salary Department
0   Ali  23.0  50000.0         IT
2   Ali  23.0  50000.0         IT
3  Hina  25.0      NaN    Finance
5  Sara  28.0  60000.0         HR

##Question 4 (Logic Test)

###Remove rows only if both Age and Salary are missing.

In [60]:
df.dropna(subset=['Age','Salary'],how='all')

   Name   Age   Salary Department
0   Ali  23.0  50000.0         IT
1  Sara   NaN  60000.0         HR
2   Ali  23.0  50000.0         IT
3  Hina  25.0      NaN    Finance
4  Omar   NaN  70000.0         IT
5  Sara  28.0  60000.0         HR

##Question 5 (Data Imputation)

###Replace missing values in Age with the average age.

In [61]:
df['Age'].fillna(df['Age'].mean())

0    23.00
1    24.75
2    23.00
3    25.00
4    24.75
5    28.00
Name: Age, dtype: float64

##Question 6 (Selective Fill)

###Replace missing Salary with 50000.

In [62]:
df['Salary'].fillna(50000)

0    50000.0
1    60000.0
2    50000.0
3    50000.0
4    70000.0
5    60000.0
Name: Salary, dtype: float64

##PART 2 — Duplicates
###Question 7 (Detect Duplicates)

###Write a command that identifies duplicate rows.

In [63]:
df.duplicated()

0    False
1    False
2     True
3    False
4    False
5    False
dtype: bool

##Question 8 (Remove Duplicates)

###Write a command that removes duplicate rows and keeps only unique rows.

In [64]:
df.drop_duplicates()

   Name   Age   Salary Department
0   Ali  23.0  50000.0         IT
1  Sara   NaN  60000.0         HR
3  Hina  25.0      NaN    Finance
4  Omar   NaN  70000.0         IT
5  Sara  28.0  60000.0         HR

##Question 9 (Advanced Duplicate Logic)

###Remove duplicates based only on Name, keeping the first occurrence.

In [65]:
df.drop_duplicates(subset=['Name'],keep='first')# you can use keep = 'last' or False

   Name   Age   Salary Department
0   Ali  23.0  50000.0         IT
1  Sara   NaN  60000.0         HR
3  Hina  25.0      NaN    Finance
4  Omar   NaN  70000.0         IT

##Question 10 (Professional Trick)

###Remove duplicates based on Name and Department together.

In [66]:
df.drop_duplicates(subset=['Name','Department'])

   Name   Age   Salary Department
0   Ali  23.0  50000.0         IT
1  Sara   NaN  60000.0         HR
3  Hina  25.0      NaN    Finance
4  Omar   NaN  70000.0         IT

##PART 3 — Data Types
###Currently Age and Salary are strings.

In [67]:
data2 = {
    "Name": ["Ali", "Sara", "Hina"],
    "Age": ["23", "25", "27"],
    "Salary": ["50000", "60000", "70000"]
}
df2 = pd.DataFrame(data2)
df2

   Name Age Salary
0   Ali  23  50000
1  Sara  25  60000
2  Hina  27  70000

##Question 11

###Check the data types of all columns.

In [68]:
df.dtypes

Name           object
Age           float64
Salary        float64
Department     object
dtype: object

##Question 12

###Convert Age column to integer using astype().

In [69]:
df['Age'] = df['Age'].fillna(0)
df['Age'].astype(int)

0    23
1     0
2    23
3    25
4     0
5    28
Name: Age, dtype: int64

##Question 13

###Convert both Age and Salary to float in one command.

In [70]:
df[['Age','Salary']].astype(float)

    Age   Salary
0  23.0  50000.0
1   0.0  60000.0
2  23.0  50000.0
3  25.0      NaN
4   0.0  70000.0
5  28.0  60000.0