#3. Pandas Data Cleaning

**Data Cleaning** is the process of fixing these issues so the data becomes reliable for analysis and machine learning.

In this lesson we will cover:

**Handling Missing Data**

**Removing or Identifying Duplicates**

**Fixing Data Types**

#1. Missing Data
What is Missing Data?

Missing data occurs when values are absent from a dataset.

In Pandas, missing values are usually represented as:

**NaN**

In [68]:
import pandas as pd
import numpy as np

In [69]:
data = {
    "Name": ["Ali", "Sara", "Amir", "Hina","Ali","Sara"],
    "Age": [23, np.nan, 25, 24,23,22],
    "Salary": [70000, 65000, np.nan, 60000,70000,65000]
}
df = pd.DataFrame(data)
df

   Name   Age   Salary
0   Ali  23.0  70000.0
1  Sara   NaN  65000.0
2  Amir  25.0      NaN
3  Hina  24.0  60000.0
4   Ali  23.0  70000.0
5  Sara  22.0  65000.0

Here:

###Sara’s **Age** is missing

###Amir’s **Salary** is missing

##1.1 Detecting Missing Values
###The **isna()** function identifies missing values.

In [70]:
df.isna()

    Name    Age  Salary
0  False  False   False
1  False   True   False
2  False  False    True
3  False  False   False
4  False  False   False
5  False  False   False

**True** = Missing value

**False** = Value exists

##Counting Missing Values

Often we want to know how many missing values exist in each column.

In [71]:
df.isna().sum()

Name      0
Age       1
Salary    1
dtype: int64

###Age column has 1 missing value

###Salary column has 1 missing value

##1.2 Detecting Non-Missing Values — notna()

**notna()** is the opposite of **isna()**.

It returns **True for existing values** and **False for missing values.**

In [72]:
df.notna()

   Name    Age  Salary
0  True   True    True
1  True  False    True
2  True   True   False
3  True   True    True
4  True   True    True
5  True   True    True

##1.3 Removing Missing Values — dropna()

###**dropna()** removes rows or columns containing missing values.

In [73]:
df.dropna()

   Name   Age   Salary
0   Ali  23.0  70000.0
3  Hina  24.0  60000.0
4   Ali  23.0  70000.0
5  Sara  22.0  65000.0

In [74]:
df

   Name   Age   Salary
0   Ali  23.0  70000.0
1  Sara   NaN  65000.0
2  Amir  25.0      NaN
3  Hina  24.0  60000.0
4   Ali  23.0  70000.0
5  Sara  22.0  65000.0

##Dropping Columns with Missing Values

###If a column contains NaN, it will be removed.

axis = 1 → columns

axis = 0 → rows

In [75]:
df.dropna(axis=1)

   Name
0   Ali
1  Sara
2  Amir
3  Hina
4   Ali
5  Sara

##Dropping Rows Only if ALL Values Are Missing

In [76]:
df.dropna(how='all')

   Name   Age   Salary
0   Ali  23.0  70000.0
1  Sara   NaN  65000.0
2  Amir  25.0      NaN
3  Hina  24.0  60000.0
4   Ali  23.0  70000.0
5  Sara  22.0  65000.0

###Dropping Rows Based on Specific Columns

In [77]:
df.dropna(subset=['Salary','Age'])

   Name   Age   Salary
0   Ali  23.0  70000.0
3  Hina  24.0  60000.0
4   Ali  23.0  70000.0
5  Sara  22.0  65000.0

In [78]:
df

   Name   Age   Salary
0   Ali  23.0  70000.0
1  Sara   NaN  65000.0
2  Amir  25.0      NaN
3  Hina  24.0  60000.0
4   Ali  23.0  70000.0
5  Sara  22.0  65000.0

##1.4 Filling Missing Values — fillna()

All missing values become **0**.

In [79]:
df.fillna(0)

   Name   Age   Salary
0   Ali  23.0  70000.0
1  Sara   0.0  65000.0
2  Amir  25.0      0.0
3  Hina  24.0  60000.0
4   Ali  23.0  70000.0
5  Sara  22.0  65000.0

##Fill with Specific Value

In [80]:
df['Salary'].fillna(80000)

0    70000.0
1    65000.0
2    80000.0
3    60000.0
4    70000.0
5    65000.0
Name: Salary, dtype: float64

In [81]:
mean = np.mean(df['Salary'])
mean

np.float64(66000.0)

##Fill with Mean Value
This replaces missing values with the **average.**

In [82]:
df['Salary'].fillna(mean)
#OR
df['Salary'].fillna(df['Salary'].mean())

0    70000.0
1    65000.0
2    66000.0
3    60000.0
4    70000.0
5    65000.0
Name: Salary, dtype: float64

##Forward Fill Method
fill missing value using the previous row's value

In [83]:
df.fillna(method='ffill')

/tmp/ipykernel_2127/1193302488.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill')

   Name   Age   Salary
0   Ali  23.0  70000.0
1  Sara  23.0  65000.0
2  Amir  25.0  65000.0
3  Hina  24.0  60000.0
4   Ali  23.0  70000.0
5  Sara  22.0  65000.0

In [84]:
df['Salary'].fillna(method='ffill')

/tmp/ipykernel_2127/2287196102.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Salary'].fillna(method='ffill')

0    70000.0
1    65000.0
2    65000.0
3    60000.0
4    70000.0
5    65000.0
Name: Salary, dtype: float64

##Backward Fill Method
Fill missing value using next row's value

In [85]:
df['Age'].fillna(method='bfill')

/tmp/ipykernel_2127/3224957626.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Age'].fillna(method='bfill')

0    23.0
1    25.0
2    25.0
3    24.0
4    23.0
5    22.0
Name: Age, dtype: float64

In [86]:
df.fillna(method='bfill')

/tmp/ipykernel_2127/2831856154.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='bfill')

   Name   Age   Salary
0   Ali  23.0  70000.0
1  Sara  25.0  65000.0
2  Amir  25.0  60000.0
3  Hina  24.0  60000.0
4   Ali  23.0  70000.0
5  Sara  22.0  65000.0

#2. Duplicate Data

###Sometimes datasets contain repeated rows.

Example:

Name	  Age

Ali	    23

Sara	  24

Ali	    23

The third row is a duplicate.

##Detecting Duplicates
###duplicated()

True mean the row is duplicated

In [89]:
df.duplicated()

0    False
1    False
2    False
3    False
4     True
5    False
dtype: bool

##Removing Duplicates
###drop_duplicates()
Duplicate rows will be removed.

In [92]:
df.drop_duplicates()

   Name   Age   Salary
0   Ali  23.0  70000.0
1  Sara   NaN  65000.0
2  Amir  25.0      NaN
3  Hina  24.0  60000.0
5  Sara  22.0  65000.0

##Removing Duplicates Based on Specific Column
This removes duplicate Salaries.

In [96]:
df.drop_duplicates(subset=['Salary'])

   Name   Age   Salary
0   Ali  23.0  70000.0
1  Sara   NaN  65000.0
2  Amir  25.0      NaN
3  Hina  24.0  60000.0

#3. Data Types
Every column has a data type.

Example:

Column	Type

Age	int

Salary	float

Name	object (string)

###Check Data types:

In [97]:
df.dtypes

Name       object
Age       float64
Salary    float64
dtype: object

##Changing Data Type
###astype()

In [102]:
df['Age'] = df['Age'].astype('float32')
df.dtypes

Name       object
Age       float32
Salary    float64
dtype: object