#Pandas Data Cleaning 2 Practice

In [1]:
import pandas as pd

In [2]:
data = {
    "Name": ["Ali", "Sara", "Ali", "Hina", "Omar", "Sara"],
    "Age": ["25", "30", "25", None, "28", "30"],
    "Salary": ["50000", "60000", "50000", "55000", "not available", "60000"],
    "JoinDate": ["2023-01-15", "2023/02/20", "2023-01-15", "15-03-2023", None, "2023/02/20"],
    "Department": ["IT", "HR", "IT", "Finance", "IT", "HR"]
}
df = pd.DataFrame(data)
df

   Name   Age         Salary    JoinDate Department
0   Ali    25          50000  2023-01-15         IT
1  Sara    30          60000  2023/02/20         HR
2   Ali    25          50000  2023-01-15         IT
3  Hina  None          55000  15-03-2023    Finance
4  Omar    28  not available        None         IT
5  Sara    30          60000  2023/02/20         HR

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        6 non-null      object
 1   Age         5 non-null      object
 2   Salary      6 non-null      object
 3   JoinDate    5 non-null      object
 4   Department  6 non-null      object
dtypes: object(5)
memory usage: 372.0+ bytes

##Question 1 — Detect duplicates

###Find all rows that are duplicates considering all columns.

In [7]:
df.duplicated()

0    False
1    False
2     True
3    False
4    False
5     True
dtype: bool

##Question 2 — Detect partial duplicates

###Find duplicates based only on Name and Department.

In [8]:
df.duplicated(subset= ['Name','Department'])

0    False
1    False
2     True
3    False
4    False
5     True
dtype: bool

##Question 3 — Remove duplicates

###Remove duplicate rows based on Name and Department, keeping only the first occurrence.

In [9]:
df.drop_duplicates(subset= ['Name','Department'],keep= 'first')

   Name   Age         Salary    JoinDate Department
0   Ali    25          50000  2023-01-15         IT
1  Sara    30          60000  2023/02/20         HR
3  Hina  None          55000  15-03-2023    Finance
4  Omar    28  not available        None         IT

##Question 4 — Safe numeric conversion

###Convert the Salary column to numeric.
####Invalid values like "not available" should become NaN.

In [18]:
df['Salary']= pd.to_numeric(df['Salary'], errors= 'coerce')

##Question 5 — Convert multiple columns

###Convert Age and Salary columns to float type in one command.

In [19]:
df[['Age','Salary']].astype(float)

    Age   Salary
0  25.0  50000.0
1  30.0  60000.0
2  25.0  50000.0
3   NaN  55000.0
4  28.0      NaN
5  30.0  60000.0

##Question 6 — Datetime conversion

###Convert the JoinDate column to datetime so that all valid dates are correctly parsed and invalid ones become NaT.

In [34]:
df['JoinDate'] = df['JoinDate'].str.replace('/','-')

In [35]:
df['JoinDate']

0    2023-01-15
1    2023-02-20
2    2023-01-15
3    15-03-2023
4          None
5    2023-02-20
Name: JoinDate, dtype: object

In [36]:
pd.to_datetime(df['JoinDate'], errors= 'coerce', dayfirst= True)

/tmp/ipykernel_177/1996130562.py:1: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  pd.to_datetime(df['JoinDate'], errors= 'coerce', dayfirst= True)

0   2023-01-15
1   2023-02-20
2   2023-01-15
3          NaT
4          NaT
5   2023-02-20
Name: JoinDate, dtype: datetime64[ns]

##To change the date at index 4(15-03-2023)
###We perform the following method

In [39]:
mask = df['JoinDate'].isna()
mask

0    False
1    False
2    False
3    False
4     True
5    False
Name: JoinDate, dtype: bool

In [40]:
df.loc[mask, 'JoinDate'] = pd.to_datetime(df.loc[mask, 'JoinDate'], format= '%Y-%m-%d', errors= 'coerce')

In [41]:
df

   Name   Age   Salary    JoinDate Department
0   Ali    25  50000.0  2023-01-15         IT
1  Sara    30  60000.0  2023-02-20         HR
2   Ali    25  50000.0  2023-01-15         IT
3  Hina  None  55000.0  15-03-2023    Finance
4  Omar    28      NaN         NaT         IT
5  Sara    30  60000.0  2023-02-20         HR