#Pandas String Operations
##Overview

In real-world datasets, text data is often **messy and inconsistent**. Names may have extra spaces, inconsistent capitalization, unwanted characters, or combined fields that need to be separated.

To perform reliable analysis, this text must be **cleaned and standardized**.

In this lesson we will learn how to clean and manipulate text data in pandas using the **.str accessor**, which allows vectorized string operations on an entire column.

##Topics Covered:

**1. Introduction to String Operations in Pandas**

**2. The .str accessor**

**3. str.lower() – convert text to lowercase**

**4. str.upper() – convert text to uppercase**

**5. str.strip() – remove leading and trailing spaces**

**6. str.replace() – replace characters or patterns**

**7. str.contains() – search for patterns in text**

**8. str.split() – split strings into multiple parts**

**9. str.len()**

**10. str.startswith()**

**11. str.endswith()**

**12. str.title()**

In [60]:
import pandas as pd

data = {
    "customer_id": [101,102,103,104,105,106,107,108],

    "name": [
        "  ali khan",
        "SARA AHMED ",
        " ahMeD RAZA ",
        "Fatima Noor",
        "  usman ali ",
        "Ayesha Malik ",
        "bilal  khan",
        " HAMZA SHAH"
    ],

    "email": [
        "ali.khan@gmail.com ",
        "SARA@YAHOO.COM",
        " ahmed123@gmail.com",
        "fatima_noor@hotmail.com ",
        "usman.ali@gmail.com",
        "ayesha.malik@yahoo.com ",
        "bilal-khan@gmail.com",
        "hamza.shah@outlook.com"
    ],

    "city": [
        " new-york ",
        "LOS-ANGELES",
        " chicago ",
        "Houston",
        "phoenix ",
        " SAN-ANTONIO",
        "san-diego",
        " Dallas "
    ],

    "job_title": [
        "data analyst",
        "DATA SCIENTIST",
        "machine learning engineer",
        "software developer",
        "data engineer",
        "business analyst",
        "AI researcher",
        "data ANALYST"
    ]
}

df = pd.DataFrame(data)
df

,customer_id,name,email,city,job_title
0,101,ali khan,ali.khan@gmail.com,new-york,data analyst
1,102,SARA AHMED,SARA@YAHOO.COM,LOS-ANGELES,DATA SCIENTIST
2,103,ahMeD RAZA,ahmed123@gmail.com,chicago,machine learning engineer
3,104,Fatima Noor,fatima_noor@hotmail.com,Houston,software developer
4,105,usman ali,usman.ali@gmail.com,phoenix,data engineer
5,106,Ayesha Malik,ayesha.malik@yahoo.com,SAN-ANTONIO,business analyst
6,107,bilal khan,bilal-khan@gmail.com,san-diego,AI researcher
7,108,HAMZA SHAH,hamza.shah@outlook.com,Dallas,data ANALYST

#1. Why String Cleaning Is Important

##Real datasets often contain problems like:

###Problem	Example
####Inconsistent capitalization	**Ali, ALI, ali**
####Extra spaces	**" Ahmed "**
####Mixed formatting	**"New-York" vs "New York"**
####Combined fields	**"Ali Khan"**

If this data is not cleaned, analysis results will be incorrect or misleading.

#2. The .str Accessor

In pandas, string operations are performed using the .str accessor.

Example:

####df["name"].str.lower()


###Explanation:

####df["name"] → select the column

####.str → access string methods

####.lower() → apply lowercase conversion

In [61]:
df['name'].str.lower()

0         ali khan
1      sara ahmed
2      ahmed raza
3      fatima noor
4       usman ali
5    ayesha malik
6      bilal  khan
7       hamza shah
Name: name, dtype: object

#3. str.lower()
###Purpose

####Convert all text in a column to lowercase.

In [62]:
df['city'].str.lower()

0       new-york
1     los-angeles
2        chicago
3         houston
4        phoenix
5     san-antonio
6       san-diego
7         dallas
Name: city, dtype: object

#4. str.upper()
###Purpose

####Convert text to uppercase.

In [63]:
df['name'].str.upper()

0         ALI KHAN
1      SARA AHMED
2      AHMED RAZA
3      FATIMA NOOR
4       USMAN ALI
5    AYESHA MALIK
6      BILAL  KHAN
7       HAMZA SHAH
Name: name, dtype: object

#5. str.strip()
###Purpose

####Remove extra spaces from the beginning and end of strings.

In [64]:
df['name'].str.strip()

0        ali khan
1      SARA AHMED
2      ahMeD RAZA
3     Fatima Noor
4       usman ali
5    Ayesha Malik
6     bilal  khan
7      HAMZA SHAH
Name: name, dtype: object

##Related Methods

###Remove only left spaces:

####**str.lstrip()**


###Remove only right spaces:

####**str.rstrip()**

In [65]:
df['name'].str.lstrip()

0         ali khan
1      SARA AHMED
2      ahMeD RAZA
3      Fatima Noor
4       usman ali
5    Ayesha Malik
6      bilal  khan
7       HAMZA SHAH
Name: name, dtype: object

In [66]:
df['name'].str.rstrip()

0        ali khan
1      SARA AHMED
2      ahMeD RAZA
3     Fatima Noor
4       usman ali
5    Ayesha Malik
6     bilal  khan
7      HAMZA SHAH
Name: name, dtype: object

In [67]:
df['name'] = df['name'].str.strip()

###Can remove specific characters:

In [100]:
df['email'].str.strip("$@")

0         ali.khan@gmail.com
1              SARA@YAHOO.COM
2          ahmed123@gmail.com
3    fatima_noor@hotmail.com
4         usman.ali@gmail.com
5     ayesha.malik@yahoo.com
6        bilal-khan@gmail.com
7      hamza.shah@outlook.com
Name: email, dtype: object

#6. str.replace()
###Purpose

####Replace characters or patterns in strings.

In [68]:
df['city']

0       new-york
1     LOS-ANGELES
2        chicago
3         Houston
4        phoenix
5     SAN-ANTONIO
6       san-diego
7         Dallas
Name: city, dtype: object

In [69]:
df['city'].str.replace("-"," ")

0       new york
1     LOS ANGELES
2        chicago
3         Houston
4        phoenix
5     SAN ANTONIO
6       san diego
7         Dallas
Name: city, dtype: object

#7. str.contains()
##Purpose

####Check if a string contains a specific pattern.

####Returns True or False.

In [70]:
df['email'].str.contains('gmail')

0     True
1    False
2     True
3    False
4     True
5    False
6     True
7    False
Name: email, dtype: bool

#8. str.split()
##Purpose

####Split text into multiple parts.

In [71]:
df['name'].str.split(" ")

0        [ali, khan]
1      [SARA, AHMED]
2      [ahMeD, RAZA]
3     [Fatima, Noor]
4       [usman, ali]
5    [Ayesha, Malik]
6    [bilal, , khan]
7      [HAMZA, SHAH]
Name: name, dtype: object

###Splitting Into Columns

In [72]:
df['name'] = df['name'].str.strip()

In [73]:
df['name'] = df['name'].str.replace("  ", " ")

In [74]:
df['name'].str.split(" ",expand=True)

        0      1
0     ali   khan
1    SARA  AHMED
2   ahMeD   RAZA
3  Fatima   Noor
4   usman    ali
5  Ayesha  Malik
6   bilal   khan
7   HAMZA   SHAH

#9. str.len()

###Find the length of strings.

In [75]:
df['name'].str.len()

0     8
1    10
2    10
3    11
4     9
5    12
6    10
7    10
Name: name, dtype: int64

#10. str.startswith()

###Check if string starts with a pattern.

In [76]:
df['email'].str.startswith('ali')

0     True
1    False
2    False
3    False
4    False
5    False
6    False
7    False
Name: email, dtype: bool

#11. str.endswith()
###Check if string ends with a pattern.

In [77]:
df['email'].str.endswith('.com')

0    False
1    False
2     True
3    False
4     True
5    False
6     True
7     True
Name: email, dtype: bool

#12. str.title()

###Convert text to title case.

In [78]:
df['name'].str.title()

0        Ali Khan
1      Sara Ahmed
2      Ahmed Raza
3     Fatima Noor
4       Usman Ali
5    Ayesha Malik
6      Bilal Khan
7      Hamza Shah
Name: name, dtype: object

In [79]:
df['city'].str.title()

0       New-York
1     Los-Angeles
2        Chicago
3         Houston
4        Phoenix
5     San-Antonio
6       San-Diego
7         Dallas
Name: city, dtype: object

#Real-World String Cleaning Workflow

Example messy dataset:

name	city
" ali "	"new-york"
"SARA "	"los-angeles"

Cleaning workflow:

`df["name"] = df["name"].str.strip().str.lower().str.title()`

`df["city"] = df["city"].str.replace("-", " ").str.title()`

#Applying Operations on Multiple Columns

In [82]:
df

,customer_id,name,email,city,job_title
0,101,ali khan,ali.khan@gmail.com,new-york,data analyst
1,102,SARA AHMED,SARA@YAHOO.COM,LOS-ANGELES,DATA SCIENTIST
2,103,ahMeD RAZA,ahmed123@gmail.com,chicago,machine learning engineer
3,104,Fatima Noor,fatima_noor@hotmail.com,Houston,software developer
4,105,usman ali,usman.ali@gmail.com,phoenix,data engineer
5,106,Ayesha Malik,ayesha.malik@yahoo.com,SAN-ANTONIO,business analyst
6,107,bilal khan,bilal-khan@gmail.com,san-diego,AI researcher
7,108,HAMZA SHAH,hamza.shah@outlook.com,Dallas,data ANALYST

In [92]:
cols = ['name', 'email', 'city', 'job_title']
df[cols].apply(lambda x: x.str.strip().str.replace(" ", "-").str.title())

,name,email,city,job_title
0,Ali-Khan,Ali.Khan@Gmail.Com,New-York,Data-Analyst
1,Sara-Ahmed,Sara@Yahoo.Com,Los-Angeles,Data-Scientist
2,Ahmed-Raza,Ahmed123@Gmail.Com,Chicago,Machine-Learning-Engineer
3,Fatima-Noor,Fatima_Noor@Hotmail.Com,Houston,Software-Developer
4,Usman-Ali,Usman.Ali@Gmail.Com,Phoenix,Data-Engineer
5,Ayesha-Malik,Ayesha.Malik@Yahoo.Com,San-Antonio,Business-Analyst
6,Bilal-Khan,Bilal-Khan@Gmail.Com,San-Diego,Ai-Researcher
7,Hamza-Shah,Hamza.Shah@Outlook.Com,Dallas,Data-Analyst

#Extract Information

In [93]:
df["domain"] = df["email"].str.split("@").str[1]
df

,customer_id,name,email,city,job_title,domain
0,101,ali khan,ali.khan@gmail.com,new-york,data analyst,gmail.com
1,102,SARA AHMED,SARA@YAHOO.COM,LOS-ANGELES,DATA SCIENTIST,YAHOO.COM
2,103,ahMeD RAZA,ahmed123@gmail.com,chicago,machine learning engineer,gmail.com
3,104,Fatima Noor,fatima_noor@hotmail.com,Houston,software developer,hotmail.com
4,105,usman ali,usman.ali@gmail.com,phoenix,data engineer,gmail.com
5,106,Ayesha Malik,ayesha.malik@yahoo.com,SAN-ANTONIO,business analyst,yahoo.com
6,107,bilal khan,bilal-khan@gmail.com,san-diego,AI researcher,gmail.com
7,108,HAMZA SHAH,hamza.shah@outlook.com,Dallas,data ANALYST,outlook.com