#Pandas String Operation Practice

In [2]:
import pandas as pd

data = {
    "customer_id": [101,102,103,104,105,106,107,108],

    "name": [
        "  ali khan",
        "SARA AHMED ",
        " ahMeD RAZA ",
        "Fatima Noor",
        "  usman ali ",
        "Ayesha Malik ",
        "bilal  khan",
        " HAMZA SHAH"
    ],

    "email": [
        "ali.khan@gmail.com ",
        "SARA@YAHOO.COM",
        " ahmed123@gmail.com",
        "fatima_noor@hotmail.com ",
        "usman.ali@gmail.com",
        "ayesha.malik@yahoo.com ",
        "bilal-khan@gmail.com",
        "hamza.shah@outlook.com"
    ],

    "city": [
        " new-york ",
        "LOS-ANGELES",
        " chicago ",
        "Houston",
        "phoenix ",
        " SAN-ANTONIO",
        "san-diego",
        " Dallas "
    ],

    "job_title": [
        "data analyst",
        "DATA SCIENTIST",
        "machine learning engineer",
        "software developer",
        "data engineer",
        "business analyst",
        "AI researcher",
        "data ANALYST"
    ]
}

df = pd.DataFrame(data)
df

,customer_id,name,email,city,job_title
0,101,ali khan,ali.khan@gmail.com,new-york,data analyst
1,102,SARA AHMED,SARA@YAHOO.COM,LOS-ANGELES,DATA SCIENTIST
2,103,ahMeD RAZA,ahmed123@gmail.com,chicago,machine learning engineer
3,104,Fatima Noor,fatima_noor@hotmail.com,Houston,software developer
4,105,usman ali,usman.ali@gmail.com,phoenix,data engineer
5,106,Ayesha Malik,ayesha.malik@yahoo.com,SAN-ANTONIO,business analyst
6,107,bilal khan,bilal-khan@gmail.com,san-diego,AI researcher
7,108,HAMZA SHAH,hamza.shah@outlook.com,Dallas,data ANALYST

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  8 non-null      int64
 1   name         8 non-null      object
 2   email        8 non-null      object
 3   city         8 non-null      object
 4   job_title    8 non-null      object
dtypes: int64(1), object(4)
memory usage: 452.0+ bytes

#Question 1 — Full Name Cleaning Pipeline

###Clean the name column so that:

####"  ali khan" → "Ali Khan"
####"bilal  khan" → "Bilal Khan"

###Requirements:

####remove extra spaces

####ensure only one space between words

####convert to title case

In [56]:
df['name'].str.strip().str.replace(r"\s+"," ",regex=True).str.title()

0        Ali Khan
1      Sara Ahmed
2      Ahmed Raza
3     Fatima Noor
4       Usman Ali
5    Ayesha Malik
6      Bilal Khan
7      Hamza Shah
Name: name, dtype: object

#Question 2 — Email Standardization

###Clean the email column so that:

####"SARA@YAHOO.COM" → "sara@yahoo.com"
####" ali.khan@gmail.com " → "ali.khan@gmail.com"

###Requirements:

####remove spaces

####convert to lowercase

In [6]:
df['email'].str.strip().str.lower()

0         ali.khan@gmail.com
1             sara@yahoo.com
2         ahmed123@gmail.com
3    fatima_noor@hotmail.com
4        usman.ali@gmail.com
5     ayesha.malik@yahoo.com
6       bilal-khan@gmail.com
7     hamza.shah@outlook.com
Name: email, dtype: object

#Question 3 — Extract Email Domain

####Create a new column called domain.

###Example:

####ali.khan@gmail.com → gmail.com

In [57]:
df['domain']= df['email'].str.strip().str.split("@").str[1].str.lower()
df['domain']

0      gmail.com
1      yahoo.com
2      gmail.com
3    hotmail.com
4      gmail.com
5      yahoo.com
6      gmail.com
7    outlook.com
Name: domain, dtype: object

#Question 4 — Gmail Users Filter

###Create a new dataframe containing only Gmail users.

In [66]:
gmail_users= df[df['email'].str.rstrip().str.endswith("@gmail.com")]
gmail_users

,customer_id,name,email,city,job_title,domain,new,first_name,last_name,name_length
0,101,ali khan,ali.khan@gmail.com,new-york,data analyst,gmail.com,True,Ali,Khan,8
2,103,ahMeD RAZA,ahmed123@gmail.com,chicago,machine learning engineer,gmail.com,True,Ahmed,Raza,10
4,105,usman ali,usman.ali@gmail.com,phoenix,data engineer,gmail.com,True,Usman,Ali,9
6,107,bilal khan,bilal-khan@gmail.com,san-diego,AI researcher,gmail.com,True,Bilal,Khan,11

#Question 5 — City Cleaning

###Clean the city column so that:

####" new-york " → "New York"
####"LOS-ANGELES" → "Los Angeles"

###Requirements:

####remove spaces

####replace - with space

####convert to title case

In [25]:
df['city'].str.strip().str.replace("-", " ").str.title()

0       New York
1    Los Angeles
2        Chicago
3        Houston
4        Phoenix
5    San Antonio
6      San Diego
7         Dallas
Name: city, dtype: object

#Question 6 — Detect Double Spaces in Names

####Find rows where the name contains multiple spaces between words.

###Example problem:

####"bilal  khan"

In [58]:
df['name'].str.strip().str.contains(r"\s{2,}",regex=True)

0    False
1    False
2    False
3    False
4    False
5    False
6     True
7    False
Name: name, dtype: bool

#Question 7 — Extract First Name

###Create a new column:

####first_name

###Example:

####Ali Khan → Ali
####Sara Ahmed → Sara

In [59]:
df['first_name']= df['name'].str.strip().str.replace(r"\s+"," ",regex=True).str.split(" ", expand = True)[0].str.title()
df['first_name']

0       Ali
1      Sara
2     Ahmed
3    Fatima
4     Usman
5    Ayesha
6     Bilal
7     Hamza
Name: first_name, dtype: object

#Question 8 — Extract Last Name

###Create another column:

####last_name

###Example:

####Ali Khan → Khan
####Sara Ahmed → Ahmed

In [60]:
df['last_name']= df['name'].str.strip().str.replace(r"\s+"," ",regex=True).str.split(" ", expand = True)[1].str.title()
df['last_name']

0     Khan
1    Ahmed
2     Raza
3     Noor
4      Ali
5    Malik
6     Khan
7     Shah
Name: last_name, dtype: object

#Question 9 — Length of Names

####Create a column:

###name_length

####This should store the length of each cleaned name.

In [61]:
df['name_length'] = df['name'].str.strip().str.len()
df['name_length']

0     8
1    10
2    10
3    11
4     9
5    12
6    11
7    10
Name: name_length, dtype: int64

#Question 10 — Job Title Filtering

####Find rows where job title contains the word "data".

####The search should not fail because of capitalization differences.

In [62]:
df['job_title'].str.contains("data",case=False)

0     True
1     True
2    False
3    False
4     True
5    False
6    False
7     True
Name: job_title, dtype: bool