#6. Pandas Data Transformation Practice

In [1]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "employee": ["Ali", "Sara", "Omar", "Ayesha", "Bilal"],
    "base_salary": [5000, 4200, 6100, 4800, 5300],
    "bonus": [500, 300, 700, 400, 600],
    "tax_rate": [0.10, 0.08, 0.12, 0.09, 0.11],
    "working_days": [22, 20, 24, 21, 23]
})

df

  employee  base_salary  bonus  tax_rate  working_days
0      Ali         5000    500      0.10            22
1     Sara         4200    300      0.08            20
2     Omar         6100    700      0.12            24
3   Ayesha         4800    400      0.09            21
4    Bilal         5300    600      0.11            23

#1 Creating New Columns
#2 Column Arithmetic Operations

##Problem 1 — Total Income

####Create a new column called total_income.

In [2]:
df['total_income'] = df['base_salary'] + df['bonus']
df['total_income']

0    5500
1    4500
2    6800
3    5200
4    5900
Name: total_income, dtype: int64

##Problem 2 — Monthly Tax Amount

####Create a column called tax_amount.

In [3]:
df['tax_amount'] = df['base_salary'] * df['tax_rate']
df['tax_amount']

0    500.0
1    336.0
2    732.0
3    432.0
4    583.0
Name: tax_amount, dtype: float64

##Problem 3 — Net Salary After Tax

####Create a column net_salary.

In [5]:
df['net_salary'] = (df['base_salary'] + df['bonus']) - df['tax_amount']
df['net_salary']

0    5000.0
1    4164.0
2    6068.0
3    4768.0
4    5317.0
Name: net_salary, dtype: float64

##Problem 4 — Salary Per Working Day

####Create a column called salary_per_day.

In [6]:
df['salary_per_day'] = df['base_salary'] / df['working_days']
df

,employee,base_salary,bonus,tax_rate,working_days,total_income,tax_amount,net_salary,salary_per_day
0,Ali,5000,500,0.10,22,5500,500.0,5000.0,227.272727
1,Sara,4200,300,0.08,20,4500,336.0,4164.0,210.000000
2,Omar,6100,700,0.12,24,6800,732.0,6068.0,254.166667
3,Ayesha,4800,400,0.09,21,5200,432.0,4768.0,228.571429
4,Bilal,5300,600,0.11,23,5900,583.0,5317.0,230.434783

##Problem 5 — Bonus Percentage

####Create a column called bonus_percent.

In [7]:
df['bonus_percent'] = (df['bonus']/df['base_salary']) * 100
df['bonus_percent']

0    10.000000
1     7.142857
2    11.475410
3     8.333333
4    11.320755
Name: bonus_percent, dtype: float64

#3. Apply() Function

In [8]:
df = pd.DataFrame({
    "employee": ["Ali", "Sara", "Omar", "Ayesha", "Bilal"],
    "salary": [5000, 4200, 6100, 4800, 5300],
    "bonus": [500, 300, 700, 400, 600],
    "experience": [2, 4, 6, 3, 5]
})
df

  employee  salary  bonus  experience
0      Ali    5000    500           2
1     Sara    4200    300           4
2     Omar    6100    700           6
3   Ayesha    4800    400           3
4    Bilal    5300    600           5

##Problem 1

####Create a new column called salary_tax.
####You must use apply().

In [9]:
df['salary_tax'] = df['salary'].apply(lambda x: x*0.10)
df['salary_tax']

0    500.0
1    420.0
2    610.0
3    480.0
4    530.0
Name: salary_tax, dtype: float64

##Problem 2 (Column Apply with Condition)

####Create a column bonus_after_cut.

###Rule:

####If bonus > 500 → reduce bonus by 50
####Otherwise keep bonus same

####You must use apply().

In [10]:
df['bonus_after_cut'] = df['bonus'].apply(lambda x: x - 50 if x > 500 else x)
df['bonus_after_cut']

0    500
1    300
2    650
3    400
4    550
Name: bonus_after_cut, dtype: int64

##Problem 3

####Create a column called total_income.

####But this time you must use row-wise apply.

In [13]:
df['total_income'] = df.apply(lambda x: (x['salary'] + x['bonus']),axis= 1)
df['total_income']

0    5500
1    4500
2    6800
3    5200
4    5900
Name: total_income, dtype: int64

##Problem 4 (Row Apply — Conditional Logic)

####Create a column experience_level.

###Rules:

####experience >= 5 → "Senior"
####experience >= 3 → "Mid"
####otherwise → "Junior"

###You must use apply().

In [27]:
def ex(x):
  if x>=5:
    return "Senior"
  elif x>=3:
    return "Mid"
  else:
    return "Junior"


df['experience_level'] = df['experience'].apply(ex)
df[['experience', 'experience_level']]

   experience experience_level
0           2           Junior
1           4              Mid
2           6           Senior
3           3              Mid
4           5           Senior

##Problem 5

####Create a column called performance_score.

In [32]:
def performance(x):
  score= x["salary"]*0.3 + x['bonus']*0.5 + x['experience']*100
  if score > 5000:
    return "Excellent"
  elif score > 4000:
    return "Good"
  else:
    return "Average"

df['performance_score'] = df.apply(performance, axis=1)
df['performance_score']

0    Average
1    Average
2    Average
3    Average
4    Average
Name: performance_score, dtype: object

#4. Map() Function

In [33]:
df = pd.DataFrame({
    "employee": ["Ali", "Sara", "Omar", "Ayesha", "Bilal"],
    "department": ["IT", "HR", "IT", "Finance", "HR"],
    "city": ["London", "Paris", "London", "Berlin", "Paris"],
    "experience": [2, 4, 6, 3, 5]
})
df

  employee department    city  experience
0      Ali         IT  London           2
1     Sara         HR   Paris           4
2     Omar         IT  London           6
3   Ayesha    Finance  Berlin           3
4    Bilal         HR   Paris           5

##Problem 1

###Convert department names to codes.

In [34]:
df['department_codes'] = df['department'].map({"IT":101, "HR":102, "Finance": 103})
df['department_codes']

0    101
1    102
2    101
3    103
4    102
Name: department_codes, dtype: int64

##Problem 2 — City Abbreviation Mapping

###Convert city names to short codes.

####London → LDN
####Paris → PAR
####Berlin → BER

In [36]:
df['city_code'] = df['city'].map({"London":"LDN", "Paris":"PAR","Berlin":"BER"})
df['city_code']

0    LDN
1    PAR
2    LDN
3    BER
4    PAR
Name: city_code, dtype: object

##Problem 3 — Experience Category (Using Lambda)

###Create column:

####experience_level

###Rules:

####experience >= 5 → Senior
####otherwise → Junior

In [37]:
df['experience_level'] = df['experience'].map(lambda x: "Senior" if x >= 5 else "Junior")
df

,employee,department,city,experience,department_codes,city_code,experience_level
0,Ali,IT,London,2,101,LDN,Junior
1,Sara,HR,Paris,4,102,PAR,Junior
2,Omar,IT,London,6,101,LDN,Senior
3,Ayesha,Finance,Berlin,3,103,BER,Junior
4,Bilal,HR,Paris,5,102,PAR,Senior

##Problem 4 — Name Length

###Create column:

####name_length

####It should contain the number of characters in the employee name.

In [52]:
df['name_length'] = df['employee'].map(lambda x: len(x) )
df

,employee,department,city,experience,department_codes,city_code,experience_level,name_length,employee_upper,priority_score
0,Ali,IT,London,2,101,LDN,Junior,3,ALI,3
1,Sara,HR,Paris,4,102,PAR,Junior,4,SARA,1
2,Omar,IT,London,6,101,LDN,Senior,4,OMAR,3
3,Ayesha,Finance,Berlin,3,103,BER,Junior,6,AYESHA,2
4,Bilal,HR,Paris,5,102,PAR,Senior,5,BILAL,1

##Problem 5 — Capitalize Names

###Create column:

####employee_upper

####Convert names to uppercase using map().

In [51]:
df['employee_upper'] = df['employee'].map(lambda x: x.upper())
df

,employee,department,city,experience,department_codes,city_code,experience_level,name_length,employee_upper,priority_score
0,Ali,IT,London,2,101,LDN,Junior,3,ALI,3
1,Sara,HR,Paris,4,102,PAR,Junior,4,SARA,1
2,Omar,IT,London,6,101,LDN,Senior,4,OMAR,3
3,Ayesha,Finance,Berlin,3,103,BER,Junior,6,AYESHA,2
4,Bilal,HR,Paris,5,102,PAR,Senior,5,BILAL,1

##Problem 6

####Some departments get priority scores.

###Mapping:

####IT → 3
####Finance → 2
####HR → 1

###Create column:

####priority_score

In [46]:
df['priority_score'] = df['department'].map({'IT':3,"Finance":2, "HR":1}).fillna(0)
df

,employee,department,city,experience,department_codes,city_code,experience_level,name_length,employee_upper,priority_score
0,Ali,IT,London,2,101,LDN,Junior,ALI,ALI,3
1,Sara,HR,Paris,4,102,PAR,Junior,SARA,SARA,1
2,Omar,IT,London,6,101,LDN,Senior,OMAR,OMAR,3
3,Ayesha,Finance,Berlin,3,103,BER,Junior,AYESHA,AYESHA,2
4,Bilal,HR,Paris,5,102,PAR,Senior,BILAL,BILAL,1