# Data Aggregation & Grouping

## Topics Covered:
1. GroupBy Fundamentals
2. Basic Aggregation Functions
3. Multiple Aggregations (.agg)
4. Grouping by Multiple Columns
5. Sorting Aggregated Data
6. Counting & Frequencies (value_counts)
7. Ranking
8. Resetting Index
9. Named Aggregations
10. Filtering Groups

## Objective:
To summarize, analyze, and extract meaningful insights from data using grouping techniques.

## Use:
- Sales analysis (revenue by product/city)
- Customer segmentation
- Performance comparison
- Business insights generation

#Topic 1: GroupBy Fundamentals
###1. What is GroupBy?
####GroupBy is used to split data into groups based on one or more columns, apply operations on each group, and then combine the results.
###Split → Apply → Combine

####Split → Divide data into groups

####Apply → Perform operation (sum, mean, etc.)

####Combine → Merge results

In [1]:
import pandas as pd

data = {
    "City": ["Lahore", "Karachi", "Lahore", "Islamabad", "Karachi", "Lahore"],
    "Product": ["Laptop", "Mobile", "Tablet", "Laptop", "Tablet", "Mobile"],
    "Sales": [100000, 50000, 30000, 70000, 20000, 60000],
    "Profit": [20000, 10000, 5000, 15000, 3000, 12000]
}
df = pd.DataFrame(data)
df

        City Product   Sales  Profit
0     Lahore  Laptop  100000   20000
1    Karachi  Mobile   50000   10000
2     Lahore  Tablet   30000    5000
3  Islamabad  Laptop   70000   15000
4    Karachi  Tablet   20000    3000
5     Lahore  Mobile   60000   12000

In [2]:
df.groupby('City')

####To get meaningful results, we must apply an aggregation function.

In [3]:
df.groupby("City")['Sales'].sum()

City
Islamabad     70000
Karachi       70000
Lahore       190000
Name: Sales, dtype: int64

####Total Sales per City

###Grouping by Multiple Columns

In [4]:
df.groupby(["City", "Product"])["Sales"].sum()

City       Product
Islamabad  Laptop      70000
Karachi    Mobile      50000
           Tablet      20000
Lahore     Laptop     100000
           Mobile      60000
           Tablet      30000
Name: Sales, dtype: int64

###Understanding the Output (VERY IMPORTANT)

####Output is a Series with hierarchical index (MultiIndex)

###Example:

####City       Product
####Lahore     Laptop     100000
####           Mobile      60000


####This is called a MultiIndex (nested index).

##As_Index Parameter
####By default, groupby sets grouped column as index.

In [5]:
df.groupby("City", as_index= False)['Sales'].sum()

        City   Sales
0  Islamabad   70000
1    Karachi   70000
2     Lahore  190000

In [6]:
df.groupby("City")['Sales'].sum()

City
Islamabad     70000
Karachi       70000
Lahore       190000
Name: Sales, dtype: int64

##Iterating Through Groups
####We can loop through each group for deeper understanding.

In [7]:
for city, group in df.groupby("City"):
  print(city)
  print(group)

Islamabad
        City Product  Sales  Profit
3  Islamabad  Laptop  70000   15000
Karachi
      City Product  Sales  Profit
1  Karachi  Mobile  50000   10000
4  Karachi  Tablet  20000    3000
Lahore
     City Product   Sales  Profit
0  Lahore  Laptop  100000   20000
2  Lahore  Tablet   30000    5000
5  Lahore  Mobile   60000   12000

- GroupBy splits data into groups
- Requires aggregation to produce results
- Can group by one or multiple columns
- Output often uses MultiIndex
- as_index=False makes output cleaner

#Topic 2: Basic Aggregation Functions
###1. What are Aggregation Functions?
####Aggregation functions are used to summarize data by performing calculations on groups.

####They reduce multiple values into a single value.
###Examples:

####Many sales → Total sales

####Many salaries → Average salary

###Why Aggregation is important
####Aggregation helps in extracting meaningful insights from data, such as:
- Total revenue
- Average profit
- Maximum sales
- Minimum performance

###Common aggregation Functions
####The most important aggregation functions are:
- sum() → Total
- mean() → Average
- count() → Number of values
- min() → Smallest value
- max() → Largest value
- median() → Middle value

##Using Aggregation with GroupBy
###Sum()
Total Sales per City

In [8]:
df.groupby("City")["Sales"].sum()

City
Islamabad     70000
Karachi       70000
Lahore       190000
Name: Sales, dtype: int64

###Mean (Average)

In [9]:
df.groupby("City")['Profit'].mean()

City
Islamabad    15000.000000
Karachi       6500.000000
Lahore       12333.333333
Name: Profit, dtype: float64

###Count

In [10]:
df.groupby("City")['Product'].count()

City
Islamabad    1
Karachi      2
Lahore       3
Name: Product, dtype: int64

###Min()

In [11]:
df.groupby("City")['Sales'].min()

City
Islamabad    70000
Karachi      20000
Lahore       30000
Name: Sales, dtype: int64

###Max()

In [12]:
df.groupby("City")['Sales'].max()

City
Islamabad     70000
Karachi       50000
Lahore       100000
Name: Sales, dtype: int64

###Median() Middle Value (useful when data has outliers)

In [13]:
df.groupby("City")['Sales'].median()

City
Islamabad    70000.0
Karachi      35000.0
Lahore       60000.0
Name: Sales, dtype: float64

###Applying Aggregation Without GroupBy
####Aggregation can also be applied to entire columns.

In [14]:
df.groupby("City").sum()

                      Product   Sales  Profit
City
Islamabad              Laptop   70000   15000
Karachi          MobileTablet   70000   13000
Lahore     LaptopTabletMobile  190000   37000

In [15]:
df.groupby("Sales").sum()

             City Product  Profit
Sales
20000     Karachi  Tablet    3000
30000      Lahore  Tablet    5000
50000     Karachi  Mobile   10000
60000      Lahore  Mobile   12000
70000   Islamabad  Laptop   15000
100000     Lahore  Laptop   20000

###Multiple Columns Aggregation
####We can apply aggregation on multiple columns at once.

In [16]:
df.groupby("City")[['Sales','Profit']].sum()

            Sales  Profit
City
Islamabad   70000   15000
Karachi     70000   13000
Lahore     190000   37000

###Difference Between count() and size()
####count() → counts non-null values
####size() → counts all rows (including nulls)

In [17]:
df.groupby("City")["Sales"].count()

City
Islamabad    1
Karachi      2
Lahore       3
Name: Sales, dtype: int64

In [18]:
df.groupby("City")["Sales"].size()

City
Islamabad    1
Karachi      2
Lahore       3
Name: Sales, dtype: int64

##Numeric Columns Only Behavior
####Aggregation functions automatically ignore non-numeric columns
####(except count()).

###Chaining with Sorting (Real Insight)
###Instantly shows:

####Best performing city

####Worst performing city

In [19]:
df.groupby("City")['Sales'].sum().sort_values(ascending=False)

City
Lahore       190000
Islamabad     70000
Karachi       70000
Name: Sales, dtype: int64

###Output Type
###Aggregation usually returns:
- Series (single column)
- DataFrame (multiple columns)

####Aggregation = “Summarizing data into insights”
- Aggregation reduces multiple values to one value
- Works with groupby to summarize data
- sum, mean, count, min, max are most important
- median is useful for outliers
- Sorting makes results meaningful

#Topic 3: Multiple Aggregations (.agg())

##1. What is Multiple Aggregation?
####Multiple aggregation means applying more than one aggregation function
on grouped data at the same time.

###Instead of:

####Only sum

####Only mean

###You can get:

####sum + mean + max → together

##2. Using .agg() with Single Column
####We can apply multiple functions to a single column using .agg().

In [20]:
df.groupby("City")['Sales'].agg(['sum','mean','min'])

              sum          mean    min
City
Islamabad   70000  70000.000000  70000
Karachi     70000  35000.000000  20000
Lahore     190000  63333.333333  30000

####Output:

Total sales

Average sales

Maximum sales
###.agg() accepts a list of functions

##3. Using .agg() with Multiple Columns
####We can apply multiple aggregations on multiple columns.
###Output Note
####This creates MultiIndex columns (nested column names).

In [21]:
df.groupby("City")[['Sales','Profit']].agg(['sum','mean'])

            Sales               Profit
              sum          mean    sum          mean
City
Islamabad   70000  70000.000000  15000  15000.000000
Karachi     70000  35000.000000  13000   6500.000000
Lahore     190000  63333.333333  37000  12333.333333

##4. Different Functions for Different Columns
####We can assign different aggregation functions to different columns.

In [22]:
df.groupby("City").agg({
    "Sales": "sum",
    "Profit": "mean"})

            Sales        Profit
City
Islamabad   70000  15000.000000
Karachi     70000   6500.000000
Lahore     190000  12333.333333

##5. List of Functions in .agg()
####Common functions used in .agg():

- "sum"
- "mean"
- "count"
- "min"
- "max"
- "median"
- "std" (standard deviation)

##6. Named Aggregations
####Named aggregation allows us to give custom column names to results.

In [23]:
df.groupby("City").agg(
    Total_Sales = ("Sales", "sum"),
    Avg_Profit = ("Profit", "mean")
        )

           Total_Sales    Avg_Profit
City
Islamabad        70000  15000.000000
Karachi          70000   6500.000000
Lahore          190000  12333.333333

##7. Output Structure & Understanding
###.agg() can return:
- DataFrame with multiple columns
- MultiIndex columns (if not named properly)

###Example:

In [24]:
df.groupby("City")["Sales"].agg(["sum", "mean"])

              sum          mean
City
Islamabad   70000  70000.000000
Karachi     70000  35000.000000
Lahore     190000  63333.333333

##8. Combine with Sorting

In [72]:
df.groupby("City").agg(
    Total_Sales= ("Sales", "sum"),
    Avg_Profit = ("Profit", "mean")
).sort_values(by= "Total_Sales", ascending = False)

           Total_Sales    Avg_Profit
City
Lahore          190000  12333.333333
Islamabad        70000  15000.000000
Karachi          70000   6500.000000

###ALL Codes at one place
`df.groupby("City")[["Sales","Profit"]].agg("sum","mean").sort_values(by= "Sales", ascending=False)`

`df.groupby("City").agg({"Sales":"sum","Profit":"mean"}).sort_values(by= "Profit", ascending=False)`

`df.groupby("City").agg(Total_Sales= ("Sales","sum"), Avg_profit = ("Profit", "mean")).sort_values(by= "Avg_profit", ascending=False)`

##9. When to Use .agg() vs Normal Aggregation
###Use simple aggregation when:
- Only one function is needed

###Use .agg() when:
- Multiple functions are needed
- Different columns need different operations

###.agg() = “Multiple summaries in one step”
- .agg() allows multiple aggregations at once
- Can be used on single or multiple columns
- Can apply different functions to different columns
- Named aggregation makes output clean and professional

#Topic 4: Grouping by Multiple Columns
##1. What is Multi-Column Grouping?
####Grouping by multiple columns means splitting data based on more than one category.

####- Instead of grouping by just 'City' → group by 'City' AND 'Product'.
####- Useful for business insights like:
    - Total sales per product in each city
    - Average profit per department in each region

##2. Syntax for Multiple Columns
`df.groupby(["City", "Product"])`

##3. Aggregation on Multiple Columns

In [26]:
df.groupby(["City", "Product"])[["Sales", "Profit"]].sum()

                    Sales  Profit
City      Product
Islamabad Laptop    70000   15000
Karachi   Mobile    50000   10000
          Tablet    20000    3000
Lahore    Laptop   100000   20000
          Mobile    60000   12000
          Tablet    30000    5000

##4. MultiIndex Output (Understanding the Structure)
###Grouping by multiple columns produces a MultiIndex:

###Example:

City       Product

Karachi    Mobile
           Tablet

Lahore     Laptop
           Mobile

###City → first level of index

###Product → second level of index

###Values → aggregated numbers

##5. Accessing Specific Groups
###Using .loc on MultiIndex

In [27]:
grouped = df.groupby(["City", "Product"])[["Sales", "Profit"]].sum()
grouped

                    Sales  Profit
City      Product
Islamabad Laptop    70000   15000
Karachi   Mobile    50000   10000
          Tablet    20000    3000
Lahore    Laptop   100000   20000
          Mobile    60000   12000
          Tablet    30000    5000

In [28]:
grouped.loc[("Islamabad","Laptop")]

Sales     70000
Profit    15000
Name: (Islamabad, Laptop), dtype: int64

In [29]:
grouped.loc['Karachi','Tablet']

Sales     20000
Profit     3000
Name: (Karachi, Tablet), dtype: int64

###using .xs(Cross-Section)

In [30]:
grouped

                    Sales  Profit
City      Product
Islamabad Laptop    70000   15000
Karachi   Mobile    50000   10000
          Tablet    20000    3000
Lahore    Laptop   100000   20000
          Mobile    60000   12000
          Tablet    30000    5000

In [31]:
grouped.xs('Karachi', level='City')

         Sales  Profit
Product
Mobile   50000   10000
Tablet   20000    3000

In [32]:
grouped.xs("Laptop", level = 'Product')

            Sales  Profit
City
Islamabad   70000   15000
Lahore     100000   20000

##6. Sorting Multi-Column Groups
####Sort by first column (City) and then Sales

In [33]:
df.groupby(['City', "Product"])['Sales'].sum().sort_values(ascending= False)

City       Product
Lahore     Laptop     100000
Islamabad  Laptop      70000
Lahore     Mobile      60000
Karachi    Mobile      50000
Lahore     Tablet      30000
Karachi    Tablet      20000
Name: Sales, dtype: int64

###Sort by index levels

In [34]:
grouped

                    Sales  Profit
City      Product
Islamabad Laptop    70000   15000
Karachi   Mobile    50000   10000
          Tablet    20000    3000
Lahore    Laptop   100000   20000
          Mobile    60000   12000
          Tablet    30000    5000

In [35]:
grouped.sort_index(level="City")

                    Sales  Profit
City      Product
Islamabad Laptop    70000   15000
Karachi   Mobile    50000   10000
          Tablet    20000    3000
Lahore    Laptop   100000   20000
          Mobile    60000   12000
          Tablet    30000    5000

In [36]:
grouped.sort_index(level= ("City", "Product"))

                    Sales  Profit
City      Product
Islamabad Laptop    70000   15000
Karachi   Mobile    50000   10000
          Tablet    20000    3000
Lahore    Laptop   100000   20000
          Mobile    60000   12000
          Tablet    30000    5000

##7. Resetting Index for Cleaner Output

In [37]:
df.groupby(["City","Product"])[['Sales',"Profit"]].sum().reset_index()

        City Product   Sales  Profit
0  Islamabad  Laptop   70000   15000
1    Karachi  Mobile   50000   10000
2    Karachi  Tablet   20000    3000
3     Lahore  Laptop  100000   20000
4     Lahore  Mobile   60000   12000
5     Lahore  Tablet   30000    5000

##8. Real-World Thinking (Professional Level)

###Multi-column grouping is how analysts answer layered questions:

Examples:

“Which product in which city brings the most revenue?”

“Which month and store combination had highest sales?”

“Which department in which branch has the best performance?”

##Key Points:
- Multi-column grouping splits data by combinations of columns
- Produces MultiIndex output
- Can aggregate multiple columns at once
- Access specific groups using .loc or .xs()
- Sorting and resetting index makes results cleaner
- Essential for layered, real-world business insights

#Topic 5: Sorting Aggregated Data

##1. Why Sorting is Important
####Aggregated/grouped data is useful, but raw output is often unordered.

###Sorting helps:
- Identify top/bottom performers
- Quickly find insights
- Make reports more readable

##2. Sorting a Series
####Example: Grouped Sales by City

In [38]:
grouped_sales= df.groupby("City")["Sales"].sum()
grouped_sales

City
Islamabad     70000
Karachi       70000
Lahore       190000
Name: Sales, dtype: int64

###Output unordered
###Now Sort by values

In [39]:
grouped_sales.sort_values(ascending=False)

City
Lahore       190000
Islamabad     70000
Karachi       70000
Name: Sales, dtype: int64

##3. Sorting a DataFrame

####If you reset index after grouping:

In [40]:
grouped_sales.reset_index()

        City   Sales
0  Islamabad   70000
1    Karachi   70000
2     Lahore  190000

###Sort by a column

In [73]:
df.groupby(["City","Product"])[["Sales","Profit"]].sum().sort_values(by = "Profit", ascending=False).reset_index()

        City Product   Sales  Profit
0     Lahore  Laptop  100000   20000
1  Islamabad  Laptop   70000   15000
2     Lahore  Mobile   60000   12000
3    Karachi  Mobile   50000   10000
4     Lahore  Tablet   30000    5000
5    Karachi  Tablet   20000    3000

##4. Sorting by Index

####If grouped output is a Series with MultiIndex:

In [42]:
grouped = df.groupby(["City", "Product"])["Sales"].sum()
grouped

City       Product
Islamabad  Laptop      70000
Karachi    Mobile      50000
           Tablet      20000
Lahore     Laptop     100000
           Mobile      60000
           Tablet      30000
Name: Sales, dtype: int64

In [43]:
grouped.sort_index(level=['City','Product'])

City       Product
Islamabad  Laptop      70000
Karachi    Mobile      50000
           Tablet      20000
Lahore     Laptop     100000
           Mobile      60000
           Tablet      30000
Name: Sales, dtype: int64

##5. Ascending vs Descending
### Descending (default False)
`grouped.sort_values(ascending=False)`

### Ascending (default True)
`grouped.sort_values(ascending=True)`

##6. Sorting MultiIndex Groups
####Sort by values in MultiIndex

In [44]:
grouped= df.groupby(["City","Product"])['Sales'].sum().sort_values(ascending=False)
grouped

City       Product
Lahore     Laptop     100000
Islamabad  Laptop      70000
Lahore     Mobile      60000
Karachi    Mobile      50000
Lahore     Tablet      30000
Karachi    Tablet      20000
Name: Sales, dtype: int64

###Sort by Index

In [45]:
grouped.sort_index(level= ("City","Product"),ascending=[False,False])

City       Product
Lahore     Tablet      30000
           Mobile      60000
           Laptop     100000
Karachi    Tablet      20000
           Mobile      50000
Islamabad  Laptop      70000
Name: Sales, dtype: int64

##7. Reset Index for Clean Output

In [78]:
df.groupby(["City", "Product"]).agg(
    Total_values= ("Sales", "sum"),
    Avg_Profit = ("Profit", "mean")
).sort_values(by= ["Total_values", 'Avg_Profit'] ,ascending= [True, False]).sort_index(level=["City", "Product"], ascending= [True,False]).reset_index()

        City Product  Total_values  Avg_Profit
0  Islamabad  Laptop         70000     15000.0
1    Karachi  Tablet         20000      3000.0
2    Karachi  Mobile         50000     10000.0
3     Lahore  Tablet         30000      5000.0
4     Lahore  Mobile         60000     12000.0
5     Lahore  Laptop        100000     20000.0

##Key Points
- Sorting is essential for readable aggregated data
- Use sort_values() to sort by aggregated values
- Use sort_index() to sort by index (single or MultiIndex)
- Chaining with groupby makes analysis clean & professional
- Always reset index for portfolio-ready output

###Chaining groupby, aggregation, and sorting in one line creates
###clean, professional, and report-ready analysis.

##Just three operations to keep in mind:


1.   sort_values(ascending= False)
2.   sort_index(level= ("City", "Product"), ascending = [True,False])
3.   reset_index()

#Topic 6: Counting & Frequencies (value_counts & .count())

##1. Difference Between count() and value_counts()
- `count()` → Counts non-null values in a column (or group)
- `value_counts()` → Counts **frequency of each unique value**

##2. Using value_counts() for a Single Column
####Instantly shows how many rows belong to each city

In [47]:
df['City'].value_counts()

City
Lahore       3
Karachi      2
Islamabad    1
Name: count, dtype: int64

##3. Sorting value_counts()

####By default, value_counts() sorts descending by frequency:

In [48]:
df['City'].value_counts()

City
Lahore       3
Karachi      2
Islamabad    1
Name: count, dtype: int64

####Ascending sort:

In [49]:
df['City'].value_counts(ascending=True)

City
Islamabad    1
Karachi      2
Lahore       3
Name: count, dtype: int64

##4. Normalizing value_counts() (Percentages)

In [50]:
df['City'].value_counts(normalize=True)

City
Lahore       0.500000
Karachi      0.333333
Islamabad    0.166667
Name: proportion, dtype: float64

##5. Handling NaN Values

In [79]:
df.groupby('City')['Product'].value_counts(dropna=False)

City       Product
Islamabad  Laptop     1
Karachi    Mobile     1
           Tablet     1
Lahore     Laptop     1
           Mobile     1
           Tablet     1
Name: count, dtype: int64

Includes NaN values in counts

Helps detect missing categories

##6. GroupBy + count()
####We can count rows per group using GroupBy

In [52]:
df.groupby("City")['Sales'].count()

City
Islamabad    1
Karachi      2
Lahore       3
Name: Sales, dtype: int64

##7. GroupBy + value_counts() (Advanced)

####Sometimes you want distribution of one column within groups:

In [53]:
df.groupby("City")["Product"].value_counts()

City       Product
Islamabad  Laptop     1
Karachi    Mobile     1
           Tablet     1
Lahore     Laptop     1
           Mobile     1
           Tablet     1
Name: count, dtype: int64

##Key Points
- count() → counts non-null rows
- value_counts() → counts frequency of unique values
- normalize=True → gives percentages
- dropna=False → includes missing values
- Combine with groupby for segmented frequencies
- Essential for EDA & quick portfolio analysis

#Topic 7: Ranking in Pandas

##1. What is Ranking?
####Ranking assigns a rank or position to each value in a dataset based on its magnitude.

###Example:
- Highest sales → rank 1
- Lowest sales → rank last

##2. Using .rank() on a Series

In [54]:
df['Sales'].rank()

0    6.0
1    3.0
2    2.0
3    5.0
4    1.0
5    4.0
Name: Sales, dtype: float64

##3. Ranking Methods
###Methods:

average → default, average rank for ties

min → all ties get minimum rank

max → all ties get maximum rank

first → ranks according to order in data

dense → like min but no gaps

In [55]:
import pandas as pd

data = {
    "City": ["Lahore", "Karachi", "Lahore", "Islamabad", "Karachi", "Lahore"],
    "Product": ["Laptop", "Mobile", "Tablet", "Laptop", "Tablet", "Mobile"],
    "Sales": [100000, 50000, 70000, 70000, 20000, 100000],
    "Profit": [20000, 10000, 5000, 15000, 3000, 12000]
}
df1 = pd.DataFrame(data)
df1

        City Product   Sales  Profit
0     Lahore  Laptop  100000   20000
1    Karachi  Mobile   50000   10000
2     Lahore  Tablet   70000    5000
3  Islamabad  Laptop   70000   15000
4    Karachi  Tablet   20000    3000
5     Lahore  Mobile  100000   12000

In [56]:
df1["Sales"].rank(method="min")

0    5.0
1    2.0
2    3.0
3    3.0
4    1.0
5    5.0
Name: Sales, dtype: float64

In [57]:
df1["Sales"].rank(method="max")

0    6.0
1    2.0
2    4.0
3    4.0
4    1.0
5    6.0
Name: Sales, dtype: float64

In [58]:
df1["Sales"].rank(method="first")

0    5.0
1    2.0
2    3.0
3    4.0
4    1.0
5    6.0
Name: Sales, dtype: float64

In [59]:
df1["Sales"].rank(method="dense")

0    4.0
1    2.0
2    3.0
3    3.0
4    1.0
5    4.0
Name: Sales, dtype: float64

##4. Descending vs Ascending
#### Highest value gets rank 1

In [60]:
df1['Sales'].rank(ascending=False)

0    1.5
1    5.0
2    3.5
3    3.5
4    6.0
5    1.5
Name: Sales, dtype: float64

##5. Ranking Within Groups (GroupBy + rank)

In [61]:
df1.groupby("City")["Sales"].rank(ascending=False)

0    1.5
1    1.0
2    3.0
3    1.0
4    2.0
5    1.5
Name: Sales, dtype: float64

##6. Resetting Index After Ranking

In [62]:
ranked_df = df1.groupby("City")["Sales"].rank(ascending=False).reset_index()

In [63]:
ranked_df

   index  Sales
0      0    1.5
1      1    1.0
2      2    3.0
3      3    1.0
4      4    2.0
5      5    1.5

##Key Points
- `.rank()` assigns order to values
- Can rank ascending or descending
- Several methods to handle ties: average, min, max, first, dense
- Works within groups using GroupBy
- Essential for top-n analysis and leaderboards
- Reset index for clean portfolio outputs

#Topic 8: Resetting Index
#Topic 9: Named Aggregation
##These are already covered in previous topics

#Topic 10: Filtering Groups (.filter())
##1. What is Group Filtering?
####Group filtering is the process of **removing or keeping groups** based on a condition applied to the aggregated group.

###Example:
- Only include cities where total sales > 50,000
- Only include products with average profit > 10,000

##2. Syntax of .filter()
`df.groupby("City").filter(func)`

####func → a function that takes a grouped DataFrame and returns True (keep) or False (drop)

##3. Filtering by Aggregated Value
####Example: Keep cities with total sales > 100,000

In [64]:
df.groupby("City").filter(lambda x: x['Sales'].sum()> 100000)

     City Product   Sales  Profit
0  Lahore  Laptop  100000   20000
2  Lahore  Tablet   30000    5000
5  Lahore  Mobile   60000   12000

##4. Filtering by Multiple Conditions
####Combine conditions with & (and) or | (or)

####Flexible for complex business rules

In [65]:
df.groupby("City").filter(lambda x: (x['Sales'].sum()> 100000) & (x['Profit'].mean()> 5000))

     City Product   Sales  Profit
0  Lahore  Laptop  100000   20000
2  Lahore  Tablet   30000    5000
5  Lahore  Mobile   60000   12000

##5. Using Lambda Functions
#### Keep groups where max sale > 80,000

In [66]:
df.groupby("City").filter(lambda x: x['Sales'].max()> 80000)

     City Product   Sales  Profit
0  Lahore  Laptop  100000   20000
2  Lahore  Tablet   30000    5000
5  Lahore  Mobile   60000   12000

##6. Filter and Keep Only Specific Groups
#### Keep only "Lahore" group

In [67]:
df.groupby("City").filter(lambda x: x.name == 'Lahore')

     City Product   Sales  Profit
0  Lahore  Laptop  100000   20000
2  Lahore  Tablet   30000    5000
5  Lahore  Mobile   60000   12000

####.name → gives the group name (City in this case)

##7. Combining with GroupBy + Aggregation

####You can chain aggregation + filtering:


####Filter first → then select relevant columns

In [68]:
df.groupby("City").filter(lambda x: x["Sales"].sum() > 100000)[["City", "Product", "Sales"]]

     City Product   Sales
0  Lahore  Laptop  100000
2  Lahore  Tablet   30000
5  Lahore  Mobile   60000

##Key Points
- .filter() lets you keep or remove groups based on a condition
- Works on grouped DataFrames
- Use lambda functions for dynamic conditions
- Can combine multiple conditions
- Essential for focusing on meaningful data in analysis and reporting