#Pandas Data Combining

#Topic 1: Concatenation (pd.concat)
##1. What is Concatenation?

###Concatenation means stacking datasets together — either:

####Vertically (rows) → like adding more records

####Horizontally (columns) → like adding more features

###Think of it as:

####SQL UNION (for rows)

OR
#### combining tables side-by-side

###Basic Syntax
`pd.concat([df1, df2], axis=0)`

axis=0 → stack rows (default)

axis=1 → stack columns

##2. Row-wise Concatenation (axis=0)

In [24]:
import pandas as pd

df1 = pd.DataFrame({
    "Name": ["Ali", "Sara"],
    "Sales": [200, 300]
})

df2 = pd.DataFrame({
    "Name": ["Ahmed", "Zara"],
    "Sales": [150, 400]
})

In [25]:
df1

   Name  Sales
0   Ali    200
1  Sara    300

In [26]:
df2

    Name  Sales
0  Ahmed    150
1   Zara    400

In [28]:
result = pd.concat([df1,df2])
result

    Name  Sales
0    Ali    200
1   Sara    300
0  Ahmed    150
1   Zara    400

####Index is not reset automatically
####That’s why there are duplicate indexes: 0,1,0,1

##3. ignore_index=True

In [29]:
result = pd.concat([df1,df2], ignore_index=True)
result

    Name  Sales
0    Ali    200
1   Sara    300
2  Ahmed    150
3   Zara    400

##4. Column-wise Concatenation (axis=1)

In [30]:
result1 = pd.concat([df1,df2], axis= 1)
result1

   Name  Sales   Name  Sales
0   Ali    200  Ahmed    150
1  Sara    300   Zara    400

###Pandas aligns data based on index

##5. Index Alignment Behavior

In [31]:
df1 = pd.DataFrame({"Name": ["Ali", "Sara"]}, index=[0,1])
df2 = pd.DataFrame({"Sales": [200, 300]}, index=[1,2])
df1

   Name
0   Ali
1  Sara

In [32]:
df2

   Sales
1    200
2    300

In [33]:
result2 = pd.concat([df1, df2])
result2

   Name  Sales
0   Ali    NaN
1  Sara    NaN
1   NaN  200.0
2   NaN  300.0

In [34]:
result3 = pd.concat([df1,df2], axis= 1)
result3

   Name  Sales
0   Ali    NaN
1  Sara  200.0
2   NaN  300.0

####Because pandas aligns by index, not position.

####Missing matches → NaN

##6. Handling Mismatched Columns (Row-wise)

In [35]:
df1 = pd.DataFrame({
    "Name": ["Ali"],
    "Sales": [200]
})

df2 = pd.DataFrame({
    "Name": ["Sara"],
    "Profit": [50]
})

result = pd.concat([df1, df2])
print(result)

   Name  Sales  Profit
0   Ali  200.0     NaN
0  Sara    NaN    50.0

####Pandas keeps all columns (outer join by default)
####Missing values → NaN

##7. join="inner" vs join="outer"
###Default → Outer Join

In [36]:
pd.concat([df1,df2], join ='outer')

   Name  Sales  Profit
0   Ali  200.0     NaN
0  Sara    NaN    50.0

####Keeps all columns "Outer"

In [37]:
pd.concat([df1,df2], join = 'inner')

   Name
0   Ali
0  Sara

####Keeps only common columns "Inner"

##8. keys=
###Purpose:

####Create a hierarchical index (MultiIndex)

In [40]:
result= pd.concat([df1, df2], keys= ["First", "Second"])
result

          Name  Sales  Profit
First  0   Ali  200.0     NaN
Second 0  Sara    NaN    50.0

#Topic 2: Merging (pd.merge)

###1. What is Merging?

####Merging combines datasets based on common columns (keys)

###Exactly like SQL JOIN:

####Combine Customer table + Orders table

####Combine Sales + Product info
###Basic Syntax
`pd.merge(left_df, right_df, on="column_name", how="type")`

###2. Dataset
###Customers Data

In [43]:
customers = pd.DataFrame({
    "customer_id": [1,2,3,4,5,6,7,8,9,10],
    "name": ["Ali","Sara","Ahmed","Zara","Usman","Ayesha","Bilal","Noor","Hamza","Hina"],
    "city": ["Lahore","Karachi","Islamabad","Lahore","Karachi","Islamabad","Lahore","Karachi","Islamabad","Lahore"]
})
customers

   customer_id    name       city
0            1     Ali     Lahore
1            2    Sara    Karachi
2            3   Ahmed  Islamabad
3            4    Zara     Lahore
4            5   Usman    Karachi
5            6  Ayesha  Islamabad
6            7   Bilal     Lahore
7            8    Noor    Karachi
8            9   Hamza  Islamabad
9           10    Hina     Lahore

Orders Data

In [44]:
orders = pd.DataFrame({
    "order_id": [101,102,103,104,105,106,107,108,109,110],
    "customer_id": [1,2,2,3,5,7,7,8,10,11],  # 11 does NOT exist in customers
    "amount": [500,700,300,400,900,200,150,800,1000,600]
})
orders

   order_id  customer_id  amount
0       101            1     500
1       102            2     700
2       103            2     300
3       104            3     400
4       105            5     900
5       106            7     200
6       107            7     150
7       108            8     800
8       109           10    1000
9       110           11     600

##3. on= Parameter
####Example (Inner Join by default)

In [51]:
result = pd.merge(customers, orders, on= 'customer_id')
result

   customer_id   name       city  order_id  amount
0            1    Ali     Lahore       101     500
1            2   Sara    Karachi       102     700
2            2   Sara    Karachi       103     300
3            3  Ahmed  Islamabad       104     400
4            5  Usman    Karachi       105     900
5            7  Bilal     Lahore       106     200
6            7  Bilal     Lahore       107     150
7            8   Noor    Karachi       108     800
8           10   Hina     Lahore       109    1000

##4. Types of Joins
###1. Inner Join
Keeps only common records

In [53]:
pd.merge(customers, orders, on= 'customer_id', how= 'inner')

   customer_id   name       city  order_id  amount
0            1    Ali     Lahore       101     500
1            2   Sara    Karachi       102     700
2            2   Sara    Karachi       103     300
3            3  Ahmed  Islamabad       104     400
4            5  Usman    Karachi       105     900
5            7  Bilal     Lahore       106     200
6            7  Bilal     Lahore       107     150
7            8   Noor    Karachi       108     800
8           10   Hina     Lahore       109    1000

###2. Left Join
####Keeps ALL customers
####Missing orders → NaN

In [54]:
pd.merge(customers, orders, on= 'customer_id', how= 'left')

    customer_id    name       city  order_id  amount
0             1     Ali     Lahore     101.0   500.0
1             2    Sara    Karachi     102.0   700.0
2             2    Sara    Karachi     103.0   300.0
3             3   Ahmed  Islamabad     104.0   400.0
4             4    Zara     Lahore       NaN     NaN
5             5   Usman    Karachi     105.0   900.0
6             6  Ayesha  Islamabad       NaN     NaN
7             7   Bilal     Lahore     106.0   200.0
8             7   Bilal     Lahore     107.0   150.0
9             8    Noor    Karachi     108.0   800.0
10            9   Hamza  Islamabad       NaN     NaN
11           10    Hina     Lahore     109.0  1000.0

##3. Right Join

####Keeps ALL orders
####Missing customers → NaN

In [55]:
pd.merge(customers, orders, on= 'customer_id', how= 'right')

   customer_id   name       city  order_id  amount
0            1    Ali     Lahore       101     500
1            2   Sara    Karachi       102     700
2            2   Sara    Karachi       103     300
3            3  Ahmed  Islamabad       104     400
4            5  Usman    Karachi       105     900
5            7  Bilal     Lahore       106     200
6            7  Bilal     Lahore       107     150
7            8   Noor    Karachi       108     800
8           10   Hina     Lahore       109    1000
9           11    NaN        NaN       110     600

###4. Outer Join

#### Keeps EVERYTHING
####Missing values on both sides

In [56]:
pd.merge(customers, orders, on= 'customer_id', how= 'outer')

    customer_id    name       city  order_id  amount
0             1     Ali     Lahore     101.0   500.0
1             2    Sara    Karachi     102.0   700.0
2             2    Sara    Karachi     103.0   300.0
3             3   Ahmed  Islamabad     104.0   400.0
4             4    Zara     Lahore       NaN     NaN
5             5   Usman    Karachi     105.0   900.0
6             6  Ayesha  Islamabad       NaN     NaN
7             7   Bilal     Lahore     106.0   200.0
8             7   Bilal     Lahore     107.0   150.0
9             8    Noor    Karachi     108.0   800.0
10            9   Hamza  Islamabad       NaN     NaN
11           10    Hina     Lahore     109.0  1000.0
12           11     NaN        NaN     110.0   600.0

 Join Type	Keeps

Inner	Common only

Left	All left + matches

Right	All right + matches

Outer	Everything

##5. left_on / right_on
####When column names differ

In [57]:
df1 = customers.rename(columns= {"customer_id": "cust_id"})
df1

   cust_id    name       city
0        1     Ali     Lahore
1        2    Sara    Karachi
2        3   Ahmed  Islamabad
3        4    Zara     Lahore
4        5   Usman    Karachi
5        6  Ayesha  Islamabad
6        7   Bilal     Lahore
7        8    Noor    Karachi
8        9   Hamza  Islamabad
9       10    Hina     Lahore

In [58]:
pd.merge(df1, orders, left_on= 'cust_id', right_on= 'customer_id', how= 'inner')

   cust_id   name       city  order_id  customer_id  amount
0        1    Ali     Lahore       101            1     500
1        2   Sara    Karachi       102            2     700
2        2   Sara    Karachi       103            2     300
3        3  Ahmed  Islamabad       104            3     400
4        5  Usman    Karachi       105            5     900
5        7  Bilal     Lahore       106            7     200
6        7  Bilal     Lahore       107            7     150
7        8   Noor    Karachi       108            8     800
8       10   Hina     Lahore       109           10    1000

Changed "cust_id" back to "customer_id"

In [59]:
customers = customers.rename(columns= {"cust_id": "customer_id"})
customers

   customer_id    name       city
0            1     Ali     Lahore
1            2    Sara    Karachi
2            3   Ahmed  Islamabad
3            4    Zara     Lahore
4            5   Usman    Karachi
5            6  Ayesha  Islamabad
6            7   Bilal     Lahore
7            8    Noor    Karachi
8            9   Hamza  Islamabad
9           10    Hina     Lahore

##6. Merging on Multiple Columns
`pd.merge(customers, orders, on = ['customer_id', 'city'], how= 'left')`

Both columns must match

##7. Handling Duplicate Keys
###Example

####Customer 2 appears twice in orders:

####customer_id = 2 → 2 orders

###Result:

####Data will duplicate rows


####This is called:

####One-to-many relationship

In [62]:
orders

   order_id  customer_id  amount
0       101            1     500
1       102            2     700
2       103            2     300
3       104            3     400
4       105            5     900
5       106            7     200
6       107            7     150
7       108            8     800
8       109           10    1000
9       110           11     600

##8. Many-to-One vs Many-to-Many
Type	Meaning

One-to-One	Unique keys in both

One-to-Many	One customer → many orders

Many-to-Many	Both sides have duplicates

##9. suffixes=
####When same column names exist
`suffixes=("_1", "_2")`

_1, _2 could be any names

In [66]:
df1 = pd.DataFrame({"id":[1,2], "value":[10,20]})
df2 = pd.DataFrame({"id":[1,2], "value":[100,200]})

pd.merge(df1, df2, on="id", suffixes=("_1", "_2"))

   id  value_1  value_2
0   1       10      100
1   2       20      200

##10. indicator=True
###Values:

####"left_only"

####"right_only"

####"both"

###Use case:

####Debug joins
####Find missing data
####Data validation

In [68]:
pd.merge(customers, orders, on= 'customer_id', how= 'left', indicator= True)

    customer_id    name       city  order_id  amount     _merge
0             1     Ali     Lahore     101.0   500.0       both
1             2    Sara    Karachi     102.0   700.0       both
2             2    Sara    Karachi     103.0   300.0       both
3             3   Ahmed  Islamabad     104.0   400.0       both
4             4    Zara     Lahore       NaN     NaN  left_only
5             5   Usman    Karachi     105.0   900.0       both
6             6  Ayesha  Islamabad       NaN     NaN  left_only
7             7   Bilal     Lahore     106.0   200.0       both
8             7   Bilal     Lahore     107.0   150.0       both
9             8    Noor    Karachi     108.0   800.0       both
10            9   Hamza  Islamabad       NaN     NaN  left_only
11           10    Hina     Lahore     109.0  1000.0       both

##11. validate=
###Options:
####Option Meaning



####1. one_to_one	-->no duplicates
####2. one_to_many -->	left unique
####3. many_to_one -->	right unique
####4. many_to_many -->	both duplicated
###It Prevents wrong joins silently

In [72]:
pd.merge(customers, orders, on= 'customer_id', validate= 'one_to_many')

   customer_id   name       city  order_id  amount
0            1    Ali     Lahore       101     500
1            2   Sara    Karachi       102     700
2            2   Sara    Karachi       103     300
3            3  Ahmed  Islamabad       104     400
4            5  Usman    Karachi       105     900
5            7  Bilal     Lahore       106     200
6            7  Bilal     Lahore       107     150
7            8   Noor    Karachi       108     800
8           10   Hina     Lahore       109    1000

#Topic 3: Join Method (df.join)

##1. What is join()?

####join() is a simpler way to combine DataFrames using their index

##Key idea:

####merge() → joins on columns

####join() → joins on index (by default)
###Basic Syntax
`df1.join(df2, how="left")`

##By default:

####Join happens on index

####Type = left join

##2. Dataset
####Customers (set index)

In [73]:
customers = pd.DataFrame({
    "customer_id": [1,2,3,4,5,6,7,8,9,10],
    "name": ["Ali","Sara","Ahmed","Zara","Usman","Ayesha","Bilal","Noor","Hamza","Hina"],
    "city": ["Lahore","Karachi","Islamabad","Lahore","Karachi","Islamabad","Lahore","Karachi","Islamabad","Lahore"]
}).set_index("customer_id")
customers

               name       city
customer_id
1               Ali     Lahore
2              Sara    Karachi
3             Ahmed  Islamabad
4              Zara     Lahore
5             Usman    Karachi
6            Ayesha  Islamabad
7             Bilal     Lahore
8              Noor    Karachi
9             Hamza  Islamabad
10             Hina     Lahore

###Orders (Set Index)

In [76]:
orders = pd.DataFrame({
    "customer_id": [1,2,2,3,5,7,7,8,10,11],
    "amount": [500,700,300,400,900,200,150,800,1000,600]
}).set_index("customer_id")
orders

             amount
customer_id
1               500
2               700
2               300
3               400
5               900
7               200
7               150
8               800
10             1000
11              600

##3. Joining on Index
####1. Matching happens using index (customer_id)

####2. Default = left join

####3. All customers are kept

####4. Missing matches → NaN

In [78]:
result= customers.join(orders)
result

               name       city  amount
customer_id
1               Ali     Lahore   500.0
2              Sara    Karachi   700.0
2              Sara    Karachi   300.0
3             Ahmed  Islamabad   400.0
4              Zara     Lahore     NaN
5             Usman    Karachi   900.0
6            Ayesha  Islamabad     NaN
7             Bilal     Lahore   200.0
7             Bilal     Lahore   150.0
8              Noor    Karachi   800.0
9             Hamza  Islamabad     NaN
10             Hina     Lahore  1000.0

###If index is not set correctly → join gives wrong result

####That’s why we used:

`.set_index("customer_id")`

##4. how= Parameter

####Same as merge(), but applied on index
###Left Join

In [79]:
left = customers.join(orders, how= 'left')
left

               name       city  amount
customer_id
1               Ali     Lahore   500.0
2              Sara    Karachi   700.0
2              Sara    Karachi   300.0
3             Ahmed  Islamabad   400.0
4              Zara     Lahore     NaN
5             Usman    Karachi   900.0
6            Ayesha  Islamabad     NaN
7             Bilal     Lahore   200.0
7             Bilal     Lahore   150.0
8              Noor    Karachi   800.0
9             Hamza  Islamabad     NaN
10             Hina     Lahore  1000.0

###"Inner

In [80]:
inner = customers.join(orders, how= 'inner')
inner

              name       city  amount
customer_id
1              Ali     Lahore     500
2             Sara    Karachi     700
2             Sara    Karachi     300
3            Ahmed  Islamabad     400
5            Usman    Karachi     900
7            Bilal     Lahore     200
7            Bilal     Lahore     150
8             Noor    Karachi     800
10            Hina     Lahore    1000

###Right Join

In [82]:
right=  customers.join(orders, how= 'right')
right

              name       city  amount
customer_id
1              Ali     Lahore     500
2             Sara    Karachi     700
2             Sara    Karachi     300
3            Ahmed  Islamabad     400
5            Usman    Karachi     900
7            Bilal     Lahore     200
7            Bilal     Lahore     150
8             Noor    Karachi     800
10            Hina     Lahore    1000
11             NaN        NaN     600

###Outer Join

In [83]:
outer= customers.join(orders, how="outer")
outer

               name       city  amount
customer_id
1               Ali     Lahore   500.0
2              Sara    Karachi   700.0
2              Sara    Karachi   300.0
3             Ahmed  Islamabad   400.0
4              Zara     Lahore     NaN
5             Usman    Karachi   900.0
6            Ayesha  Islamabad     NaN
7             Bilal     Lahore   200.0
7             Bilal     Lahore   150.0
8              Noor    Karachi   800.0
9             Hamza  Islamabad     NaN
10             Hina     Lahore  1000.0
11              NaN        NaN   600.0

##5. Joining Multiple DataFrames

In [84]:
orders2 = pd.DataFrame({
    "customer_id": [1,2,3,4,5],
    "discount": [10,20,15,5,25]
}).set_index("customer_id")
orders2

             discount
customer_id
1                  10
2                  20
3                  15
4                   5
5                  25

In [85]:
result = customers.join([orders, orders2])
result

               name       city  amount  discount
customer_id
1               Ali     Lahore   500.0      10.0
2              Sara    Karachi   700.0      20.0
2              Sara    Karachi   300.0      20.0
3             Ahmed  Islamabad   400.0      15.0
4              Zara     Lahore     NaN       5.0
5             Usman    Karachi   900.0      25.0
6            Ayesha  Islamabad     NaN       NaN
7             Bilal     Lahore   200.0       NaN
7             Bilal     Lahore   150.0       NaN
8              Noor    Karachi   800.0       NaN
9             Hamza  Islamabad     NaN       NaN
10             Hina     Lahore  1000.0       NaN

##6. Join on Column (Using on=)

 join() can also behave like merge

###Left DataFrame → column

###Right DataFrame → index

In [89]:
merge = customers.join(orders, on = 'customer_id', how= 'left')
merge

               name       city  amount
customer_id
1               Ali     Lahore   500.0
2              Sara    Karachi   700.0
2              Sara    Karachi   300.0
3             Ahmed  Islamabad   400.0
4              Zara     Lahore     NaN
5             Usman    Karachi   900.0
6            Ayesha  Islamabad     NaN
7             Bilal     Lahore   200.0
7             Bilal     Lahore   150.0
8              Noor    Karachi   800.0
9             Hamza  Islamabad     NaN
10             Hina     Lahore  1000.0

#Topic 4: Index Alignment Concept

##1. What is Index Alignment?

####Pandas automatically aligns data based on index labels whenever you perform:

####Arithmetic operations

####Concatenation / join / merge on index

####Combining multiple datasets



####“Pandas does not care about the position of data, it only cares about the index labels.”

##2. Alignment During Operations

In [90]:
s1 = pd.Series([100, 200, 300], index=["A", "B", "C"])
s2 = pd.Series([10, 20, 30], index=["B", "C", "D"])

result = s1 + s2
print(result)

A      NaN
B    210.0
C    320.0
D      NaN
dtype: float64

Why?

Index “A” exists only in s1 → result = NaN

Index “D” exists only in s2 → result = NaN

Index “B” & “C” → values are added

##3. Combining Mismatched Indexes

In [91]:
df1 = pd.DataFrame({"Sales": [100, 200, 300]}, index=["Jan","Feb","Mar"])
df2 = pd.DataFrame({"Sales": [400, 500, 600]}, index=["Feb","Mar","Apr"])

result = pd.concat([df1, df2], axis=1)
print(result)

     Sales  Sales
Jan  100.0    NaN
Feb  200.0  400.0
Mar  300.0  500.0
Apr    NaN  600.0

Observation:

Pandas matches rows by index

Unmatched indexes → NaN

##4. Real-World Example: Combining Multiple Monthly Reports

In [94]:
january = pd.DataFrame({"Revenue": [1000, 2000]}, index=["Product A","Product B"])
february = pd.DataFrame({"Revenue": [1500, 2500]}, index=["Product B","Product C"])

combined = pd.concat([january, february], axis=1)
combined

           Revenue  Revenue
Product A   1000.0      NaN
Product B   2000.0   1500.0
Product C      NaN   2500.0

In [95]:

combined.columns = ["Jan", "Feb"]
combined

              Jan     Feb
Product A  1000.0     NaN
Product B  2000.0  1500.0
Product C     NaN  2500.0

Pandas auto-aligned by product names

Missing months → NaN

##5. NaN Creation During Alignment

###Whenever you combine data:

####Any mismatch in index → NaN

####Must handle later using fillna() or dropna()

In [98]:
combined

              Jan     Feb
Product A  1000.0     NaN
Product B  2000.0  1500.0
Product C     NaN  2500.0

In [99]:
combined.fillna(0)

              Jan     Feb
Product A  1000.0     0.0
Product B  2000.0  1500.0
Product C     0.0  2500.0

In [100]:
combined.dropna()

              Jan     Feb
Product B  2000.0  1500.0

##Topic 5: Handling Keys & Indexes in Combining

##1. Why This Matters

####Most datasets don’t come “ready to join”

####Incorrect index/key handling → wrong merges, duplicate rows, NaNs

####Proper index handling is a hallmark of a professional analyst

####Remember: “A mismatch in index is the #1 cause of silent errors in combining datasets.”

##2. Setting Index Before Join (set_index)

In [101]:
customers = pd.DataFrame({
    "customer_id": [1,2,3,4,5],
    "name": ["Ali","Sara","Ahmed","Zara","Usman"],
    "city": ["Lahore","Karachi","Islamabad","Lahore","Karachi"]
})

orders = pd.DataFrame({
    "order_id": [101,102,103,104,105],
    "customer_id": [1,2,2,3,5],
    "amount": [500,700,300,400,900]
})
customers

   customer_id   name       city
0            1    Ali     Lahore
1            2   Sara    Karachi
2            3  Ahmed  Islamabad
3            4   Zara     Lahore
4            5  Usman    Karachi

In [102]:
orders

   order_id  customer_id  amount
0       101            1     500
1       102            2     700
2       103            2     300
3       104            3     400
4       105            5     900

###Setting index for join:

In [103]:
customer_index = customers.set_index("customer_id")
order_index = orders.set_index("customer_id")
result = customer_index.join(order_index)
result

              name       city  order_id  amount
customer_id
1              Ali     Lahore     101.0   500.0
2             Sara    Karachi     102.0   700.0
2             Sara    Karachi     103.0   300.0
3            Ahmed  Islamabad     104.0   400.0
4             Zara     Lahore       NaN     NaN
5            Usman    Karachi     105.0   900.0

Why set_index first?

join() works on index

Without set_index, join would fail or require on=

Ensures proper alignment and avoids duplicates errors

##3. Resetting Index (reset_index)

In [105]:
df = result.reset_index()
df

   customer_id   name       city  order_id  amount
0            1    Ali     Lahore     101.0   500.0
1            2   Sara    Karachi     102.0   700.0
2            2   Sara    Karachi     103.0   300.0
3            3  Ahmed  Islamabad     104.0   400.0
4            4   Zara     Lahore       NaN     NaN
5            5  Usman    Karachi     105.0   900.0

Why reset index?

Makes the index a regular column

Useful for:

Exporting CSV

Plotting

Further merges on columns

##4. Using Index as Join Key (on=)

####join() uses index by default

####You can also join on a column from left DataFrame

`customers_indexed.join(orders, on="customer_id")`
###Key Insight

####Left DataFrame column matched with right DataFrame index

####Useful when only one DataFrame is indexed

In [106]:
join = customer_index.join(orders, on= 'customer_id')
join

              name       city  order_id  customer_id  amount
customer_id
1              Ali     Lahore     102.0            1   700.0
2             Sara    Karachi     103.0            2   300.0
3            Ahmed  Islamabad     104.0            3   400.0
4             Zara     Lahore     105.0            4   900.0
5            Usman    Karachi       NaN            5     NaN

##5. MultiIndex Joining Basics
MultiIndex = hierarchical index (like keys + subkeys)

Useful for combining datasets with multiple identifiers

In [107]:
df1 = pd.DataFrame({
    "region": ["East","East","West","West"],
    "product": ["A","B","A","B"],
    "sales": [100,150,200,250]
}).set_index(["region","product"])

df2 = pd.DataFrame({
    "region": ["East","East","West","West"],
    "product": ["A","B","A","B"],
    "profit": [20,30,50,60]
}).set_index(["region","product"])

df1

                sales
region product
East   A          100
       B          150
West   A          200
       B          250

In [108]:
df2

                profit
region product
East   A            20
       B            30
West   A            50
       B            60

In [109]:
result = df1.join(df2)
result

                sales  profit
region product
East   A          100      20
       B          150      30
West   A          200      50
       B          250      60

Insight

MultiIndex join aligns both levels automatically

Prevents mismatches in hierarchical datasets (Region + Product, Month + Store, etc.)

1. Set index explicitly for join()

2. Reset index for further column-based operations or export

3. Use MultiIndex for hierarchical datasets