#Pandas Data Combining Practice

#Topic 1: Pandas Concatenation (pd.concat)

#Question 1
##Tasks:

####1. Concatenate row-wise

####2. Fix the index issue

In [1]:
import pandas as pd
df2 = pd.DataFrame({"Name": ["Ali", "Sara"],
       "Sales": [200, 300]})
df1 = pd.DataFrame({"Name": ["Ahmed", "Zara"],
       "Sales": [150, 400]})
df1

    Name  Sales
0  Ahmed    150
1   Zara    400

In [ ]:
df2

   Name  Sales
0   Ali    200
1  Sara    300

###1. Concatenate row-wise

In [ ]:
result = pd.concat([df1, df2], axis=0)
result

    Name  Sales
0  Ahmed    150
1   Zara    400
0    Ali    200
1   Sara    300

###2. Fix the index issue

In [ ]:
index= pd.concat([df1, df2], ignore_index=True)
index

    Name  Sales
0  Ahmed    150
1   Zara    400
2    Ali    200
3   Sara    300

##Question 2
###Tasks
####1. Concatenate column-wise (axis=1)
####2. Then fix the problem so that rows align correctly

In [ ]:
df1 = pd.DataFrame({"Name": ["Ali", "Sara"]}, index= [0, 1])
df2 = pd.DataFrame({"Sales": [200, 300]}, index= [1, 2])
df1

   Name
0   Ali
1  Sara

In [ ]:
df2

   Sales
1    200
2    300

###1. Concatenate column-wise (axis=1)

In [ ]:
result = pd.concat([df1, df2], axis= 1)
result

   Name  Sales
0   Ali    NaN
1  Sara  200.0
2   NaN  300.0

###2. Then fix the problem so that rows align correctly

In [ ]:
df1_index = df1.reset_index(drop=True)
df1_index

   Name
0   Ali
1  Sara

In [ ]:
df2_index = df2.reset_index(drop=True)
df2_index

   Sales
0    200
1    300

In [ ]:
result = pd.concat([df1_index, df2_index], axis = 1)
result

   Name  Sales
0   Ali    200
1  Sara    300

##Question 3
###Tasks:

####1. Concatenate row-wise
####2. Fill missing values with 0

In [ ]:
df1 = pd.DataFrame({"Name": ["Ali", "Sara"],
       "Sales": [200, 300]})
df2 = pd.DataFrame({"Name": ["Ahmed", "Zara"],
       "Profit": [150, 400]})
df1

   Name  Sales
0   Ali    200
1  Sara    300

In [ ]:
df2

    Name  Profit
0  Ahmed     150
1   Zara     400

###1. Concatenate row-wise

In [ ]:
result = pd.concat([df1, df2], axis= 0)
result

    Name  Sales  Profit
0    Ali  200.0     NaN
1   Sara  300.0     NaN
0  Ahmed    NaN   150.0
1   Zara    NaN   400.0

###2. Fill missing values with 0

In [ ]:
filled = result.fillna(0)
filled

    Name  Sales  Profit
0    Ali  200.0     0.0
1   Sara  300.0     0.0
0  Ahmed    0.0   150.0
1   Zara    0.0   400.0

##Question 4
###Tasks:

####1. Concatenate with join="outer"

####2. Concatenate with join="inner"

In [ ]:
df1 = pd.DataFrame({"A": [1,2,3], "B": [4,5,6]})
df2 = pd.DataFrame({"C": [11,12,13], "D": [14,15,16]})
df1

   A  B
0  1  4
1  2  5
2  3  6

In [ ]:
df2

    C   D
0  11  14
1  12  15
2  13  16


###1. Concatenate with join="outer"

In [ ]:
result1 = pd.concat([df1, df2], join= 'outer', ignore_index=True)
result1

     A    B     C     D
0  1.0  4.0   NaN   NaN
1  2.0  5.0   NaN   NaN
2  3.0  6.0   NaN   NaN
3  NaN  NaN  11.0  14.0
4  NaN  NaN  12.0  15.0
5  NaN  NaN  13.0  16.0

###2. Concatenate with join="inner"

In [ ]:
result2 = pd.concat([df1, df2], join = 'inner', ignore_index=True)
result2

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5]

##Question 5

###Create two small DataFrames (same structure)

###Tasks:

####1. Concatenate using keys=["Jan", "Feb"]

####2. Access only “Jan” data

In [ ]:
df1 = pd.DataFrame({"Name": ["Ali", "Sara"],
       "Sales": [200, 300]})
df2 = pd.DataFrame({"Name": ["Ahmed", "Zara"],
       "Sales": [150, 400]})
df1

   Name  Sales
0   Ali    200
1  Sara    300

In [ ]:
df2

    Name  Sales
0  Ahmed    150
1   Zara    400

###1. Concatenate using keys=["Jan", "Feb"]

In [ ]:
result = pd.concat([df1, df2], keys= ['Jan', 'Feb'])
result

        Name  Sales
Jan 0    Ali    200
    1   Sara    300
Feb 0  Ahmed    150
    1   Zara    400

###2. Access only “Jan” data

In [ ]:
result.loc["Jan"]

   Name  Sales
0   Ali    200
1  Sara    300

##Question 6
###Tasks:

####1. Combine both datasets

####2. Add a column showing month manually

####3. Then solve the same problem using keys= instead

In [ ]:
jan_sales = pd.DataFrame({
    "Product": ["A", "B"],
    "Sales": [100, 200]
})

feb_sales = pd.DataFrame({
    "Product": ["A", "B"],
    "Sales": [150, 250]
})
jan_sales

  Product  Sales
0       A    100
1       B    200

In [ ]:
feb_sales

  Product  Sales
0       A    150
1       B    250

####1. Combine Both Datasets

In [ ]:
result = pd.concat([jan_sales, feb_sales], ignore_index=True)
result

  Product  Sales
0       A    100
1       B    200
2       A    150
3       B    250

####2. Add a column showing month manually

In [ ]:
jan_sales['Month']= 'Jan'
feb_sales['Month']= 'Feb'
result2 = pd.concat([jan_sales,feb_sales], ignore_index=True)
result2

  Product  Sales Month
0       A    100   Jan
1       B    200   Jan
2       A    150   Feb
3       B    250   Feb

####3. Then solve the same problem using keys= instead

In [ ]:
result_key = pd.concat([jan_sales, feb_sales], keys=['Jan', 'Feb'])
result_key

      Product  Sales Month
Jan 0       A    100   Jan
    1       B    200   Jan
Feb 0       A    150   Feb
    1       B    250   Feb

##Question 7
###Tasks:

####1. Concatenate with axis=1

####2. Then change index of df2 to [1,2] and run again

In [ ]:
df1 = pd.DataFrame({"A": [10, 20]}, index= [0,1])
df2 = pd.DataFrame({"B": [30, 40]}, index= [0,1])

####1. Concatenate with axis=1

In [ ]:
result= pd.concat([df1, df2], axis=1)
result

    A   B
0  10  30
1  20  40


####2. Then change index of df2 to [1,2] and run again

In [ ]:
df2.index = [1,2]
result2 = pd.concat([df1, df2], axis=1).fillna(0)
result2

      A     B
0  10.0   0.0
1  20.0  30.0
2   0.0  40.0

#Topic 2: Merging (pd.merge)

In [ ]:
customers = pd.DataFrame({
    "customer_id": [1,2,3,4,5,6,7,8,9,10],
    "name": ["Ali","Sara","Ahmed","Zara","Usman","Ayesha","Bilal","Noor","Hamza","Hina"],
    "city": ["Lahore","Karachi","Islamabad","Lahore","Karachi","Islamabad","Lahore","Karachi","Islamabad","Lahore"]
})

orders = pd.DataFrame({
    "order_id": [101,102,103,104,105,106,107,108,109,110],
    "customer_id": [1,2,2,3,5,7,7,8,10,11],  # 11 does NOT exist in customers
    "amount": [500,700,300,400,900,200,150,800,1000,600]
})

customers, orders

(   customer_id    name       city
 0            1     Ali     Lahore
 1            2    Sara    Karachi
 2            3   Ahmed  Islamabad
 3            4    Zara     Lahore
 4            5   Usman    Karachi
 5            6  Ayesha  Islamabad
 6            7   Bilal     Lahore
 7            8    Noor    Karachi
 8            9   Hamza  Islamabad
 9           10    Hina     Lahore,
    order_id  customer_id  amount
 0       101            1     500
 1       102            2     700
 2       103            2     300
 3       104            3     400
 4       105            5     900
 5       106            7     200
 6       107            7     150
 7       108            8     800
 8       109           10    1000
 9       110           11     600)

##Question 1

Merge customers and orders on customer_id (inner join by default)

Print the result

In [ ]:
pd.merge(customers, orders)

   customer_id   name       city  order_id  amount
0            1    Ali     Lahore       101     500
1            2   Sara    Karachi       102     700
2            2   Sara    Karachi       103     300
3            3  Ahmed  Islamabad       104     400
4            5  Usman    Karachi       105     900
5            7  Bilal     Lahore       106     200
6            7  Bilal     Lahore       107     150
7            8   Noor    Karachi       108     800
8           10   Hina     Lahore       109    1000

##Question 2 — Different Join Types

####1. Merge using how="left" → keep all customers

In [ ]:
pd.merge(customers, orders, how= 'left')

    customer_id    name       city  order_id  amount
0             1     Ali     Lahore     101.0   500.0
1             2    Sara    Karachi     102.0   700.0
2             2    Sara    Karachi     103.0   300.0
3             3   Ahmed  Islamabad     104.0   400.0
4             4    Zara     Lahore       NaN     NaN
5             5   Usman    Karachi     105.0   900.0
6             6  Ayesha  Islamabad       NaN     NaN
7             7   Bilal     Lahore     106.0   200.0
8             7   Bilal     Lahore     107.0   150.0
9             8    Noor    Karachi     108.0   800.0
10            9   Hamza  Islamabad       NaN     NaN
11           10    Hina     Lahore     109.0  1000.0

####2. Merge using how="right" → keep all orders

In [ ]:
pd.merge(customers, orders, how= 'right')

   customer_id   name       city  order_id  amount
0            1    Ali     Lahore       101     500
1            2   Sara    Karachi       102     700
2            2   Sara    Karachi       103     300
3            3  Ahmed  Islamabad       104     400
4            5  Usman    Karachi       105     900
5            7  Bilal     Lahore       106     200
6            7  Bilal     Lahore       107     150
7            8   Noor    Karachi       108     800
8           10   Hina     Lahore       109    1000
9           11    NaN        NaN       110     600

####3. Merge using how="outer" → keep everything

In [ ]:
pd.merge(customers, orders, how= 'outer')

    customer_id    name       city  order_id  amount
0             1     Ali     Lahore     101.0   500.0
1             2    Sara    Karachi     102.0   700.0
2             2    Sara    Karachi     103.0   300.0
3             3   Ahmed  Islamabad     104.0   400.0
4             4    Zara     Lahore       NaN     NaN
5             5   Usman    Karachi     105.0   900.0
6             6  Ayesha  Islamabad       NaN     NaN
7             7   Bilal     Lahore     106.0   200.0
8             7   Bilal     Lahore     107.0   150.0
9             8    Noor    Karachi     108.0   800.0
10            9   Hamza  Islamabad       NaN     NaN
11           10    Hina     Lahore     109.0  1000.0
12           11     NaN        NaN     110.0   600.0

#Question 3 — Merge with Different Column Names

####1. Rename customer_id in customers → cust_id

In [ ]:
customers= customers.rename(columns={'customer_id': 'cust_id'})
customers

   cust_id    name       city
0        1     Ali     Lahore
1        2    Sara    Karachi
2        3   Ahmed  Islamabad
3        4    Zara     Lahore
4        5   Usman    Karachi
5        6  Ayesha  Islamabad
6        7   Bilal     Lahore
7        8    Noor    Karachi
8        9   Hamza  Islamabad
9       10    Hina     Lahore

####2. Now Merge with orders

In [ ]:
pd.merge(customers, orders, left_on='cust_id', right_on = 'customer_id')

   cust_id   name       city  order_id  customer_id  amount
0        1    Ali     Lahore       101            1     500
1        2   Sara    Karachi       102            2     700
2        2   Sara    Karachi       103            2     300
3        3  Ahmed  Islamabad       104            3     400
4        5  Usman    Karachi       105            5     900
5        7  Bilal     Lahore       106            7     200
6        7  Bilal     Lahore       107            7     150
7        8   Noor    Karachi       108            8     800
8       10   Hina     Lahore       109           10    1000

####Change cust_id back to customer_id

In [ ]:
customers= customers.rename(columns={'cust_id': 'customer_id' })

##Question 4 — Merge on Multiple Columns

####1. Merge customers and orders on "customer_id","city"
`pd.merge(customers, orders, on= ['customer_id', 'city'])`
That's how you can merge using multiple columns but both DataFrames must have same columns

##

##Question 5 — Using suffixes=

####1. Create a new DataFrame df_extra:

In [ ]:
df_extra = pd.DataFrame({
    "customer_id": [1,2,3],
    "name": ["Ali K.","Sara B.","Ahmed T."],
    "discount": [10,15,20]})
df_extra

   customer_id      name  discount
0            1    Ali K.        10
1            2   Sara B.        15
2            3  Ahmed T.        20

####2. Merge customers and df_extra on customer_id

In [ ]:
pd.merge(customers, df_extra, on= 'customer_id')

   customer_id name_x       city    name_y  discount
0            1    Ali     Lahore    Ali K.        10
1            2   Sara    Karachi   Sara B.        15
2            3  Ahmed  Islamabad  Ahmed T.        20

####3. Use suffixes

In [ ]:
pd.merge(customers, df_extra, on= 'customer_id', suffixes= ("_cust", "_extra"))

   customer_id name_cust       city name_extra  discount
0            1       Ali     Lahore     Ali K.        10
1            2      Sara    Karachi    Sara B.        15
2            3     Ahmed  Islamabad   Ahmed T.        20

##Question 6 — Using indicator=True

####Merge customers and orders with how="outer", indicator=True

In [ ]:
merged= pd.merge(customers, orders, on = 'customer_id', how= 'outer', indicator= True)
merged

    customer_id    name       city  order_id  amount      _merge
0             1     Ali     Lahore     101.0   500.0        both
1             2    Sara    Karachi     102.0   700.0        both
2             2    Sara    Karachi     103.0   300.0        both
3             3   Ahmed  Islamabad     104.0   400.0        both
4             4    Zara     Lahore       NaN     NaN   left_only
5             5   Usman    Karachi     105.0   900.0        both
6             6  Ayesha  Islamabad       NaN     NaN   left_only
7             7   Bilal     Lahore     106.0   200.0        both
8             7   Bilal     Lahore     107.0   150.0        both
9             8    Noor    Karachi     108.0   800.0        both
10            9   Hamza  Islamabad       NaN     NaN   left_only
11           10    Hina     Lahore     109.0  1000.0        both
12           11     NaN        NaN     110.0   600.0  right_only

####2. Count how many rows are "left_only", "right_only", "both" give me solution of this

In [ ]:
merged['_merge'].value_counts()

_merge
both          9
left_only     3
right_only    1
Name: count, dtype: int64

##Question 7 — Using validate=

####1. Merge customers and orders with validate=

In [ ]:
pd.merge(customers, orders, validate= 'one_to_many')

   customer_id   name       city  order_id  amount
0            1    Ali     Lahore       101     500
1            2   Sara    Karachi       102     700
2            2   Sara    Karachi       103     300
3            3  Ahmed  Islamabad       104     400
4            5  Usman    Karachi       105     900
5            7  Bilal     Lahore       106     200
6            7  Bilal     Lahore       107     150
7            8   Noor    Karachi       108     800
8           10   Hina     Lahore       109    1000

####2. Try changing validate="one_to_one" → observe error

In [ ]:
#pd.merge(customers, orders, validate= 'one_to_one')
'''
Arise in error:
MergeError: Merge keys are not unique in right dataset; not a one-to-one merge
'''

'\nArise in error:\nMergeError: Merge keys are not unique in right dataset; not a one-to-one merge\n'

###Why validate is critical

####Ensures your assumptions about key uniqueness are correct

####Prevents silent data duplication

###Real-World Importance

####Many datasets claim "unique customer IDs"

####If you assume one-to-one but dataset has duplicates → pandas silently duplicates rows

####Using validate will raise an error immediately, avoiding wrong analysis

###Options
| Option | Meaning |
|--------|---------|
| one_to_one | Both left and right keys unique |
| one_to_many | Left unique, right may duplicate |
| many_to_one | Left may duplicate, right unique |
| many_to_many | Both may duplicate |

#Topic 3: Join Method:

In [11]:
customers = pd.DataFrame({
    "customer_id": [1,2,3,4,5,6,7,8,9,10],
    "name": ["Ali","Sara","Ahmed","Zara","Usman","Ayesha","Bilal","Noor","Hamza","Hina"],
    "city": ["Lahore","Karachi","Islamabad","Lahore","Karachi","Islamabad","Lahore","Karachi","Islamabad","Lahore"]
}).set_index("customer_id")

orders = pd.DataFrame({
    "customer_id": [1,2,2,3,5,7,7,8,10,11],
    "amount": [500,700,300,400,900,200,150,800,1000,600]
}).set_index("customer_id")

orders2 = pd.DataFrame({
    "customer_id": [1,2,3,4,5],
    "discount": [10,20,15,5,25]
}).set_index("customer_id")
customers, orders, orders2

(               name       city
 customer_id
 1               Ali     Lahore
 2              Sara    Karachi
 3             Ahmed  Islamabad
 4              Zara     Lahore
 5             Usman    Karachi
 6            Ayesha  Islamabad
 7             Bilal     Lahore
 8              Noor    Karachi
 9             Hamza  Islamabad
 10             Hina     Lahore,
              amount
 customer_id
 1               500
 2               700
 2               300
 3               400
 5               900
 7               200
 7               150
 8               800
 10             1000
 11              600,
              discount
 customer_id
 1                  10
 2                  20
 3                  15
 4                   5
 5                  25)

##Question 1:
##Tasks:
###Identify join type
`joinied = customers.join(orders)`

In [12]:
joined = customers.join(orders)
joined

               name       city  amount
customer_id
1               Ali     Lahore   500.0
2              Sara    Karachi   700.0
2              Sara    Karachi   300.0
3             Ahmed  Islamabad   400.0
4              Zara     Lahore     NaN
5             Usman    Karachi   900.0
6            Ayesha  Islamabad     NaN
7             Bilal     Lahore   200.0
7             Bilal     Lahore   150.0
8              Noor    Karachi   800.0
9             Hamza  Islamabad     NaN
10             Hina     Lahore  1000.0

###Left Join

##Question 2
####Write code to:

####Perform INNER join using join()
####Store result in result2

In [13]:
result2 = customers.join(orders, how='inner')
result2

              name       city  amount
customer_id
1              Ali     Lahore     500
2             Sara    Karachi     700
2             Sara    Karachi     300
3            Ahmed  Islamabad     400
5            Usman    Karachi     900
7            Bilal     Lahore     200
7            Bilal     Lahore     150
8             Noor    Karachi     800
10            Hina     Lahore    1000

##Question 3

####Write code to:

####Perform FULL OUTER join using join()
####Store result in result4

In [14]:
result4 = customers.join(orders)
result4

               name       city  amount
customer_id
1               Ali     Lahore   500.0
2              Sara    Karachi   700.0
2              Sara    Karachi   300.0
3             Ahmed  Islamabad   400.0
4              Zara     Lahore     NaN
5             Usman    Karachi   900.0
6            Ayesha  Islamabad     NaN
7             Bilal     Lahore   200.0
7             Bilal     Lahore   150.0
8              Noor    Karachi   800.0
9             Hamza  Islamabad     NaN
10             Hina     Lahore  1000.0

##Question 4

Do this:

####Reset index of both DataFrames
####Try joining them
You will get WRONG result

In [15]:
customers_index = customers.reset_index()
customers_index

   customer_id    name       city
0            1     Ali     Lahore
1            2    Sara    Karachi
2            3   Ahmed  Islamabad
3            4    Zara     Lahore
4            5   Usman    Karachi
5            6  Ayesha  Islamabad
6            7   Bilal     Lahore
7            8    Noor    Karachi
8            9   Hamza  Islamabad
9           10    Hina     Lahore

In [16]:
orders_index = orders.reset_index()
orders_index

   customer_id  amount
0            1     500
1            2     700
2            2     300
3            3     400
4            5     900
5            7     200
6            7     150
7            8     800
8           10    1000
9           11     600

In [18]:
joining = customers_index.join(orders_index)
joining

ValueError: columns overlap but no suffix specified: Index(['customer_id'], dtype='object')

In [22]:
customers = customers_index.set_index("customer_id")
orders = orders_index.set_index("customer_id")

In [23]:
correct_result = customers.join(orders)
correct_result

               name       city  amount
customer_id
1               Ali     Lahore   500.0
2              Sara    Karachi   700.0
2              Sara    Karachi   300.0
3             Ahmed  Islamabad   400.0
4              Zara     Lahore     NaN
5             Usman    Karachi   900.0
6            Ayesha  Islamabad     NaN
7             Bilal     Lahore   200.0
7             Bilal     Lahore   150.0
8              Noor    Karachi   800.0
9             Hamza  Islamabad     NaN
10             Hina     Lahore  1000.0

##Question 5:
####Write code to:

####Use join() to join customers_reset with orders
####Use customer_id as key

In [24]:
result3 = customers_index.join(orders, on = 'customer_id')
result3

   customer_id    name       city  amount
0            1     Ali     Lahore   500.0
1            2    Sara    Karachi   700.0
1            2    Sara    Karachi   300.0
2            3   Ahmed  Islamabad   400.0
3            4    Zara     Lahore     NaN
4            5   Usman    Karachi   900.0
5            6  Ayesha  Islamabad     NaN
6            7   Bilal     Lahore   200.0
6            7   Bilal     Lahore   150.0
7            8    Noor    Karachi   800.0
8            9   Hamza  Islamabad     NaN
9           10    Hina     Lahore  1000.0

##Question 6

####Write code to:

####Join customers with BOTH:
####orders
####orders2

In [25]:
customers.join([orders, orders2])

               name       city  amount  discount
customer_id
1               Ali     Lahore   500.0      10.0
2              Sara    Karachi   700.0      20.0
2              Sara    Karachi   300.0      20.0
3             Ahmed  Islamabad   400.0      15.0
4              Zara     Lahore     NaN       5.0
5             Usman    Karachi   900.0      25.0
6            Ayesha  Islamabad     NaN       NaN
7             Bilal     Lahore   200.0       NaN
7             Bilal     Lahore   150.0       NaN
8              Noor    Karachi   800.0       NaN
9             Hamza  Islamabad     NaN       NaN
10             Hina     Lahore  1000.0       NaN

##Question 7

####Write code to:

####Extract rows where customer_id = 2
####Count how many rows exist after join

In [27]:
result5 = customers.join(orders)
result5

               name       city  amount
customer_id
1               Ali     Lahore   500.0
2              Sara    Karachi   700.0
2              Sara    Karachi   300.0
3             Ahmed  Islamabad   400.0
4              Zara     Lahore     NaN
5             Usman    Karachi   900.0
6            Ayesha  Islamabad     NaN
7             Bilal     Lahore   200.0
7             Bilal     Lahore   150.0
8              Noor    Karachi   800.0
9             Hamza  Islamabad     NaN
10             Hina     Lahore  1000.0

In [30]:
customer_2 = result5.loc[2]
customer_2

             name     city  amount
customer_id
2            Sara  Karachi   700.0
2            Sara  Karachi   300.0

In [36]:
customer_2.shape[0]

2

##Question 8


####Write code to:

####Find customers with NO orders

In [37]:
no_orders = customers.join(orders, how = 'outer')
no_orders

               name       city  amount
customer_id
1               Ali     Lahore   500.0
2              Sara    Karachi   700.0
2              Sara    Karachi   300.0
3             Ahmed  Islamabad   400.0
4              Zara     Lahore     NaN
5             Usman    Karachi   900.0
6            Ayesha  Islamabad     NaN
7             Bilal     Lahore   200.0
7             Bilal     Lahore   150.0
8              Noor    Karachi   800.0
9             Hamza  Islamabad     NaN
10             Hina     Lahore  1000.0
11              NaN        NaN   600.0

In [47]:
no_orders[no_orders['amount'].isna()]

               name       city  amount
customer_id
4              Zara     Lahore     NaN
6            Ayesha  Islamabad     NaN
9             Hamza  Islamabad     NaN

##Question 10
####Write code to:
####Find orders that have NO matching customer (customer_id = 11 case)

In [50]:
result = customers.join(orders, how="right")
result

              name       city  amount
customer_id
1              Ali     Lahore     500
2             Sara    Karachi     700
2             Sara    Karachi     300
3            Ahmed  Islamabad     400
5            Usman    Karachi     900
7            Bilal     Lahore     200
7            Bilal     Lahore     150
8             Noor    Karachi     800
10            Hina     Lahore    1000
11             NaN        NaN     600

In [51]:
no_customer = result[result['name'].isna()]
no_customer

            name city  amount
customer_id
11           NaN  NaN     600