#Pandas Working with Files

#Working with Files

## Notebook Overview:

This notebook covers **professional file handling with Pandas**, including:

1. **Reading / Loading Files**
   - CSV, Excel, JSON
   - Handling headers, indexes, missing values, data types, and dates
   - Reading large files efficiently

2. **Writing / Exporting Files**
   - CSV, Excel, JSON
   - Handling indexes, missing values, separators
   - Writing multiple sheets and pretty JSON

3. **Best Practices**
   - File paths, encoding, error handling
   - Using chunksize for large datasets
   - Professional tips for reproducible data pipelines

#Upload the ZIP file to Colab

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving archive.zip to archive.zip

#Check the contents of the ZIP

In [ ]:
import zipfile

zip_path = "archive.zip"  # replace with your uploaded file name

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    print(zip_ref.namelist())

['tested.csv']

#Read test.csv directly from ZIP

In [ ]:
import pandas as pd

csv_file = "tested.csv"

with zipfile.ZipFile(zip_path) as z:
    with z.open(csv_file) as f:
        df = pd.read_csv(f)

# Check first 5 rows
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving tested[1].csv to tested[1].csv

In [ ]:
import pandas as pd

import os

os.rename("tested[1].csv", "tested.csv")
df = pd.read_csv("tested.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

#1. Working with CSV Files in Pandas

##1. pd.read_csv() Basics

###Purpose: Load a CSV file into a Pandas DataFrame.

In [ ]:
df =pd.read_csv('tested.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Survived     418 non-null    int64
 2   Pclass       418 non-null    int64
 3   Name         418 non-null    object
 4   Sex          418 non-null    object
 5   Age          332 non-null    float64
 6   SibSp        418 non-null    int64
 7   Parch        418 non-null    int64
 8   Ticket       418 non-null    object
 9   Fare         417 non-null    float64
 10  Cabin        91 non-null     object
 11  Embarked     418 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 39.3+ KB

##2. Handling Headers (header and names)

####Scenario 1: CSV has column headers in the first row (default)

In [ ]:
df =pd.read_csv('tested.csv', header=0)
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

####Scenario 2: CSV has no headers, you provide column names

In [ ]:
df = pd.read_csv('tested.csv', header=None)
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11
0,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
2,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47,1,0,363272,7,NaN,S
3,894,0,2,"Myles, Mr. Thomas Francis",male,62,0,0,240276,9.6875,NaN,Q
4,895,0,3,"Wirz, Mr. Albert",male,27,0,0,315154,8.6625,NaN,S

In [ ]:
df = pd.read_csv('tested.csv', header=None,
                 names=["PassengerId", "Pclass", "Name", "Sex", "Age", "SibSp", "Parch", "Ticket", "Fare", "Cabin", "Embarked"])
df.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47,1,0,363272,7,NaN,S
894,0,2,"Myles, Mr. Thomas Francis",male,62,0,0,240276,9.6875,NaN,Q
895,0,3,"Wirz, Mr. Albert",male,27,0,0,315154,8.6625,NaN,S

In [ ]:
df = pd.read_csv('tested.csv', header=0)
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

##3. Index Column (index_col)
####Purpose: Set a column as the index of the DataFrame for easier selection and merging.

In [ ]:
df = pd.read_csv('tested.csv', index_col='PassengerId')
df.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

##4. Skipping Rows (skiprows)
####Purpose: Skip unnecessary rows, e.g., metadata or comments at the start.

In [ ]:
df = pd.read_csv('tested.csv', skiprows= 2)
df.head()

,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47,1.1,0,363272,7,Unnamed: 10,S
0,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
1,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
2,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
3,897,0,3,"Svensson, Mr. Johan Cervin",male,14.0,0,0,7538,9.2250,NaN,S
4,898,1,3,"Connolly, Miss. Kate",female,30.0,0,0,330972,7.6292,NaN,Q

In [ ]:
df =pd.read_csv('tested.csv', skiprows=[1,2,5])
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
1,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
2,897,0,3,"Svensson, Mr. Johan Cervin",male,14.0,0,0,7538,9.2250,NaN,S
3,898,1,3,"Connolly, Miss. Kate",female,30.0,0,0,330972,7.6292,NaN,Q
4,899,0,2,"Caldwell, Mr. Albert Francis",male,26.0,1,1,248738,29.0000,NaN,S

##5. Handling Missing Values (na_values)
####Purpose: Convert custom markers to NaN for consistency.

In [ ]:
df = pd.read_csv('tested.csv', na_values= ['NA', 'n/a','-',''])
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

####Now "NA", "n/a", "-" and empty strings are treated as NaN

In [ ]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

##6. Specifying Data Types (dtype)
####Pandas guesses types by default — sometimes incorrectly, especially for IDs or categorical columns.

In [ ]:
df = pd.read_csv("tested.csv", dtype ={
      'PassengerId' : str,
      'Pclass' : int,
      'Age' : float,
      'Fare' : float
})
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    object
 1   Survived     418 non-null    int64
 2   Pclass       418 non-null    int64
 3   Name         418 non-null    object
 4   Sex          418 non-null    object
 5   Age          332 non-null    float64
 6   SibSp        418 non-null    int64
 7   Parch        418 non-null    int64
 8   Ticket       418 non-null    object
 9   Fare         417 non-null    float64
 10  Cabin        91 non-null     object
 11  Embarked     418 non-null    object
dtypes: float64(2), int64(4), object(6)
memory usage: 39.3+ KB

##7. Parsing Dates (parse_dates)
####Convert string columns to datetime for analysis.
`df = pd.read_csv('tested.csv', parse_dates=['DateOfBirth'])`

`df.head()`
####Combine multiple columns into one date:
`df = pd.read_csv("tested.csv", parse_dates=[["Year", "Month", "Day"]])`
####Use infer_datetime_format=True to speed up parsing:
`df = pd.read_csv("tested.csv", parse_dates=["DateOfBirth"], infer_datetime_format=True)`

##8. Handling Large Files (chunksize)
####Useful when CSV is too big to fit in memory.
`chunk_iter = pd.read_csv("large_file.csv", chunksize=100000) `

`for chunk in chunk_iter:`

    `process(chunk)`

#2. Working with Excel Files in Pandas
####1. Excel files (.xlsx, .xls) are very common in business and analytics.
####2. Pandas allows you to read, analyze, and write Excel files professionally, similar to CSVs but with extra features like multiple sheets.

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving Sample_-_Superstore_Sales_(Excel)[1].xlsx to Sample_-_Superstore_Sales_(Excel)[1].xlsx

In [ ]:
df = pd.read_excel("Sample_-_Superstore_Sales_(Excel)[1].xlsx")
df.head()

,Row ID,Order ID,Order Date,Order Priority,Order Quantity,Sales,Discount,Ship Mode,Profit,Unit Price,...,Zip Code,State,Region,Customer Segment,Product Category,Product Sub-Category,Product Name,Product Container,Product Base Margin,Ship Date
0,1,3,2010-10-13,Low,6,261.5400,0.04,Regular Air,-213.250,38.94,...,60035,Illinois,Central,Small Business,Office Supplies,Storage & Organization,"Eldon Base for stackable storage shelf, platinum",Large Box,0.80,2010-10-20
1,2,6,2012-02-20,Not Specified,2,6.9300,0.01,Regular Air,-4.640,2.08,...,98026,Washington,West,Corporate,Office Supplies,"Scissors, Rulers and Trimmers",Kleencut® Forged Office Shears by Acme United ...,Small Pack,0.55,2012-02-21
2,3,32,2011-07-15,High,26,2808.0800,0.07,Regular Air,1054.820,107.53,...,98387,Washington,West,Corporate,Furniture,Office Furnishings,Tenex Contemporary Contur Chairmats for Low an...,Medium Box,0.65,2011-07-17
3,4,32,2011-07-15,High,24,1761.4000,0.09,Delivery Truck,-1748.560,70.89,...,98387,Washington,West,Corporate,Furniture,Tables,KI Conference Tables,Jumbo Box,0.72,2011-07-16
4,5,32,2011-07-15,High,23,160.2335,0.04,Regular Air,-85.129,7.99,...,98387,Washington,West,Corporate,Technology,Telephones and Communication,Bell Sonecor JB700 Caller ID,Medium Box,0.60,2011-07-17

##Rename File

In [ ]:
os.rename("Sample_-_Superstore_Sales_(Excel)[1].xlsx", "Sales.xlsx")
df = pd.read_excel("Sales.xlsx")
df.head()

,Row ID,Order ID,Order Date,Order Priority,Order Quantity,Sales,Discount,Ship Mode,Profit,Unit Price,...,Zip Code,State,Region,Customer Segment,Product Category,Product Sub-Category,Product Name,Product Container,Product Base Margin,Ship Date
0,1,3,2010-10-13,Low,6,261.5400,0.04,Regular Air,-213.250,38.94,...,60035,Illinois,Central,Small Business,Office Supplies,Storage & Organization,"Eldon Base for stackable storage shelf, platinum",Large Box,0.80,2010-10-20
1,2,6,2012-02-20,Not Specified,2,6.9300,0.01,Regular Air,-4.640,2.08,...,98026,Washington,West,Corporate,Office Supplies,"Scissors, Rulers and Trimmers",Kleencut® Forged Office Shears by Acme United ...,Small Pack,0.55,2012-02-21
2,3,32,2011-07-15,High,26,2808.0800,0.07,Regular Air,1054.820,107.53,...,98387,Washington,West,Corporate,Furniture,Office Furnishings,Tenex Contemporary Contur Chairmats for Low an...,Medium Box,0.65,2011-07-17
3,4,32,2011-07-15,High,24,1761.4000,0.09,Delivery Truck,-1748.560,70.89,...,98387,Washington,West,Corporate,Furniture,Tables,KI Conference Tables,Jumbo Box,0.72,2011-07-16
4,5,32,2011-07-15,High,23,160.2335,0.04,Regular Air,-85.129,7.99,...,98387,Washington,West,Corporate,Technology,Telephones and Communication,Bell Sonecor JB700 Caller ID,Medium Box,0.60,2011-07-17

##1. pd.read_excel() Basics

####Purpose: Load an Excel file into a Pandas DataFrame.

In [ ]:
df = pd.read_excel('Sales.xlsx')
df.head()

,Row ID,Order ID,Order Date,Order Priority,Order Quantity,Sales,Discount,Ship Mode,Profit,Unit Price,...,Zip Code,State,Region,Customer Segment,Product Category,Product Sub-Category,Product Name,Product Container,Product Base Margin,Ship Date
0,1,3,2010-10-13,Low,6,261.5400,0.04,Regular Air,-213.250,38.94,...,60035,Illinois,Central,Small Business,Office Supplies,Storage & Organization,"Eldon Base for stackable storage shelf, platinum",Large Box,0.80,2010-10-20
1,2,6,2012-02-20,Not Specified,2,6.9300,0.01,Regular Air,-4.640,2.08,...,98026,Washington,West,Corporate,Office Supplies,"Scissors, Rulers and Trimmers",Kleencut® Forged Office Shears by Acme United ...,Small Pack,0.55,2012-02-21
2,3,32,2011-07-15,High,26,2808.0800,0.07,Regular Air,1054.820,107.53,...,98387,Washington,West,Corporate,Furniture,Office Furnishings,Tenex Contemporary Contur Chairmats for Low an...,Medium Box,0.65,2011-07-17
3,4,32,2011-07-15,High,24,1761.4000,0.09,Delivery Truck,-1748.560,70.89,...,98387,Washington,West,Corporate,Furniture,Tables,KI Conference Tables,Jumbo Box,0.72,2011-07-16
4,5,32,2011-07-15,High,23,160.2335,0.04,Regular Air,-85.129,7.99,...,98387,Washington,West,Corporate,Technology,Telephones and Communication,Bell Sonecor JB700 Caller ID,Medium Box,0.60,2011-07-17

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8399 entries, 0 to 8398
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Row ID                8399 non-null   int64
 1   Order ID              8399 non-null   int64
 2   Order Date            8399 non-null   datetime64[ns]
 3   Order Priority        8399 non-null   object
 4   Order Quantity        8399 non-null   int64
 5   Sales                 8399 non-null   float64
 6   Discount              8399 non-null   float64
 7   Ship Mode             8399 non-null   object
 8   Profit                8399 non-null   float64
 9   Unit Price            8399 non-null   float64
 10  Shipping Cost         8399 non-null   float64
 11  Customer Name         8399 non-null   object
 12  City                  8399 non-null   object
 13  Zip Code              8399 non-null   int64
 14  State                 8399 non-null   object
 15  Region                8399 non-null   object
 16  Customer Segment      8399 non-null   object
 17  Product Category      8399 non-null   object
 18  Product Sub-Category  8399 non-null   object
 19  Product Name          8399 non-null   object
 20  Product Container     8399 non-null   object
 21  Product Base Margin   8336 non-null   float64
 22  Ship Date             8399 non-null   datetime64[ns]
dtypes: datetime64[ns](2), float64(6), int64(4), object(11)
memory usage: 1.5+ MB

##2. Reading Multiple Sheets

####Many Excel files have multiple sheets (like Orders, Returns).

####1. To see all sheet names:

In [ ]:
xls = pd.ExcelFile("Sales.xlsx")
xls.sheet_names

['Orders', 'Returns', 'Users']

####2. Read all sheets into a dictionary:

In [ ]:
sheet_dict = pd.read_excel(xls, sheet_name= None)
sheet_dict.keys()

dict_keys(['Orders', 'Returns', 'Users'])

####3. Access a specific sheet

In [ ]:
df_orders = sheet_dict['Orders']
df_orders.head()

,Row ID,Order ID,Order Date,Order Priority,Order Quantity,Sales,Discount,Ship Mode,Profit,Unit Price,...,Zip Code,State,Region,Customer Segment,Product Category,Product Sub-Category,Product Name,Product Container,Product Base Margin,Ship Date
0,1,3,2010-10-13,Low,6,261.5400,0.04,Regular Air,-213.250,38.94,...,60035,Illinois,Central,Small Business,Office Supplies,Storage & Organization,"Eldon Base for stackable storage shelf, platinum",Large Box,0.80,2010-10-20
1,2,6,2012-02-20,Not Specified,2,6.9300,0.01,Regular Air,-4.640,2.08,...,98026,Washington,West,Corporate,Office Supplies,"Scissors, Rulers and Trimmers",Kleencut® Forged Office Shears by Acme United ...,Small Pack,0.55,2012-02-21
2,3,32,2011-07-15,High,26,2808.0800,0.07,Regular Air,1054.820,107.53,...,98387,Washington,West,Corporate,Furniture,Office Furnishings,Tenex Contemporary Contur Chairmats for Low an...,Medium Box,0.65,2011-07-17
3,4,32,2011-07-15,High,24,1761.4000,0.09,Delivery Truck,-1748.560,70.89,...,98387,Washington,West,Corporate,Furniture,Tables,KI Conference Tables,Jumbo Box,0.72,2011-07-16
4,5,32,2011-07-15,High,23,160.2335,0.04,Regular Air,-85.129,7.99,...,98387,Washington,West,Corporate,Technology,Telephones and Communication,Bell Sonecor JB700 Caller ID,Medium Box,0.60,2011-07-17

##3. Using sheet_name

####Instead of reading all sheets, read a specific sheet:

###By Name

In [ ]:

df_orders = pd.read_excel('Sales.xlsx', sheet_name='Orders')
df_orders.head()

,Row ID,Order ID,Order Date,Order Priority,Order Quantity,Sales,Discount,Ship Mode,Profit,Unit Price,...,Zip Code,State,Region,Customer Segment,Product Category,Product Sub-Category,Product Name,Product Container,Product Base Margin,Ship Date
0,1,3,2010-10-13,Low,6,261.5400,0.04,Regular Air,-213.250,38.94,...,60035,Illinois,Central,Small Business,Office Supplies,Storage & Organization,"Eldon Base for stackable storage shelf, platinum",Large Box,0.80,2010-10-20
1,2,6,2012-02-20,Not Specified,2,6.9300,0.01,Regular Air,-4.640,2.08,...,98026,Washington,West,Corporate,Office Supplies,"Scissors, Rulers and Trimmers",Kleencut® Forged Office Shears by Acme United ...,Small Pack,0.55,2012-02-21
2,3,32,2011-07-15,High,26,2808.0800,0.07,Regular Air,1054.820,107.53,...,98387,Washington,West,Corporate,Furniture,Office Furnishings,Tenex Contemporary Contur Chairmats for Low an...,Medium Box,0.65,2011-07-17
3,4,32,2011-07-15,High,24,1761.4000,0.09,Delivery Truck,-1748.560,70.89,...,98387,Washington,West,Corporate,Furniture,Tables,KI Conference Tables,Jumbo Box,0.72,2011-07-16
4,5,32,2011-07-15,High,23,160.2335,0.04,Regular Air,-85.129,7.99,...,98387,Washington,West,Corporate,Technology,Telephones and Communication,Bell Sonecor JB700 Caller ID,Medium Box,0.60,2011-07-17

###By Index

In [ ]:
df_return = pd.read_excel('Sales.xlsx', sheet_name= 1)
df_return.head()

   Order ID    Status
0        65  Returned
1        69  Returned
2       134  Returned
3       135  Returned
4       230  Returned

###For Multiple Sheets

In [ ]:
df_orders, df_returns = pd.read_excel('Sales.xlsx', sheet_name=['Orders', 'Returns'])

##4. Handling Headers, Indexes, and Missing Values

###Headers:

####If headers are not on the first row:

In [ ]:
df_order = pd.read_excel("Sales.xlsx", sheet_name='Orders', header=1)
df_order.head()

,1,3,2010-10-13 00:00:00,Low,6,261.54,0.04,Regular Air,-213.25,38.94,...,60035,Illinois,Central,Small Business,Office Supplies,Storage & Organization,"Eldon Base for stackable storage shelf, platinum",Large Box,0.8,2010-10-20 00:00:00
0,2,6,2012-02-20,Not Specified,2,6.9300,0.01,Regular Air,-4.640,2.08,...,98026,Washington,West,Corporate,Office Supplies,"Scissors, Rulers and Trimmers",Kleencut® Forged Office Shears by Acme United ...,Small Pack,0.55,2012-02-21
1,3,32,2011-07-15,High,26,2808.0800,0.07,Regular Air,1054.820,107.53,...,98387,Washington,West,Corporate,Furniture,Office Furnishings,Tenex Contemporary Contur Chairmats for Low an...,Medium Box,0.65,2011-07-17
2,4,32,2011-07-15,High,24,1761.4000,0.09,Delivery Truck,-1748.560,70.89,...,98387,Washington,West,Corporate,Furniture,Tables,KI Conference Tables,Jumbo Box,0.72,2011-07-16
3,5,32,2011-07-15,High,23,160.2335,0.04,Regular Air,-85.129,7.99,...,98387,Washington,West,Corporate,Technology,Telephones and Communication,Bell Sonecor JB700 Caller ID,Medium Box,0.60,2011-07-17
4,6,32,2011-07-15,High,15,140.5600,0.04,Regular Air,-128.380,8.46,...,27260,North Carolina,South,Corporate,Technology,Computer Peripherals,"Imation 3.5 IBM Diskettes, 10/Box",Small Pack,0.79,2011-07-16

###Index_Column
####Set a column as index

In [ ]:
df_order = pd.read_excel("Sales.xlsx", sheet_name='Orders', index_col='Row ID')
df_order.head()

,Order ID,Order Date,Order Priority,Order Quantity,Sales,Discount,Ship Mode,Profit,Unit Price,Shipping Cost,...,Zip Code,State,Region,Customer Segment,Product Category,Product Sub-Category,Product Name,Product Container,Product Base Margin,Ship Date
Row ID,,,,,,,,,,,,,,,,,,,,,
1,3,2010-10-13,Low,6,261.5400,0.04,Regular Air,-213.250,38.94,35.00,...,60035,Illinois,Central,Small Business,Office Supplies,Storage & Organization,"Eldon Base for stackable storage shelf, platinum",Large Box,0.80,2010-10-20
2,6,2012-02-20,Not Specified,2,6.9300,0.01,Regular Air,-4.640,2.08,2.56,...,98026,Washington,West,Corporate,Office Supplies,"Scissors, Rulers and Trimmers",Kleencut® Forged Office Shears by Acme United ...,Small Pack,0.55,2012-02-21
3,32,2011-07-15,High,26,2808.0800,0.07,Regular Air,1054.820,107.53,5.81,...,98387,Washington,West,Corporate,Furniture,Office Furnishings,Tenex Contemporary Contur Chairmats for Low an...,Medium Box,0.65,2011-07-17
4,32,2011-07-15,High,24,1761.4000,0.09,Delivery Truck,-1748.560,70.89,89.30,...,98387,Washington,West,Corporate,Furniture,Tables,KI Conference Tables,Jumbo Box,0.72,2011-07-16
5,32,2011-07-15,High,23,160.2335,0.04,Regular Air,-85.129,7.99,5.03,...,98387,Washington,West,Corporate,Technology,Telephones and Communication,Bell Sonecor JB700 Caller ID,Medium Box,0.60,2011-07-17

###Missing values:

####Replace custom markers like "NA", "n/a":

In [ ]:
df_order = pd.read_excel("Sales.xlsx", sheet_name='Orders', na_values=['NA',"n/a",""])
df_order.isna().sum()

Row ID                   0
Order ID                 0
Order Date               0
Order Priority           0
Order Quantity           0
Sales                    0
Discount                 0
Ship Mode                0
Profit                   0
Unit Price               0
Shipping Cost            0
Customer Name            0
City                     0
Zip Code                 0
State                    0
Region                   0
Customer Segment         0
Product Category         0
Product Sub-Category     0
Product Name             0
Product Container        0
Product Base Margin     63
Ship Date                0
dtype: int64

##5. Parsing Dates
####Many Excel datasets have date columns like Order Date, Ship Date.

In [ ]:
df_orders = pd.read_excel("Sales.xlsx", sheet_name="Orders", parse_dates= ['Ship Date'])
df_order.dtypes

Row ID                           int64
Order ID                         int64
Order Date              datetime64[ns]
Order Priority                  object
Order Quantity                   int64
Sales                          float64
Discount                       float64
Ship Mode                       object
Profit                         float64
Unit Price                     float64
Shipping Cost                  float64
Customer Name                   object
City                            object
Zip Code                         int64
State                           object
Region                          object
Customer Segment                object
Product Category                object
Product Sub-Category            object
Product Name                    object
Product Container               object
Product Base Margin            float64
Ship Date               datetime64[ns]
dtype: object

####Combine multiple columns into one datetime (rare, but possible):
##### Example if Excel has Year, Month, Day columns
`df_orders = pd.read_excel("Superstore_Sales.xlsx", parse_dates=[["Year", "Month", "Day"]])`

#6. Select only needed Columns

In [ ]:
df_orders = pd.read_excel('Sales.xlsx', sheet_name='Orders', usecols='A:C')
df_orders.head()

   Row ID  Order ID Order Date
0       1         3 2010-10-13
1       2         6 2012-02-20
2       3        32 2011-07-15
3       4        32 2011-07-15
4       5        32 2011-07-15

##Read only first N rows:

In [ ]:
df_orders = pd.read_excel('Sales.xlsx', sheet_name='Orders', nrows= 2)
df_orders

,Row ID,Order ID,Order Date,Order Priority,Order Quantity,Sales,Discount,Ship Mode,Profit,Unit Price,...,Zip Code,State,Region,Customer Segment,Product Category,Product Sub-Category,Product Name,Product Container,Product Base Margin,Ship Date
0,1,3,2010-10-13,Low,6,261.54,0.04,Regular Air,-213.25,38.94,...,60035,Illinois,Central,Small Business,Office Supplies,Storage & Organization,"Eldon Base for stackable storage shelf, platinum",Large Box,0.80,2010-10-20
1,2,6,2012-02-20,Not Specified,2,6.93,0.01,Regular Air,-4.64,2.08,...,98026,Washington,West,Corporate,Office Supplies,"Scissors, Rulers and Trimmers",Kleencut® Forged Office Shears by Acme United ...,Small Pack,0.55,2012-02-21

In [ ]:
df_orders = pd.read_excel('Sales.xlsx', sheet_name='Orders', nrows= 2, usecols='A:C, F')
df_orders

   Row ID  Order ID Order Date   Sales
0       1         3 2010-10-13  261.54
1       2         6 2012-02-20    6.93

##Skip Unnecessary Rows

In [ ]:
df_orders = pd.read_excel("Sales.xlsx", sheet_name='Orders', skiprows=2)
df_orders.head()

,2,6,2012-02-20 00:00:00,Not Specified,2.1,6.93,0.01,Regular Air,-4.64,2.08,...,98026,Washington,West,Corporate,Office Supplies,"Scissors, Rulers and Trimmers",Kleencut® Forged Office Shears by Acme United Corporation,Small Pack,0.55,2012-02-21 00:00:00
0,3,32,2011-07-15,High,26,2808.0800,0.07,Regular Air,1054.820,107.53,...,98387,Washington,West,Corporate,Furniture,Office Furnishings,Tenex Contemporary Contur Chairmats for Low an...,Medium Box,0.65,2011-07-17
1,4,32,2011-07-15,High,24,1761.4000,0.09,Delivery Truck,-1748.560,70.89,...,98387,Washington,West,Corporate,Furniture,Tables,KI Conference Tables,Jumbo Box,0.72,2011-07-16
2,5,32,2011-07-15,High,23,160.2335,0.04,Regular Air,-85.129,7.99,...,98387,Washington,West,Corporate,Technology,Telephones and Communication,Bell Sonecor JB700 Caller ID,Medium Box,0.60,2011-07-17
3,6,32,2011-07-15,High,15,140.5600,0.04,Regular Air,-128.380,8.46,...,27260,North Carolina,South,Corporate,Technology,Computer Peripherals,"Imation 3.5 IBM Diskettes, 10/Box",Small Pack,0.79,2011-07-16
4,7,35,2011-10-22,Not Specified,30,288.5600,0.03,Regular Air,60.720,9.11,...,50010,Iowa,Central,Corporate,Office Supplies,Pens & Art Supplies,Dixon Ticonderoga Core-Lock Colored Pencils,Wrap Bag,0.52,2011-10-23

###Apply Converters to Columns

In [ ]:
df_orders = pd.read_excel('Sales.xlsx', sheet_name='Orders', converters={"Order ID": str})
df_orders.dtypes

Row ID                           int64
Order ID                        object
Order Date              datetime64[ns]
Order Priority                  object
Order Quantity                   int64
Sales                          float64
Discount                       float64
Ship Mode                       object
Profit                         float64
Unit Price                     float64
Shipping Cost                  float64
Customer Name                   object
City                            object
Zip Code                         int64
State                           object
Region                          object
Customer Segment                object
Product Category                object
Product Sub-Category            object
Product Name                    object
Product Container               object
Product Base Margin            float64
Ship Date               datetime64[ns]
dtype: object

#3. Json Files
####JSON is extremely important because most modern data comes from:

####1. APIs
####2. Web applications
####3. Microservices
####4. logs

####CSV and Excel are mostly static files, but JSON is dynamic data.

In [4]:
from google.colab import files

uploaded = files.upload()

Saving countries+states+cities.json to countries+states+cities.json

In [7]:
import pandas as pd
df = pd.read_json('countries+states+cities.json')
df.head()

,id,name,iso3,iso2,phone_code,capital,currency,currency_symbol,tld,native,region,subregion,timezones,translations,latitude,longitude,emoji,emojiU,states
0,1,Afghanistan,AFG,AF,93,Kabul,AFN,؋,.af,افغانستان,Asia,Southern Asia,"[{'zoneName': 'Asia/Kabul', 'gmtOffset': 16200...","{'kr': '아프가니스탄', 'br': 'Afeganistão', 'pt': 'A...",33.000000,65.0,🇦🇫,U+1F1E6 U+1F1EB,"[{'id': 3901, 'name': 'Badakhshan', 'state_cod..."
1,2,Aland Islands,ALA,AX,+358-18,Mariehamn,EUR,€,.ax,Åland,Europe,Northern Europe,"[{'zoneName': 'Europe/Mariehamn', 'gmtOffset':...","{'kr': '올란드 제도', 'br': 'Ilhas de Aland', 'pt':...",60.116667,19.9,🇦🇽,U+1F1E6 U+1F1FD,[]
2,3,Albania,ALB,AL,355,Tirana,ALL,Lek,.al,Shqipëria,Europe,Southern Europe,"[{'zoneName': 'Europe/Tirane', 'gmtOffset': 36...","{'kr': '알바니아', 'br': 'Albânia', 'pt': 'Albânia...",41.000000,20.0,🇦🇱,U+1F1E6 U+1F1F1,"[{'id': 603, 'name': 'Berat County', 'state_co..."
3,4,Algeria,DZA,DZ,213,Algiers,DZD,دج,.dz,الجزائر,Africa,Northern Africa,"[{'zoneName': 'Africa/Algiers', 'gmtOffset': 3...","{'kr': '알제리', 'br': 'Argélia', 'pt': 'Argélia'...",28.000000,3.0,🇩🇿,U+1F1E9 U+1F1FF,"[{'id': 1118, 'name': 'Adrar', 'state_code': '..."
4,5,American Samoa,ASM,AS,+1-684,Pago Pago,USD,$,.as,American Samoa,Oceania,Polynesia,"[{'zoneName': 'Pacific/Pago_Pago', 'gmtOffset'...","{'kr': '아메리칸사모아', 'br': 'Samoa Americana', 'pt...",-14.333333,-170.0,🇦🇸,U+1F1E6 U+1F1F8,[]

In [8]:
import os
os.rename('countries+states+cities.json', 'dataset.json')

##1. pd.read_json()

In [10]:
df= pd.read_json('dataset.json')
df.head()

,id,name,iso3,iso2,phone_code,capital,currency,currency_symbol,tld,native,region,subregion,timezones,translations,latitude,longitude,emoji,emojiU,states
0,1,Afghanistan,AFG,AF,93,Kabul,AFN,؋,.af,افغانستان,Asia,Southern Asia,"[{'zoneName': 'Asia/Kabul', 'gmtOffset': 16200...","{'kr': '아프가니스탄', 'br': 'Afeganistão', 'pt': 'A...",33.000000,65.0,🇦🇫,U+1F1E6 U+1F1EB,"[{'id': 3901, 'name': 'Badakhshan', 'state_cod..."
1,2,Aland Islands,ALA,AX,+358-18,Mariehamn,EUR,€,.ax,Åland,Europe,Northern Europe,"[{'zoneName': 'Europe/Mariehamn', 'gmtOffset':...","{'kr': '올란드 제도', 'br': 'Ilhas de Aland', 'pt':...",60.116667,19.9,🇦🇽,U+1F1E6 U+1F1FD,[]
2,3,Albania,ALB,AL,355,Tirana,ALL,Lek,.al,Shqipëria,Europe,Southern Europe,"[{'zoneName': 'Europe/Tirane', 'gmtOffset': 36...","{'kr': '알바니아', 'br': 'Albânia', 'pt': 'Albânia...",41.000000,20.0,🇦🇱,U+1F1E6 U+1F1F1,"[{'id': 603, 'name': 'Berat County', 'state_co..."
3,4,Algeria,DZA,DZ,213,Algiers,DZD,دج,.dz,الجزائر,Africa,Northern Africa,"[{'zoneName': 'Africa/Algiers', 'gmtOffset': 3...","{'kr': '알제리', 'br': 'Argélia', 'pt': 'Argélia'...",28.000000,3.0,🇩🇿,U+1F1E9 U+1F1FF,"[{'id': 1118, 'name': 'Adrar', 'state_code': '..."
4,5,American Samoa,ASM,AS,+1-684,Pago Pago,USD,$,.as,American Samoa,Oceania,Polynesia,"[{'zoneName': 'Pacific/Pago_Pago', 'gmtOffset'...","{'kr': '아메리칸사모아', 'br': 'Samoa Americana', 'pt...",-14.333333,-170.0,🇦🇸,U+1F1E6 U+1F1F8,[]

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               250 non-null    int64
 1   name             250 non-null    object
 2   iso3             250 non-null    object
 3   iso2             250 non-null    object
 4   phone_code       250 non-null    object
 5   capital          250 non-null    object
 6   currency         250 non-null    object
 7   currency_symbol  250 non-null    object
 8   tld              250 non-null    object
 9   native           249 non-null    object
 10  region           250 non-null    object
 11  subregion        250 non-null    object
 12  timezones        250 non-null    object
 13  translations     250 non-null    object
 14  latitude         250 non-null    float64
 15  longitude        250 non-null    float64
 16  emoji            250 non-null    object
 17  emojiU           250 non-null    object
 18  states           250 non-null    object
dtypes: float64(2), int64(1), object(16)
memory usage: 37.2+ KB

##Inspect the nested Data

In [14]:
df['states'].head()

0    [{'id': 3901, 'name': 'Badakhshan', 'state_cod...
1                                                   []
2    [{'id': 603, 'name': 'Berat County', 'state_co...
3    [{'id': 1118, 'name': 'Adrar', 'state_code': '...
4                                                   []
Name: states, dtype: object

In [15]:
df['states'].iloc[0]

[{'id': 3901,
  'name': 'Badakhshan',
  'state_code': 'BDS',
  'latitude': '36.73477250',
  'longitude': '70.81199530',
  'cities': [{'id': 52,
    'name': 'Ashkāsham',
    'latitude': '36.68333000',
    'longitude': '71.53333000'},
   {'id': 68,
    'name': 'Fayzabad',
    'latitude': '37.11664000',
    'longitude': '70.58002000'},
   {'id': 78,
    'name': 'Jurm',
    'latitude': '36.86477000',
    'longitude': '70.83421000'},
   {'id': 84,
    'name': 'Khandūd',
    'latitude': '36.95127000',
    'longitude': '72.31800000'},
   {'id': 115,
    'name': 'Rāghistān',
    'latitude': '37.66079000',
    'longitude': '70.67346000'},
   {'id': 131,
    'name': 'Wākhān',
    'latitude': '37.05710000',
    'longitude': '73.34928000'}]},
 {'id': 3871,
  'name': 'Badghis',
  'state_code': 'BDG',
  'latitude': '35.16713390',
  'longitude': '63.76953840',
  'cities': [{'id': 72,
    'name': 'Ghormach',
    'latitude': '35.73062000',
    'longitude': '63.78264000'},
   {'id': 108,
    'name': 'Qala i Naw',
    'latitude': '34.98735000',
    'longitude': '63.12891000'}]},
 {'id': 3875,
  'name': 'Baghlan',
  'state_code': 'BGL',
  'latitude': '36.17890260',
  'longitude': '68.74530640',
  'cities': [{'id': 54,
    'name': 'Baghlān',
    'latitude': '36.13068000',
    'longitude': '68.70829000'},
   {'id': 140,
    'name': 'Ḩukūmatī Dahanah-ye Ghōrī',
    'latitude': '35.90617000',
    'longitude': '68.48869000'},
   {'id': 101,
    'name': 'Nahrīn',
    'latitude': '36.06490000',
    'longitude': '69.13343000'},
   {'id': 105,
    'name': 'Pul-e Khumrī',
    'latitude': '35.94458000',
    'longitude': '68.71512000'}]},
 {'id': 3884,
  'name': 'Balkh',
  'state_code': 'BAL',
  'latitude': '36.75506030',
  'longitude': '66.89753720',
  'cities': [{'id': 55,
    'name': 'Balkh',
    'latitude': '36.75635000',
    'longitude': '66.89720000'},
   {'id': 65,
    'name': 'Dowlatābād',
    'latitude': '36.98821000',
    'longitude': '66.82069000'},
   {'id': 85,
    'name': 'Khulm',
    'latitude': '36.69736000',
    'longitude': '67.69826000'},
   {'id': 91,
    'name': 'Lab-Sar',
    'latitude': '36.02634000',
    'longitude': '66.83799000'},
   {'id': 97,
    'name': 'Mazār-e Sharīf',
    'latitude': '36.70904000',
    'longitude': '67.11087000'},
   {'id': 112,
    'name': 'Qarchī Gak',
    'latitude': '37.03999000',
    'longitude': '66.78891000'}]},
 {'id': 3872,
  'name': 'Bamyan',
  'state_code': 'BAM',
  'latitude': '34.81000670',
  'longitude': '67.82121040',
  'cities': [{'id': 57,
    'name': 'Bāmyān',
    'latitude': '34.82156000',
    'longitude': '67.82734000'},
   {'id': 104,
    'name': 'Panjāb',
    'latitude': '34.38795000',
    'longitude': '67.02327000'}]},
 {'id': 3892,
  'name': 'Daykundi',
  'state_code': 'DAY',
  'latitude': '33.66949500',
  'longitude': '66.04635340',
  'cities': [{'id': 102,
    'name': 'Nīlī',
    'latitude': '33.76329000',
    'longitude': '66.07617000'}]},
 {'id': 3899,
  'name': 'Farah',
  'state_code': 'FRA',
  'latitude': '32.49532800',
  'longitude': '62.26266270',
  'cities': [{'id': 66,
    'name': 'Farah',
    'latitude': '32.37451000',
    'longitude': '62.11638000'}]},
 {'id': 3889,
  'name': 'Faryab',
  'state_code': 'FYB',
  'latitude': '36.07956130',
  'longitude': '64.90595500',
  'cities': [{'id': 50,
    'name': 'Andkhoy',
    'latitude': '36.95293000',
    'longitude': '65.12376000'},
   {'id': 96,
    'name': 'Maymana',
    'latitude': '35.92139000',
    'longitude': '64.78361000'}]},
 {'id': 3870,
  'name': 'Ghazni',
  'state_code': 'GHA',
  'latitude': '33.54505870',
  'longitude': '68.41739720',
  'cities': [{'id': 71,
    'name': 'Ghazni',
    'latitude': '33.55391000',
    'longitude': '68.42096000'}]},
 {'id': 3888,
  'name': 'Ghōr',
  'state_code': 'GHO',
  'latitude': '34.09957760',
  'longitude': '64.90595500',
  'cities': [{'id': 67,
    'name': 'Fayrōz Kōh',
    'latitude': '34.51952000',
    'longitude': '65.25093000'},
   {'id': 121,
    'name': 'Shahrak',
    'latitude': '34.10737000',
    'longitude': '64.30520000'}]},
 {'id': 3873,
  'name': 'Helmand',
  'state_code': 'HEL',
  'latitude': '39.29893610',
  'longitude': '-76.61604720',
  'cities': [{'id': 141,
    'name': '‘Alāqahdārī Dīshū',
    'latitude': '30.43206000',
    'longitude': '63.29802000'},
   {'id': 70,
    'name': 'Gereshk',
    'latitude': '31.82089000',
    'longitude': '64.57005000'},
   {'id': 93,
    'name': 'Lashkar Gāh',
    'latitude': '31.59382000',
    'longitude': '64.37161000'},
   {'id': 95,
    'name': 'Markaz-e Ḩukūmat-e Darwēshān',
    'latitude': '31.13231000',
    'longitude': '64.19340000'},
   {'id': 118,
    'name': 'Sangīn',
    'latitude': '32.07275000',
    'longitude': '64.83590000'}]},
 {'id': 3887,
  'name': 'Herat',
  'state_code': 'HER',
  'latitude': '34.35286500',
  'longitude': '62.20402870',
  'cities': [{'id': 60,
    'name': 'Chahār Burj',
    'latitude': '34.24475000',
    'longitude': '62.19165000'},
   {'id': 73,
    'name': 'Ghōriyān',
    'latitude': '34.34480000',
    'longitude': '61.49321000'},
   {'id': 74,
    'name': 'Herāt',
    'latitude': '34.34817000',
    'longitude': '62.19967000'},
   {'id': 80,
    'name': 'Kafir Qala',
    'latitude': '34.66667000',
    'longitude': '61.06667000'},
   {'id': 82,
    'name': 'Karukh',
    'latitude': '34.48108000',
    'longitude': '62.58630000'},
   {'id': 88,
    'name': 'Kuhsān',
    'latitude': '34.65389000',
    'longitude': '61.19778000'},
   {'id': 90,
    'name': 'Kushk',
    'latitude': '33.29565000',
    'longitude': '61.95221000'},
   {'id': 111,
    'name': 'Qarah Bāgh',
    'latitude': '34.94023000',
    'longitude': '61.77589000'},
   {'id': 123,
    'name': 'Shīnḏanḏ',
    'latitude': '33.30294000',
    'longitude': '62.14740000'},
   {'id': 129,
    'name': 'Tīr Pul',
    'latitude': '34.59431000',
    'longitude': '61.26895000'},
   {'id': 135,
    'name': 'Zindah Jān',
    'latitude': '34.34264000',
    'longitude': '61.74675000'}]},
 {'id': 3886,
  'name': 'Jowzjan',
  'state_code': 'JOW',
  'latitude': '36.89696920',
  'longitude': '65.66585680',
  'cities': [{'id': 136,
    'name': 'Āqchah',
    'latitude': '36.90500000',
    'longitude': '66.18341000'},
   {'id': 63,
    'name': 'Darzāb',
    'latitude': '35.97744000',
    'longitude': '65.37828000'},
   {'id': 113,
    'name': 'Qarqīn',
    'latitude': '37.41853000',
    'longitude': '66.04358000'},
   {'id': 122,
    'name': 'Shibirghān',
    'latitude': '36.66757000',
    'longitude': '65.75290000'}]},
 {'id': 3902,
  'name': 'Kabul',
  'state_code': 'KAB',
  'latitude': '34.55534940',
  'longitude': '69.20748600',
  'cities': [{'id': 79,
    'name': 'Kabul',
    'latitude': '34.52813000',
    'longitude': '69.17233000'},
   {'id': 99,
    'name': 'Mīr Bachah Kōṯ',
    'latitude': '34.74999000',
    'longitude': '69.11899000'},
   {'id': 103,
    'name': 'Paghmān',
    'latitude': '34.58787000',
    'longitude': '68.95091000'}]},
 {'id': 3890,
  'name': 'Kandahar',
  'state_code': 'KAN',
  'latitude': '31.62887100',
  'longitude': '65.73717490',
  'cities': [{'id': 81,
    'name': 'Kandahār',
    'latitude': '31.61332000',
    'longitude': '65.71013000'}]},
 {'id': 3879,
  'name': 'Kapisa',
  'state_code': 'KAP',
  'latitude': '34.98105720',
  'longitude': '69.62145620',
  'cities': [{'id': 124,
    'name': 'Sidqābād',
    'latitude': '35.02298000',
    'longitude': '69.35112000'}]},
 {'id': 3878,
  'name': 'Khost',
  'state_code': 'KHO',
  'latitude': '33.33384720',
  'longitude': '69.93716730',
  'cities': [{'id': 87,
    'name': 'Khōst',
    'latitude': '33.33951000',
    'longitude': '69.92041000'}]},
 {'id': 3876,
  'name': 'Kunar',
  'state_code': 'KNR',
  'latitude': '34.84658930',
  'longitude': '71.09731700',
  'cities': [{'id': 51,
    'name': 'Asadabad',
    'latitude': '34.87311000',
    'longitude': '71.14697000'},
   {'id': 138,
    'name': 'Āsmār',
    'latitude': '35.03333000',
    'longitude': '71.35809000'}]},
 {'id': 3900,
  'name': 'Kunduz Province',
  'state_code': 'KDZ',
  'latitude': '36.72855110',
  'longitude': '68.86789820',
  'cities': [{'id': 64,
    'name': 'Dasht-e Archī',
    'latitude': '37.13333000',
    'longitude': '69.16667000'},
   {'id': 75,
    'name': 'Imām Şāḩib',
    'latitude': '37.18897000',
    'longitude': '68.93644000'},
   {'id': 83,
    'name': 'Khanabad',
    'latitude': '36.68250000',
    'longitude': '69.11556000'},
   {'id': 89,
    'name': 'Kunduz',
    'latitude': '36.72895000',
    'longitude': '68.85700000'},
   {'id': 114,
    'name': 'Qarāwul',
    'latitude': '37.21959000',
    'longitude': '68.78020000'}]},
 {'id': 3891,
  'name': 'Laghman',
  'state_code': 'LAG',
  'latitude': '34.68976870',
  'longitude': '70.14558050',
  'cities': [{'id': 98,
    'name': 'Mehtar Lām',
    'latitude': '34.67139000',
    'longitude': '70.20944000'}]},
 {'id': 3897,
  'name': 'Logar',
  'state_code': 'LOG',
  'latitude': '34.01455180',
  'longitude': '69.19239160',
  'cities': [{'id': 56,
    'name': 'Baraki Barak',
    'latitude': '33.96744000',
    'longitude': '68.94920000'},
   {'id': 139,
    'name': 'Ḩukūmatī Azrah',
    'latitude': '34.17355000',
    'longitude': '69.64573000'},
   {'id': 106,
    'name': 'Pul-e ‘Alam',
    'latitude': '33.99529000',
    'longitude': '69.02274000'}]},
 {'id': 3882,
  'name': 'Nangarhar',
  'state_code': 'NAN',
  'latitude': '34.17183130',
  'longitude': '70.62167940',
  'cities': [{'id': 58,
    'name': 'Bāsawul',
    'latitude': '34.24749000',
    'longitude': '70.87218000'},
   {'id': 77,
    'name': 'Jalālābād',
    'latitude': '34.42647000',
    'longitude': '70.45153000'},
   {'id': 94,
    'name': 'Markaz-e Woluswalī-ye Āchīn',
    'latitude': '34.12583000',
    'longitude': '70.70778000'}]},
 {'id': 3896,
  'name': 'Nimruz',
  'state_code': 'NIM',
  'latitude': '31.02614880',
  'longitude': '62.45041540',
  'cities': [{'id': 86,
    'name': 'Khāsh',
    'latitude': '31.52919000',
    'longitude': '62.79055000'},
   {'id': 100,
    'name': 'Mīrābād',
    'latitude': '30.43624000',
    'longitude': '61.83830000'},
   {'id': 116,
    'name': 'Rūdbār',
    'latitude': '30.15000000',
    'longitude': '62.60000000'},
   {'id': 132,
    'name': 'Zaranj',
    'latitude': '30.95962000',
    'longitude': '61.86037000'}]},
 {'id': 3880,
  'name': 'Nuristan',
  'state_code': 'NUR',
  'latitude': '35.32502230',
  'longitude': '70.90712360',
  'cities': [{'id': 107,
    'name': 'Pārūn',
    'latitude': '35.42064000',
    'longitude': '70.92261000'}]},
 {'id': 3894,
  'name': 'Paktia',
  'state_code': 'PIA',
  'latitude': '33.70619900',
  'longitude': '69.38310790',
  'cities': [{'id': 69,
    'name': 'Gardez',
    'latitude': '33.59744000',
    'longitude': '69.22592000'}]},
 {'id': 3877,
  'name': 'Paktika',
  'state_code': 'PKA',
  'latitude': '32.26453860',
  'longitude': '68.52471490',
  'cities': [{'id': 120,
    'name': 'Saṟōbī',
    'latitude': '32.75221000',
    'longitude': '69.04587000'},
   {'id': 134,
    'name': 'Zaṟah Sharan',
    'latitude': '33.14641000',
    'longitude': '68.79213000'},
   {'id': 133,
    'name': 'Zarghūn Shahr',
    'latitude': '32.84734000',
    'longitude': '68.44573000'}]},
 {'id': 3881,
  'name': 'Panjshir',
  'state_code': 'PAN',
  'latitude': '38.88023910',
  'longitude': '-77.17172380',
  'cities': [{'id': 59,
    'name': 'Bāzārak',
    'latitude': '35.31292000',
    'longitude': '69.51519000'}]},
 {'id': 3895,
  'name': 'Parwan',
  'state_code': 'PAR',
  'latitude': '34.96309770',
  'longitude': '68.81088490',
  'cities': [{'id': 61,
    'name': 'Charikar',
    'latitude': '35.01361000',
    'longitude': '69.17139000'},
   {'id': 76,
    'name': 'Jabal os Saraj',
    'latitude': '35.11833000',
    'longitude': '69.23778000'}]},
 {'id': 3883,
  'name': 'Samangan',
  'state_code': 'SAM',
  'latitude': '36.31555060',
  'longitude': '67.96428630',
  'cities': [{'id': 53,
    'name': 'Aībak',
    'latitude': '36.26468000',
    'longitude': '68.01551000'}]},
 {'id': 3885,
  'name': 'Sar-e Pol',
  'state_code': 'SAR',
  'latitude': '36.21662800',
  'longitude': '65.93336000',
  'cities': [{'id': 62,
    'name': 'Chīras',
    'latitude': '35.41674000',
    'longitude': '65.98234000'},
   {'id': 92,
    'name': 'Larkird',
    'latitude': '35.48936000',
    'longitude': '66.66409000'},
   {'id': 110,
    'name': 'Qal‘ah-ye Shahr',
    'latitude': '35.54729000',
    'longitude': '65.56760000'},
   {'id': 117,
    'name': 'Sang-e Chārak',
    'latitude': '35.84972000',
    'longitude': '66.43694000'},
   {'id': 119,
    'name': 'Sar-e Pul',
    'latitude': '36.21544000',
    'longitude': '65.93249000'},
   {'id': 125,
    'name': 'Tagāw-Bāy',
    'latitude': '35.69941000',
    'longitude': '66.06164000'},
   {'id': 128,
    'name': 'Tukzār',
    'latitude': '35.94831000',
    'longitude': '66.42132000'}]},
 {'id': 3893,
  'name': 'Takhar',
  'state_code': 'TAK',
  'latitude': '36.66980130',
  'longitude': '69.47845410',
  'cities': [{'id': 137,
    'name': 'Ārt Khwājah',
    'latitude': '37.08571000',
    'longitude': '69.47958000'},
   {'id': 126,
    'name': 'Taloqan',
    'latitude': '36.73605000',
    'longitude': '69.53451000'}]},
 {'id': 3898,
  'name': 'Urozgan',
  'state_code': 'URU',
  'latitude': '32.92712870',
  'longitude': '66.14152630',
  'cities': [{'id': 127,
    'name': 'Tarinkot',
    'latitude': '32.62998000',
    'longitude': '65.87806000'},
   {'id': 130,
    'name': 'Uruzgān',
    'latitude': '32.92775000',
    'longitude': '66.63253000'}]},
 {'id': 3874,
  'name': 'Zabul',
  'state_code': 'ZAB',
  'latitude': '32.19187820',
  'longitude': '67.18944880',
  'cities': [{'id': 109,
    'name': 'Qalāt',
    'latitude': '32.10575000',
    'longitude': '66.90833000'}]}]

##Reading Nested JSON Properly

In [13]:
from pandas import json_normalize
states = json_normalize(df['states'].explode())
states.head()

,id,name,state_code,latitude,longitude,cities
0,3901.0,Badakhshan,BDS,36.73477250,70.81199530,"[{'id': 52, 'name': 'Ashkāsham', 'latitude': '..."
1,3871.0,Badghis,BDG,35.16713390,63.76953840,"[{'id': 72, 'name': 'Ghormach', 'latitude': '3..."
2,3875.0,Baghlan,BGL,36.17890260,68.74530640,"[{'id': 54, 'name': 'Baghlān', 'latitude': '36..."
3,3884.0,Balkh,BAL,36.75506030,66.89753720,"[{'id': 55, 'name': 'Balkh', 'latitude': '36.7..."
4,3872.0,Bamyan,BAM,34.81000670,67.82121040,"[{'id': 57, 'name': 'Bāmyān', 'latitude': '34...."

##Orient Parameter

####When reading JSON, Pandas needs to know how the data is structured.

###This is controlled by:

## orient
###Common Orientations:
##1. Records

In [16]:
pd.read_json('dataset.json', orient='records')

,id,name,iso3,iso2,phone_code,capital,currency,currency_symbol,tld,native,region,subregion,timezones,translations,latitude,longitude,emoji,emojiU,states
0,1,Afghanistan,AFG,AF,93,Kabul,AFN,؋,.af,افغانستان,Asia,Southern Asia,"[{'zoneName': 'Asia/Kabul', 'gmtOffset': 16200...","{'kr': '아프가니스탄', 'br': 'Afeganistão', 'pt': 'A...",33.000000,65.0,🇦🇫,U+1F1E6 U+1F1EB,"[{'id': 3901, 'name': 'Badakhshan', 'state_cod..."
1,2,Aland Islands,ALA,AX,+358-18,Mariehamn,EUR,€,.ax,Åland,Europe,Northern Europe,"[{'zoneName': 'Europe/Mariehamn', 'gmtOffset':...","{'kr': '올란드 제도', 'br': 'Ilhas de Aland', 'pt':...",60.116667,19.9,🇦🇽,U+1F1E6 U+1F1FD,[]
2,3,Albania,ALB,AL,355,Tirana,ALL,Lek,.al,Shqipëria,Europe,Southern Europe,"[{'zoneName': 'Europe/Tirane', 'gmtOffset': 36...","{'kr': '알바니아', 'br': 'Albânia', 'pt': 'Albânia...",41.000000,20.0,🇦🇱,U+1F1E6 U+1F1F1,"[{'id': 603, 'name': 'Berat County', 'state_co..."
3,4,Algeria,DZA,DZ,213,Algiers,DZD,دج,.dz,الجزائر,Africa,Northern Africa,"[{'zoneName': 'Africa/Algiers', 'gmtOffset': 3...","{'kr': '알제리', 'br': 'Argélia', 'pt': 'Argélia'...",28.000000,3.0,🇩🇿,U+1F1E9 U+1F1FF,"[{'id': 1118, 'name': 'Adrar', 'state_code': '..."
4,5,American Samoa,ASM,AS,+1-684,Pago Pago,USD,$,.as,American Samoa,Oceania,Polynesia,"[{'zoneName': 'Pacific/Pago_Pago', 'gmtOffset'...","{'kr': '아메리칸사모아', 'br': 'Samoa Americana', 'pt...",-14.333333,-170.0,🇦🇸,U+1F1E6 U+1F1F8,[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,243,Wallis And Futuna Islands,WLF,WF,681,Mata Utu,XPF,₣,.wf,Wallis et Futuna,Oceania,Polynesia,"[{'zoneName': 'Pacific/Wallis', 'gmtOffset': 4...","{'kr': '왈리스 푸투나', 'br': 'Wallis e Futuna', 'pt...",-13.300000,-176.2,🇼🇫,U+1F1FC U+1F1EB,[]
246,244,Western Sahara,ESH,EH,212,El-Aaiun,MAD,MAD,.eh,الصحراء الغربية,Africa,Northern Africa,"[{'zoneName': 'Africa/El_Aaiun', 'gmtOffset': ...","{'kr': '서사하라', 'br': 'Saara Ocidental', 'pt': ...",24.500000,-13.0,🇪🇭,U+1F1EA U+1F1ED,[]
247,245,Yemen,YEM,YE,967,Sanaa,YER,﷼,.ye,اليَمَن,Asia,Western Asia,"[{'zoneName': 'Asia/Aden', 'gmtOffset': 10800,...","{'kr': '예멘', 'br': 'Iêmen', 'pt': 'Iémen', 'nl...",15.000000,48.0,🇾🇪,U+1F1FE U+1F1EA,"[{'id': 1242, 'name': ''Adan Governorate', 'st..."
248,246,Zambia,ZMB,ZM,260,Lusaka,ZMW,ZK,.zm,Zambia,Africa,Eastern Africa,"[{'zoneName': 'Africa/Lusaka', 'gmtOffset': 72...","{'kr': '잠비아', 'br': 'Zâmbia', 'pt': 'Zâmbia', ...",-15.000000,30.0,🇿🇲,U+1F1FF U+1F1F2,"[{'id': 1986, 'name': 'Central Province', 'sta..."
249,247,Zimbabwe,ZWE,ZW,263,Harare,ZWL,$,.zw,Zimbabwe,Africa,Eastern Africa,"[{'zoneName': 'Africa/Harare', 'gmtOffset': 72...","{'kr': '짐바브웨', 'br': 'Zimbabwe', 'pt': 'Zimbab...",-20.000000,30.0,🇿🇼,U+1F1FF U+1F1FC,"[{'id': 1956, 'name': 'Bulawayo Province', 'st..."

##2. Index

`pd.read_json('dataset.json', orient='index')`

##3. columns

In [19]:
pd.read_json('dataset.json', orient='columns')

,id,name,iso3,iso2,phone_code,capital,currency,currency_symbol,tld,native,region,subregion,timezones,translations,latitude,longitude,emoji,emojiU,states
0,1,Afghanistan,AFG,AF,93,Kabul,AFN,؋,.af,افغانستان,Asia,Southern Asia,"[{'zoneName': 'Asia/Kabul', 'gmtOffset': 16200...","{'kr': '아프가니스탄', 'br': 'Afeganistão', 'pt': 'A...",33.000000,65.0,🇦🇫,U+1F1E6 U+1F1EB,"[{'id': 3901, 'name': 'Badakhshan', 'state_cod..."
1,2,Aland Islands,ALA,AX,+358-18,Mariehamn,EUR,€,.ax,Åland,Europe,Northern Europe,"[{'zoneName': 'Europe/Mariehamn', 'gmtOffset':...","{'kr': '올란드 제도', 'br': 'Ilhas de Aland', 'pt':...",60.116667,19.9,🇦🇽,U+1F1E6 U+1F1FD,[]
2,3,Albania,ALB,AL,355,Tirana,ALL,Lek,.al,Shqipëria,Europe,Southern Europe,"[{'zoneName': 'Europe/Tirane', 'gmtOffset': 36...","{'kr': '알바니아', 'br': 'Albânia', 'pt': 'Albânia...",41.000000,20.0,🇦🇱,U+1F1E6 U+1F1F1,"[{'id': 603, 'name': 'Berat County', 'state_co..."
3,4,Algeria,DZA,DZ,213,Algiers,DZD,دج,.dz,الجزائر,Africa,Northern Africa,"[{'zoneName': 'Africa/Algiers', 'gmtOffset': 3...","{'kr': '알제리', 'br': 'Argélia', 'pt': 'Argélia'...",28.000000,3.0,🇩🇿,U+1F1E9 U+1F1FF,"[{'id': 1118, 'name': 'Adrar', 'state_code': '..."
4,5,American Samoa,ASM,AS,+1-684,Pago Pago,USD,$,.as,American Samoa,Oceania,Polynesia,"[{'zoneName': 'Pacific/Pago_Pago', 'gmtOffset'...","{'kr': '아메리칸사모아', 'br': 'Samoa Americana', 'pt...",-14.333333,-170.0,🇦🇸,U+1F1E6 U+1F1F8,[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,243,Wallis And Futuna Islands,WLF,WF,681,Mata Utu,XPF,₣,.wf,Wallis et Futuna,Oceania,Polynesia,"[{'zoneName': 'Pacific/Wallis', 'gmtOffset': 4...","{'kr': '왈리스 푸투나', 'br': 'Wallis e Futuna', 'pt...",-13.300000,-176.2,🇼🇫,U+1F1FC U+1F1EB,[]
246,244,Western Sahara,ESH,EH,212,El-Aaiun,MAD,MAD,.eh,الصحراء الغربية,Africa,Northern Africa,"[{'zoneName': 'Africa/El_Aaiun', 'gmtOffset': ...","{'kr': '서사하라', 'br': 'Saara Ocidental', 'pt': ...",24.500000,-13.0,🇪🇭,U+1F1EA U+1F1ED,[]
247,245,Yemen,YEM,YE,967,Sanaa,YER,﷼,.ye,اليَمَن,Asia,Western Asia,"[{'zoneName': 'Asia/Aden', 'gmtOffset': 10800,...","{'kr': '예멘', 'br': 'Iêmen', 'pt': 'Iémen', 'nl...",15.000000,48.0,🇾🇪,U+1F1FE U+1F1EA,"[{'id': 1242, 'name': ''Adan Governorate', 'st..."
248,246,Zambia,ZMB,ZM,260,Lusaka,ZMW,ZK,.zm,Zambia,Africa,Eastern Africa,"[{'zoneName': 'Africa/Lusaka', 'gmtOffset': 72...","{'kr': '잠비아', 'br': 'Zâmbia', 'pt': 'Zâmbia', ...",-15.000000,30.0,🇿🇲,U+1F1FF U+1F1F2,"[{'id': 1986, 'name': 'Central Province', 'sta..."
249,247,Zimbabwe,ZWE,ZW,263,Harare,ZWL,$,.zw,Zimbabwe,Africa,Eastern Africa,"[{'zoneName': 'Africa/Harare', 'gmtOffset': 72...","{'kr': '짐바브웨', 'br': 'Zimbabwe', 'pt': 'Zimbab...",-20.000000,30.0,🇿🇼,U+1F1FF U+1F1FC,"[{'id': 1956, 'name': 'Bulawayo Province', 'st..."

##Check Structure of your Json
####Professional workflow: Always inspect raw JSON
`import json`

`with open("countries_states_cities.json") as f: `

   ` data = json.load(f)`

`type(data)`

Most likely output:

list

Which means:

list of dictionaries

This matches orient="records".

In [21]:
import json
with open("dataset.json") as f:
  data =json.load(f)
type(data)

list

# Writing / Exporting Files
#Writing / Exporting CSV Files with Pandas

####CSV (Comma-Separated Values) is the most common format for saving tabular data. Pandas provides the df.to_csv() method to export a DataFrame to CSV.

In [22]:
from google.colab import files

uploaded = files.upload()

Saving tested[1].csv to tested[1].csv

In [23]:
import pandas as pd

import os

os.rename("tested[1].csv", "tested.csv")
df = pd.read_csv("tested.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

## df.to_csv() Basics

####Export the full dataset to a CSV:

In [24]:
df.to_csv("titanic_exported.csv")

In [25]:
!ls

dataset.json  sample_data  tested.csv  titanic_exported.csv

####1. Exports all columns
####2. Includes index by default
####3. Missing values are blank by default

In [26]:
from google.colab import files

files.download('titanic_exported.csv')

##2. Handling Index (index=False)

####Usually you don’t need the numeric row index in a CSV:

In [29]:
df.to_csv('titanic_no_index.csv', index=False)

In [37]:
from google.colab import files

files.download('titanic_no_index.csv')

##3. Choosing Separators (sep)

####By default CSV is comma-separated, but sometimes:

####Excel in Europe expects semicolon (;)
Tab-separated files are easier to parse if some text contains commas

In [35]:
#Tab Separator
df.to_csv('titanic_tab.csv', sep='\t', index=False)

#Semicolon Separated
df.to_csv('titanic_semi.csv', sep=';', index=False)

from google.colab import files

files.download('titanic_tab.csv')

##4. Handling Missing Values (na_rep)

####Some columns like Age and Cabin have missing values. Use na_rep to mark them explicitly:

In [38]:
df.to_csv('titanic_na.csv', index=False, na_rep='MISSING')

In [39]:
from google.colab import files

files.download('titanic_na.csv')

##5. Writing Large Files in Chunks

###1. What are Chunks?

####A chunk is basically a smaller part of a big dataset.

####Think of a huge Excel file with millions of rows. Loading it all into memory at once can crash your computer, because Pandas tries to read everything at once.

###2. Why Use Chunks?
####1. Memory efficiency: Your RAM isn’t overloaded.
####2. Speed: Process smaller parts quickly instead of waiting for the entire file.
####3. Streaming large files: Some files are too big to load at once (millions of rows).
####4. Incremental processing: You can calculate aggregates, filter, or clean chunk by chunk.

###3. How to Use Chunks in Pandas

#####There are two main cases:

###A. Reading large CSV files in chunks

####Use chunksize in pd.read_csv():

In [41]:
chunk_size = 200
for chunk in pd.read_csv('tested.csv', chunksize= chunk_size):
  print(chunk.shape)

(200, 12)
(200, 12)
(18, 12)

####pd.read_csv() doesn’t load the whole file, only 200 rows at a time.
####Each chunk is a DataFrame you can process.

###B. Writing large CSV files in chunks

####Sometimes the DataFrame is already in memory, but it’s huge.

####Writing all rows at once may consume too much memory.
Solution: split DataFrame into chunks and write incrementally.

In [43]:
chunk_size = 200  # rows per chunk

for i, start in enumerate(range(0, len(df), chunk_size)):
    df.iloc[start:start+chunk_size].to_csv(
        'titanic_large_chunks.csv',
        mode='a',          # append to file
        index=False,
        header=(i==0),     # write header only for first chunk
        na_rep='MISSING'
    )

##Writing / Exporting Excel Files with Pandas

In [44]:
from google.colab import files

uploaded = files.upload()

Saving Sample_-_Superstore_Sales_(Excel)[1].xlsx to Sample_-_Superstore_Sales_(Excel)[1].xlsx

In [45]:
df = pd.read_excel("Sample_-_Superstore_Sales_(Excel)[1].xlsx")
df.head()

,Row ID,Order ID,Order Date,Order Priority,Order Quantity,Sales,Discount,Ship Mode,Profit,Unit Price,...,Zip Code,State,Region,Customer Segment,Product Category,Product Sub-Category,Product Name,Product Container,Product Base Margin,Ship Date
0,1,3,2010-10-13,Low,6,261.5400,0.04,Regular Air,-213.250,38.94,...,60035,Illinois,Central,Small Business,Office Supplies,Storage & Organization,"Eldon Base for stackable storage shelf, platinum",Large Box,0.80,2010-10-20
1,2,6,2012-02-20,Not Specified,2,6.9300,0.01,Regular Air,-4.640,2.08,...,98026,Washington,West,Corporate,Office Supplies,"Scissors, Rulers and Trimmers",Kleencut® Forged Office Shears by Acme United ...,Small Pack,0.55,2012-02-21
2,3,32,2011-07-15,High,26,2808.0800,0.07,Regular Air,1054.820,107.53,...,98387,Washington,West,Corporate,Furniture,Office Furnishings,Tenex Contemporary Contur Chairmats for Low an...,Medium Box,0.65,2011-07-17
3,4,32,2011-07-15,High,24,1761.4000,0.09,Delivery Truck,-1748.560,70.89,...,98387,Washington,West,Corporate,Furniture,Tables,KI Conference Tables,Jumbo Box,0.72,2011-07-16
4,5,32,2011-07-15,High,23,160.2335,0.04,Regular Air,-85.129,7.99,...,98387,Washington,West,Corporate,Technology,Telephones and Communication,Bell Sonecor JB700 Caller ID,Medium Box,0.60,2011-07-17

In [46]:
os.rename("Sample_-_Superstore_Sales_(Excel)[1].xlsx", "Sales.xlsx")
df = pd.read_excel("Sales.xlsx")
df.head()

,Row ID,Order ID,Order Date,Order Priority,Order Quantity,Sales,Discount,Ship Mode,Profit,Unit Price,...,Zip Code,State,Region,Customer Segment,Product Category,Product Sub-Category,Product Name,Product Container,Product Base Margin,Ship Date
0,1,3,2010-10-13,Low,6,261.5400,0.04,Regular Air,-213.250,38.94,...,60035,Illinois,Central,Small Business,Office Supplies,Storage & Organization,"Eldon Base for stackable storage shelf, platinum",Large Box,0.80,2010-10-20
1,2,6,2012-02-20,Not Specified,2,6.9300,0.01,Regular Air,-4.640,2.08,...,98026,Washington,West,Corporate,Office Supplies,"Scissors, Rulers and Trimmers",Kleencut® Forged Office Shears by Acme United ...,Small Pack,0.55,2012-02-21
2,3,32,2011-07-15,High,26,2808.0800,0.07,Regular Air,1054.820,107.53,...,98387,Washington,West,Corporate,Furniture,Office Furnishings,Tenex Contemporary Contur Chairmats for Low an...,Medium Box,0.65,2011-07-17
3,4,32,2011-07-15,High,24,1761.4000,0.09,Delivery Truck,-1748.560,70.89,...,98387,Washington,West,Corporate,Furniture,Tables,KI Conference Tables,Jumbo Box,0.72,2011-07-16
4,5,32,2011-07-15,High,23,160.2335,0.04,Regular Air,-85.129,7.99,...,98387,Washington,West,Corporate,Technology,Telephones and Communication,Bell Sonecor JB700 Caller ID,Medium Box,0.60,2011-07-17

##1. df.to_excel()

In [47]:
df.to_excel('superstore_exported.xlsx', index=False)

In [48]:
from google.colab import files

files.download('superstore_exported.xlsx')

In [49]:
df.to_excel('superstore_exported_index.xlsx', index=False)
from google.colab import files

files.download('superstore_exported_index.xlsx')

##2. Writing Multiple Sheets

####You can save multiple DataFrames in one Excel file, each in a separate sheet:

In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8399 entries, 0 to 8398
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Row ID                8399 non-null   int64
 1   Order ID              8399 non-null   int64
 2   Order Date            8399 non-null   datetime64[ns]
 3   Order Priority        8399 non-null   object
 4   Order Quantity        8399 non-null   int64
 5   Sales                 8399 non-null   float64
 6   Discount              8399 non-null   float64
 7   Ship Mode             8399 non-null   object
 8   Profit                8399 non-null   float64
 9   Unit Price            8399 non-null   float64
 10  Shipping Cost         8399 non-null   float64
 11  Customer Name         8399 non-null   object
 12  City                  8399 non-null   object
 13  Zip Code              8399 non-null   int64
 14  State                 8399 non-null   object
 15  Region                8399 non-null   object
 16  Customer Segment      8399 non-null   object
 17  Product Category      8399 non-null   object
 18  Product Sub-Category  8399 non-null   object
 19  Product Name          8399 non-null   object
 20  Product Container     8399 non-null   object
 21  Product Base Margin   8336 non-null   float64
 22  Ship Date             8399 non-null   datetime64[ns]
dtypes: datetime64[ns](2), float64(6), int64(4), object(11)
memory usage: 1.5+ MB

In [53]:
df_sales = df[['Order ID', 'Sales', 'Profit']]
df_customers = df[['Customer Name', 'Customer Segment', 'City']]

with pd.ExcelWriter('superstore_multi.xlsx', engine='openpyxl') as writer:
  df_sales.to_excel(writer, sheet_name='Sales', index=False)
  df_customers.to_excel(writer, sheet_name='Customers', index=False)

In [54]:
from google.colab import files

files.download('superstore_multi.xlsx')

##3. Handling Index and Columns

In [56]:
df.to_excel('superstore_with_index.xlsx', index=True)

####First column will now have the row index.

###Export only specific columns

In [58]:
df.to_excel(
    'superstore_selected_cols.xlsx',
    columns=['Order ID', 'Order Date', 'Sales', 'Profit'],
    index=False)